using System.Buffers.Binary;
using iTunesPod.Core;
using iTunesPod.Infrastructure;
namespace iTunesPod.Tests;
public class NativeMediaTests
{
    [Fact] public void NativePhotoRoundTripRetainsAlbumsAndOriginalReference(){var database=new NativeImageDatabase(null,true);var image=database.AddImage(0,[new(1079,80,80,new byte[12800]),new(1024,320,240,new byte[153600])],"Photos/Thumbs","原图.jpg",[1,2,3]);var master=Assert.Single(database.Albums());database.SetAlbum(master.Id,master.Name,[image.Id]);database.AddAlbum("旅行",[image.Id,image.Id]);var raw=database.Build();var reloaded=new NativeImageDatabase(raw,true);Assert.Equal(raw,reloaded.Build());Assert.Equal(3,Assert.Single(reloaded.Images()).Images.Count);Assert.Equal(2,reloaded.Albums()[1].Images.Count);reloaded.RemoveImage(image.Id);Assert.Empty(reloaded.Images());Assert.All(reloaded.Albums(),x=>Assert.Empty(x.Images));Assert.Throws<IOException>(()=>reloaded.RemoveAlbum(master.Id));}
    [Fact] public void NativeArtworkKeepsPersistentTrackIdAndBounds(){var database=new NativeImageDatabase(null);database.AddImage(12345678,[new(1074,50,50,new byte[5000])],"iPod_Control/Artwork");var image=Assert.Single(new NativeImageDatabase(database.Build()).Images());Assert.Equal(12345678ul,image.TrackId);Assert.Equal(5000,Assert.Single(image.Images).Size);var raw=database.Build();BinaryPrimitives.WriteUInt32LittleEndian(raw.AsSpan(8),uint.MaxValue);Assert.Throws<InvalidDataException>(()=>new NativeImageDatabase(raw));}
    [Fact] public void SmartRulesRoundTripNativeBigEndianAndKeepDuplicateData(){var definition=new SmartDefinition(false,[new(4,"包含","甲"),new(25,"大于","3")],"评分",25);var records=SmartPlaylistBinary.Encode(definition);var parsed=SmartPlaylistBinary.Decode(records[0],records[1]);Assert.NotNull(parsed);Assert.Equal(definition.Rules,parsed.Rules);Assert.Equal(definition.MatchAll,parsed.MatchAll);Assert.Equal(25,parsed.Limit);var a=new Track("a","","","a","甲","专辑","甲",1,1,2026,60,100,Rating:1);var b=a with{Id="b",Artist="乙",Rating=5};Assert.Equal(new[]{"b","a"},SmartPlaylists.Evaluate(definition,[a,b]).Select(x=>x.Id));records[1][24+136+8]=1;Assert.Null(SmartPlaylistBinary.Decode(records[0],records[1]));}
    [Fact] public void PodcastRejectsEntitiesAndKeepsStableGuid(){var xml="<rss><channel><title>节目</title><item><title>一集</title><guid>stable</guid><enclosure url='https://example.com/one.mp3'/></item></channel></rss>";var first=Assert.Single(PodcastService.Parse(xml,"https://example.com/feed"));var changed=Assert.Single(PodcastService.Parse(xml.Replace("一集","改名"),"https://example.com/feed"));Assert.Equal(first.Id,changed.Id);Assert.Throws<System.Xml.XmlException>(()=>PodcastService.Parse("<!DOCTYPE rss [<!ENTITY x SYSTEM 'file:///c:/secret'>]><rss><channel><title>&x;</title></channel></rss>","https://example.com"));}
    [Fact] public void NotesUseEncodedByteLimit(){Assert.Throws<IOException>(()=>DeviceNotes.Save("../escape","text"));Assert.Throws<IOException>(()=>DeviceNotes.Save("中文",new string('中',1400)));var note=DeviceNotes.Save("笔记","第一行\n第二行");Assert.Equal("Notes/笔记.txt",note.RelativePath);Assert.True(note.Content!.Length<4096);}
    [Fact] public void M3uRoundTripPreservesRepeatedUnicodePaths(){var root=Path.Combine(Path.GetTempPath(),"itp-m3u-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{var file=Path.Combine(root,"列表.m3u8");var track=new Track("a",Path.Combine(root,"音乐","歌曲.mp3"),"","歌","甲","专辑","甲",1,1,2026,60,100);PlaylistFiles.Write(file,[track,track]);Assert.Equal(new[]{track.Path,track.Path},PlaylistFiles.Read(file));}finally{Directory.Delete(root,true);}}
}
