using System.Text.Json;
using iTunesPod.Infrastructure;
using Microsoft.Data.Sqlite;
namespace iTunesPod.Tests;
public sealed class TransactionTests:IDisposable
{
    readonly string _host=Path.Combine(Path.GetTempPath(),"itp-tx-"+Guid.NewGuid().ToString("N"));readonly string _root;
    public TransactionTests(){_root=Path.Combine(_host,"device");Directory.CreateDirectory(Path.Combine(_root,"iPod_Control/iTunes"));Directory.CreateDirectory(Path.Combine(_root,"iPod_Control/Device"));File.WriteAllBytes(Path.Combine(_root,"iPod_Control/iTunes/iTunesDB"),WriterTests.Fixture());File.WriteAllText(Path.Combine(_root,"iPod_Control/Device/SysInfo"),"ModelNumStr: MB751\nSerialNumber: TX-FIXTURE\nFirewireGuid: 0011223344556677");Directory.CreateDirectory(Path.Combine(_root,"Notes"));File.WriteAllText(Path.Combine(_root,"Notes/old.txt"),"before");}
    public void Dispose(){SqliteConnection.ClearAllPools();Directory.Delete(_host,true);}
    [Fact]public async Task FailureAfterWritesRollsBackAllMutations(){var session=await new DeviceAccess().InspectAsync(_root);await Assert.ThrowsAsync<IOException>(()=>DeviceFileTransaction.ApplyCoreAsync(session,[DeviceNotes.Save("old.txt","changed"),DeviceNotes.Save("new.txt","created")],Path.Combine(_host,"data"),CancellationToken.None,true,()=>throw new IOException("injected verify failure")));Assert.Equal("before",await File.ReadAllTextAsync(Path.Combine(_root,"Notes/old.txt")));Assert.False(File.Exists(Path.Combine(_root,"Notes/new.txt")));Assert.Equal(session.Generation,(await new DeviceAccess().InspectAsync(_root)).Generation);Assert.False(File.Exists(Path.Combine(_root,"iPod_Control/iTunes/.itp-lock")));}
    [Fact]public async Task ExternalChangesAreNeverOverwrittenDuringRecovery(){var session=await new DeviceAccess().InspectAsync(_root);await Assert.ThrowsAsync<IOException>(()=>DeviceFileTransaction.ApplyCoreAsync(session,[DeviceNotes.Save("old.txt","changed")],Path.Combine(_host,"data"),CancellationToken.None,true,async()=>{await File.WriteAllTextAsync(Path.Combine(_root,"Notes/old.txt"),"external edit");throw new IOException("injected external failure");}));Assert.Equal("external edit",await File.ReadAllTextAsync(Path.Combine(_root,"Notes/old.txt")));var journal=Directory.EnumerateFiles(Path.Combine(_host,"data/file-transactions"),"journal.json",SearchOption.AllDirectories).Single();Assert.Equal("RecoveryRequired",JsonSerializer.Deserialize<FileJournal>(await File.ReadAllTextAsync(journal))!.Phase);}
    [Fact]public async Task StaleGenerationStopsBeforeAnyChanges(){var session=await new DeviceAccess().InspectAsync(_root);var data=await File.ReadAllBytesAsync(Path.Combine(_root,"iPod_Control/iTunes/iTunesDB"));data[32]^=1;await File.WriteAllBytesAsync(Path.Combine(_root,"iPod_Control/iTunes/iTunesDB"),data);await Assert.ThrowsAsync<IOException>(()=>DeviceFileTransaction.ApplyAsync(session,[DeviceNotes.Save("old.txt","changed")],Path.Combine(_host,"data")));Assert.Equal("before",await File.ReadAllTextAsync(Path.Combine(_root,"Notes/old.txt")));}
    [Fact]public async Task CompleteBackupRestoresChangedMedia(){var music=Path.Combine(_root,"iPod_Control/Music/F00");Directory.CreateDirectory(music);var audio=Path.Combine(music,"original.mp3");await File.WriteAllBytesAsync(audio,[1,2,3,4]);var session=await new DeviceAccess().InspectAsync(_root);var backup=await DeviceBackup.CreateAsync(session,Path.Combine(_host,"original-backups"),true);await File.WriteAllBytesAsync(audio,[5,6,7]);await DeviceFileTransaction.RestoreFullAsync(session,backup,Path.Combine(_host,"data"));Assert.Equal(new byte[]{1,2,3,4},await File.ReadAllBytesAsync(audio));}
    [Fact]public async Task InterruptedBackupResumesAndRejectsChangedGeneration(){var session=await new DeviceAccess().InspectAsync(_root);var folder=Path.Combine(_host,"resume");Directory.CreateDirectory(folder);await File.WriteAllTextAsync(Path.Combine(folder,"INCOMPLETE"),"unfinished");await File.WriteAllTextAsync(Path.Combine(folder,"request.json"),JsonSerializer.Serialize(new BackupManifest(session.DeviceId,session.Generation,true,DateTime.UtcNow,[])));await DeviceBackup.ResumeAsync(session,folder);var manifest=await DeviceBackup.VerifyAsync(folder);Assert.True(manifest.Full);Assert.Contains(manifest.Files,x=>x.RelativePath.Replace((char)92,(char)47)=="Notes/old.txt");await File.WriteAllTextAsync(Path.Combine(folder,"INCOMPLETE"),"unfinished");await Assert.ThrowsAsync<IOException>(()=>DeviceBackup.ResumeAsync(session with{Generation=new string('0',64)},folder));}
    [Fact]public async Task MetadataRestoreRemovesAddedNotesAndKeepsMusic(){var session=await new DeviceAccess().InspectAsync(_root);var backup=await DeviceBackup.CreateAsync(session,Path.Combine(_host,"snapshot"),false);File.WriteAllText(Path.Combine(_root,"Notes/new.txt"),"new");var music=Path.Combine(_root,"iPod_Control/Music/F00");Directory.CreateDirectory(music);File.WriteAllBytes(Path.Combine(music,"extra.mp3"),[1,2,3]);await DeviceFileTransaction.RestoreMetadataAsync(session,backup,Path.Combine(_host,"data"));Assert.False(File.Exists(Path.Combine(_root,"Notes/new.txt")));Assert.True(File.Exists(Path.Combine(music,"extra.mp3")));Assert.Equal("before",File.ReadAllText(Path.Combine(_root,"Notes/old.txt")));}
}
