using System.Globalization;
namespace iTunesPod.Core;
public static class SmartPlaylists
{
    public static readonly IReadOnlyDictionary<int,string> Fields=new Dictionary<int,string>{{2,"标题"},{3,"专辑"},{4,"艺术家"},{7,"年份"},{8,"流派"},{13,"时长（秒）"},{16,"添加日期"},{23,"最近播放日期"},{22,"播放次数"},{25,"评分（0—5）"},{60,"媒体类型"},{71,"专辑艺术家"}};
    public static bool IsDate(int field)=>field is 16 or 23;
    public static bool IsText(int field)=>field is 2 or 3 or 4 or 8 or 71;
    public static IReadOnlyList<Track> Evaluate(SmartDefinition definition,IEnumerable<Track> tracks){if(definition.Rules.Count is <1 or >64||definition.Limit<0||definition.Limit>200000)throw new InvalidDataException("智能列表条件或数量无效。");bool Match(Track t,SmartRule r){if(!Fields.ContainsKey(r.Field))throw new InvalidDataException("未知规则字段。");if(IsDate(r.Field)){if(!int.TryParse(r.Value,out var days)||days<1||days>36500)throw new InvalidDataException("日期规则需要 1—36500 天。");var date=r.Field==16?t.AddedUtc:t.LastPlayedUtc;var recent=date!=null&&date>=DateTimeOffset.UtcNow.AddDays(-days)&&date<=DateTimeOffset.UtcNow;return r.Comparison switch{"在最近天数内"=>recent,"不在最近天数内"=>!recent,_=>throw new InvalidDataException("日期规则请选择最近天数比较。")};}if(IsText(r.Field)){var text=r.Field switch{2=>t.Title,3=>t.Album,4=>t.Artist,8=>t.Genre,_=>t.AlbumArtist};return r.Comparison switch{"包含"=>text.Contains(r.Value,StringComparison.OrdinalIgnoreCase),"不包含"=>!text.Contains(r.Value,StringComparison.OrdinalIgnoreCase),"等于"=>text.Equals(r.Value,StringComparison.OrdinalIgnoreCase),"不等于"=>!text.Equals(r.Value,StringComparison.OrdinalIgnoreCase),"开头是"=>text.StartsWith(r.Value,StringComparison.OrdinalIgnoreCase),"结尾是"=>text.EndsWith(r.Value,StringComparison.OrdinalIgnoreCase),_=>throw new InvalidDataException("文字比较条件无效。")};}if(!double.TryParse(r.Value,NumberStyles.Float,CultureInfo.InvariantCulture,out var wanted)||wanted<0)throw new InvalidDataException("数字规则需要非负数字。");var actual=r.Field switch{7=>t.Year,13=>t.Seconds,22=>t.PlayCount,25=>t.Rating,60=>t.MediaType,_=>0d};if(r.Field==60){var mask=checked((uint)wanted);return r.Comparison switch{"等于"=>(t.MediaType&mask)!=0,"不等于"=>(t.MediaType&mask)==0,_=>throw new InvalidDataException("媒体类型仅支持等于或不等于。")};}return r.Comparison switch{"等于"=>actual==wanted,"不等于"=>actual!=wanted,"大于"=>actual>wanted,"小于"=>actual<wanted,_=>throw new InvalidDataException("数字比较条件无效。")};}
        // Validate every rule even for an empty library.
        var dummy=new Track("","","","","","","",0,0,0,0,0);foreach(var rule in definition.Rules)Match(dummy,rule);
        var filtered=tracks.Where(t=>definition.MatchAll?definition.Rules.All(r=>Match(t,r)):definition.Rules.Any(r=>Match(t,r)));var sorted=definition.Sort switch{"评分"=>filtered.OrderByDescending(x=>x.Rating),"播放次数"=>filtered.OrderByDescending(x=>x.PlayCount),"最近添加"=>filtered.OrderByDescending(x=>x.AddedUtc),"最近播放"=>filtered.OrderByDescending(x=>x.LastPlayedUtc),"艺术家"=>filtered.OrderBy(x=>x.Artist,StringComparer.OrdinalIgnoreCase),"专辑"=>filtered.OrderBy(x=>x.Album,StringComparer.OrdinalIgnoreCase),_=>filtered.OrderBy(x=>x.Title,StringComparer.OrdinalIgnoreCase)};if(definition.LimitUnit is not ("首" or "分钟" or "小时"))throw new InvalidDataException("限制单位无效。");if(definition.Limit==0)return sorted.ToArray();if(definition.LimitUnit=="首")return sorted.Take(definition.Limit).ToArray();var budget=definition.Limit*(definition.LimitUnit=="小时"?3600d:60d);var selected=new List<Track>();foreach(var track in sorted){if(track.Seconds<0)throw new InvalidDataException("曲目时长无效。");if(track.Seconds>budget)continue;selected.Add(track);budget-=track.Seconds;}return selected;}
}
