using System.Text.Json;
using iTunesPod.Core;
namespace iTunesPod.Infrastructure;
public sealed record DeviceMediaHash(uint Id,string RelativePath,long Bytes,long Modified,string Hash);
public sealed record SourceDeviceLink(string SourceId,string SourceHash,string PayloadHash,uint DeviceTrackId);
public static class DeviceMediaIndex
{
    public static IReadOnlyList<SourceDeviceLink> LoadLinks(string deviceId,string host){var path=Path.Combine(host,"source-device-links",deviceId.Replace(':','_')+".json");return File.Exists(path)?JsonSerializer.Deserialize<List<SourceDeviceLink>>(File.ReadAllText(path))??[]:[];}
    public static void SaveLinks(string deviceId,string host,IEnumerable<SourceDeviceLink> links){var folder=Path.Combine(host,"source-device-links");Directory.CreateDirectory(folder);var path=Path.Combine(folder,deviceId.Replace(':','_')+".json");File.WriteAllText(path+".tmp",JsonSerializer.Serialize(links.DistinctBy(x=>x.SourceId)));File.Move(path+".tmp",path,true);}
    public static async Task<IReadOnlyList<DeviceMediaHash>> BuildAsync(DeviceSession session,string host,IProgress<string>? progress=null,CancellationToken token=default){var folder=Path.Combine(host,"device-media-index");Directory.CreateDirectory(folder);var path=Path.Combine(folder,session.DeviceId.Replace(':','_')+".json");var previous=File.Exists(path)?JsonSerializer.Deserialize<List<DeviceMediaHash>>(await File.ReadAllTextAsync(path,token))??[]:[];var lookup=previous.ToDictionary(x=>x.Id);var result=new List<DeviceMediaHash>();foreach(var track in session.Tracks){token.ThrowIfCancellationRequested();if(!File.Exists(track.Path))continue;var id=uint.Parse(track.Id[7..]);var file=new FileInfo(track.Path);var relative=Path.GetRelativePath(session.Root,track.Path);if(lookup.TryGetValue(id,out var cached)&&cached.RelativePath.Equals(relative,StringComparison.OrdinalIgnoreCase)&&cached.Bytes==file.Length&&cached.Modified==file.LastWriteTimeUtc.Ticks){result.Add(cached);continue;}progress?.Report("核对设备内容："+track.Title);var beforeLength=file.Length;var beforeTime=file.LastWriteTimeUtc;var hash=await DeviceBackup.HashAsync(track.Path,token);file.Refresh();if(file.Length!=beforeLength||file.LastWriteTimeUtc!=beforeTime)throw new IOException("核对时设备媒体发生改变，请刷新重试。");result.Add(new(id,relative,file.Length,file.LastWriteTimeUtc.Ticks,hash));}await File.WriteAllTextAsync(path,JsonSerializer.Serialize(result),token);return result;}
}
