using System.Buffers.Binary;
using System.Text.Json;
using static iTunesPod.Infrastructure.ITunesDbWriter;
namespace iTunesPod.Infrastructure;
public static class DeviceClock
{
    const long Epoch=2082844800;
    public static int DatabaseOffset(byte[] database)=>U(database,4)>=112?BinaryPrimitives.ReadInt32LittleEndian(database.AsSpan(108)):0;
    public static int CurrentOffset(string root,byte[] database){var preferences=DeviceAccess.SafePath(root,"iPod_Control/Device/Preferences");if(File.Exists(preferences)){var bytes=File.ReadAllBytes(preferences);if(bytes.Length is 2952 or 2956 or 2960){var city=BinaryPrimitives.ReadUInt16LittleEndian(bytes.AsSpan(0xb70));using var stream=typeof(DeviceClock).Assembly.GetManifestResourceStream("iTunesPod.Infrastructure.Data.device-timezones.json")!;var names=JsonSerializer.Deserialize<Dictionary<string,string>>(stream)!;if(names.TryGetValue(city.ToString(),out var zone)){zone=zone switch{"PST8PDT"=>"America/Los_Angeles","EST5EDT"=>"America/New_York","MST7MDT"=>"America/Denver","CST6CDT"=>"America/Chicago",_=>zone};try{return (int)TimeZoneInfo.FindSystemTimeZoneById(zone).GetUtcOffset(DateTimeOffset.UtcNow).TotalSeconds;}catch(TimeZoneNotFoundException){}catch(InvalidTimeZoneException){}}}}var offset=DatabaseOffset(database);if(Math.Abs((long)offset)>14*3600)throw new IOException("数据库时区偏移无效。");return offset;}
    public static DateTimeOffset? Read(uint value,int offset)=>value is 0 or uint.MaxValue?null:DateTimeOffset.FromUnixTimeSeconds((long)value-Epoch-offset);
    public static byte[] Normalize(byte[] original,int offset,ReadOnlySpan<byte> identity){if(!DeviceChecksum.VerifyHash58(original,identity)||U(original,4)<112)throw new IOException("数据库签名或时区头无效。");var before=DatabaseOffset(original);if(before==offset)return original;if(new ITunesDbReader().ReadPlaylists(original).Any(x=>x.IsSmart&&x.SmartDefinition==null))throw new IOException("未知智能列表可能包含绝对日期，不能更改数据库时区。");if(Math.Abs((long)offset)>14*3600||Math.Abs((long)before)>14*3600)throw new IOException("设备时区无法确认。");var delta=offset-before;void Shift(byte[] record,int field){var value=BinaryPrimitives.ReadUInt32LittleEndian(record.AsSpan(field));if(value is 0 or uint.MaxValue)return;BinaryPrimitives.WriteUInt32LittleEndian(record.AsSpan(field),checked((uint)((long)value+delta)));}var sections=Children(original,U(original,4));for(var s=0;s<sections.Count;s++){var section=sections[s];var type=U(section,12);if(type is not (1 or 2 or 3))throw new IOException("额外分区的时区字段尚未支持。");var sh=U(section,4);var lh=U(section,sh+4);var records=Children(section,sh+lh);for(var i=0;i<records.Count;i++){var record=records[i];if(type==1){foreach(var field in new[]{32,88,104,140,160,220})if(U(record,4)>=field+4)Shift(record,field);}else{Shift(record,24);if(U(record,4)>=92)Shift(record,88);var children=Children(record,U(record,4));foreach(var child in children.Where(x=>Magic(x)=="mhip"&&U(x,4)>=32))Shift(child,28);record=Join(record.AsSpan(0,U(record,4)).ToArray(),children);}records[i]=record;}_sectionsUpdate();void _sectionsUpdate()=>sections[s]=Join(section.AsSpan(0,sh).ToArray(),[Join(section.AsSpan(sh,lh).ToArray(),records,true)]);}var header=original.AsSpan(0,U(original,4)).ToArray();BinaryPrimitives.WriteInt32LittleEndian(header.AsSpan(108),offset);return DeviceChecksum.SignHash58(Join(header,sections),identity);}
}
