using System.Security.Cryptography;
using System.Text.Json;
using iTunesPod.Core;
namespace iTunesPod.Infrastructure;
public sealed record BackupFile(string RelativePath,string Hash,long Bytes);
public sealed record BackupManifest(string DeviceId,string Generation,bool Full,DateTime CreatedUtc,IReadOnlyList<BackupFile> Files);
public static class DeviceBackup
{
    public static string Destination(string host,string deviceId){var settings=new LibraryStore(host);return Path.Combine(settings.GetPreference("backup-directory",Path.Combine(host,"backups")),deviceId.Replace(':','_'));}
    public static int Prune(string destination,string host,int keep){if(keep<10)throw new IOException("至少保留 10 份备份。");if(!Directory.Exists(destination))return 0;var protectedFolders=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var type in new[]{"transactions","file-transactions"}){var root=Path.Combine(host,type);if(!Directory.Exists(root))continue;foreach(var path in Directory.EnumerateFiles(root,"journal.json",SearchOption.AllDirectories)){using var json=JsonDocument.Parse(File.ReadAllText(path));var phase=json.RootElement.GetProperty("Phase").GetString();if(phase is "Complete" or "RolledBack")continue;var property=type=="transactions"?"BackupDirectory":"Backup";if(json.RootElement.TryGetProperty(property,out var backup)&&backup.GetString() is string value)protectedFolders.Add(Path.GetFullPath(value));}}var folders=Directory.EnumerateDirectories(destination).Where(x=>File.Exists(Path.Combine(x,"manifest.json"))&&!File.Exists(Path.Combine(x,"INCOMPLETE"))).OrderByDescending(Path.GetFileName).ToArray();var removed=0;foreach(var folder in folders.Skip(keep)){var safe=DeviceAccess.SafePath(destination,Path.GetFileName(folder));if(protectedFolders.Contains(Path.GetFullPath(safe)))continue;foreach(var entry in Directory.EnumerateFileSystemEntries(safe,"*",new EnumerationOptions{RecurseSubdirectories=true,AttributesToSkip=0}))if((File.GetAttributes(entry)&FileAttributes.ReparsePoint)!=0)throw new IOException("备份中有链接，停止清理。");Directory.Delete(safe,true);removed++;}return removed;}
    internal static async Task<string> HashAsync(string path,CancellationToken token=default){await using var f=File.OpenRead(path);return Convert.ToHexString(await SHA256.HashDataAsync(f,token));}
    internal static async Task CopyAsync(string source,string target,CancellationToken token){Directory.CreateDirectory(Path.GetDirectoryName(target)!);await using var input=new FileStream(source,FileMode.Open,FileAccess.Read,FileShare.Read,81920,true);await using var output=new FileStream(target,FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,FileOptions.Asynchronous|FileOptions.WriteThrough);await input.CopyToAsync(output,token);await output.FlushAsync(token);output.Flush(true);}
    public static async Task<IReadOnlyDictionary<string,string>> MetadataHashesAsync(string root,CancellationToken token=default){var result=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);foreach(var name in new[]{"iPod_Control","Photos","Notes"}){var directory=DeviceAccess.SafePath(root,name);if(!Directory.Exists(directory))continue;foreach(var file in EnumerateSafe(directory)){var relative=Path.GetRelativePath(root,file).Replace((char)92,(char)47);if(relative.StartsWith("iPod_Control/Music/",StringComparison.OrdinalIgnoreCase))continue;result[relative]=await HashAsync(file,token);}}return result;}
    public static async Task<string> CreateAsync(DeviceSession session,string destination,bool full,IProgress<string>? progress=null,CancellationToken token=default)
    {
        var root=Path.GetFullPath(session.Root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;var host=Path.GetFullPath(destination).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;if(host.StartsWith(root,StringComparison.OrdinalIgnoreCase))throw new IOException("备份必须位于设备之外。");
        var folder=DeviceAccess.SafePath(host,DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N")[..8]);Directory.CreateDirectory(folder);
        await File.WriteAllTextAsync(Path.Combine(folder,"INCOMPLETE"),"备份未完成",token);
        await WriteManifest(Path.Combine(folder,"request.json"),new BackupManifest(session.DeviceId,session.Generation,full,DateTime.UtcNow,[]),token);
        return await ResumeAsync(session,folder,progress,token);
    }
    public static async Task<string> ResumeAsync(DeviceSession session,string folder,IProgress<string>? progress=null,CancellationToken token=default)
    {
        if(!File.Exists(Path.Combine(folder,"INCOMPLETE")))throw new IOException("备份已经完成。");
        var request=JsonSerializer.Deserialize<BackupManifest>(await File.ReadAllTextAsync(Path.Combine(folder,"request.json"),token))??throw new IOException("备份请求无效。");
        if(request.DeviceId!=session.DeviceId||request.Generation!=session.Generation)throw new IOException("设备或数据库代次已变化，请创建新备份。");
        var root=Path.GetFullPath(session.Root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;if((Path.GetFullPath(folder)+Path.DirectorySeparatorChar).StartsWith(root,StringComparison.OrdinalIgnoreCase))throw new IOException("备份必须位于设备之外。");
        var paths=new List<string>();foreach(var directory in new[]{"iPod_Control","Photos","Notes"}){var sourceRoot=DeviceAccess.SafePath(root,directory);if(Directory.Exists(sourceRoot))paths.AddRange(EnumerateSafe(sourceRoot).Where(x=>request.Full||!Path.GetRelativePath(root,x).Replace((char)92,(char)47).StartsWith("iPod_Control/Music/",StringComparison.OrdinalIgnoreCase)));}
        var files=new List<BackupFile>();foreach(var source in paths){token.ThrowIfCancellationRequested();var relative=Path.GetRelativePath(root,source);var safe=DeviceAccess.SafePath(root,relative);progress?.Report(relative);var hash=await HashAsync(safe,token);var target=DeviceAccess.SafePath(folder,relative);if(!File.Exists(target)||await HashAsync(target,token)!=hash){if(File.Exists(target))File.Delete(target);var free=new DriveInfo(Path.GetPathRoot(target)!).AvailableFreeSpace;if(new FileInfo(safe).Length+64L*1024*1024>free)throw new IOException("电脑备份空间不足，任务可继续。");await CopyAsync(safe,target,token);}if(await HashAsync(target,token)!=hash||await HashAsync(safe,token)!=hash)throw new IOException("备份期间内容更改："+relative);files.Add(new(relative,hash,new FileInfo(target).Length));}
        if(await HashAsync(DeviceAccess.SafePath(root,session.DatabaseFile),token)!=session.Generation)throw new IOException("数据库已更改，请重新创建备份。");
        foreach(var file in files)if(await HashAsync(DeviceAccess.SafePath(root,file.RelativePath),token)!=file.Hash)throw new IOException("设备内容在备份期间变化，请重新创建备份。");
        await WriteManifest(Path.Combine(folder,"manifest.json"),request with{Files=files},token);File.Delete(Path.Combine(folder,"INCOMPLETE"));return folder;
    }
    static async Task WriteManifest(string path,BackupManifest manifest,CancellationToken token){var pending=path+".tmp";await using(var stream=new FileStream(pending,FileMode.Create,FileAccess.Write,FileShare.None,81920,FileOptions.WriteThrough)){await JsonSerializer.SerializeAsync(stream,manifest,cancellationToken:token);await stream.FlushAsync(token);stream.Flush(true);}File.Move(pending,path,true);}
    static IEnumerable<string> EnumerateSafe(string root){foreach(var path in Directory.EnumerateFileSystemEntries(root)){if((File.GetAttributes(path)&FileAttributes.ReparsePoint)!=0)throw new IOException("备份不跟随链接。");if(Directory.Exists(path)){foreach(var file in EnumerateSafe(path))yield return file;}else if(!Path.GetFileName(path).Contains(".itp-",StringComparison.Ordinal))yield return path;}}
    public static async Task<BackupManifest> VerifyAsync(string folder,CancellationToken token=default){if(File.Exists(Path.Combine(folder,"INCOMPLETE")))throw new IOException("备份未完成。");var manifest=JsonSerializer.Deserialize<BackupManifest>(await File.ReadAllTextAsync(Path.Combine(folder,"manifest.json"),token))??throw new IOException("清单无效。");if(string.IsNullOrWhiteSpace(manifest.DeviceId)||manifest.Generation.Length!=64||manifest.Files.Count==0||manifest.Files.Select(x=>x.RelativePath).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=manifest.Files.Count)throw new IOException("备份清单缺少身份或文件集合。");foreach(var entry in manifest.Files){var path=DeviceAccess.SafePath(folder,entry.RelativePath);if(new FileInfo(path).Length!=entry.Bytes||await HashAsync(path,token)!=entry.Hash)throw new IOException("备份损坏："+entry.RelativePath);}return manifest;}
}
