using System.Text.Json;
using iTunesPod.Core;
namespace iTunesPod.Infrastructure;
public sealed record FileChange(string RelativePath,byte[]? Content,string? SourceFile=null){public string? ExpectedBeforeHash{get;init;}public bool CheckBefore{get;init;}}
public sealed record FileReceipt(string RelativePath,string? BeforeHash,string? AfterHash);
public sealed record FileJournal(string DeviceId,string Root,string Backup,string Phase,IReadOnlyList<FileReceipt> Files);
public static class DeviceFileTransaction
{
    public static async Task<string> RestoreFullAsync(DeviceSession session,string backupFolder,string host,CancellationToken token=default){var manifest=await DeviceBackup.VerifyAsync(backupFolder,token);if(!manifest.Full||manifest.DeviceId!=session.DeviceId)throw new IOException("需要属于当前设备的完整备份。");var sourceDb=DeviceAccess.SafePath(backupFolder,session.DatabaseFile);var data=await File.ReadAllBytesAsync(sourceDb,token);if(!DeviceChecksum.VerifyHash58(data,session.SigningIdentity))throw new IOException("备份数据库签名不匹配。");var changes=new List<FileChange>();foreach(var file in manifest.Files){var relative=file.RelativePath.Replace((char)92,(char)47);if(relative.StartsWith("iPod_Control/Device/",StringComparison.OrdinalIgnoreCase))continue;var target=DeviceAccess.SafePath(session.Root,relative);if(File.Exists(target)&&await DeviceBackup.HashAsync(target,token)==file.Hash)continue;changes.Add(new(relative,null,DeviceAccess.SafePath(backupFolder,relative)));}RemoveExtras(session,manifest,changes,true);return await ApplyAsync(session,changes.OrderBy(x=>x.RelativePath.Equals(session.DatabaseFile,StringComparison.OrdinalIgnoreCase)?1:0).ToArray(),host,token);}
    static void RemoveExtras(DeviceSession session,BackupManifest manifest,List<FileChange> changes,bool full){var saved=manifest.Files.Select(x=>x.RelativePath.Replace((char)92,(char)47)).ToHashSet(StringComparer.OrdinalIgnoreCase);foreach(var directory in new[]{"Notes","Photos","iPod_Control/Artwork","iPod_Control/iTunes"}.Concat(full?new[]{"iPod_Control/Music"}:Array.Empty<string>())){var root=DeviceAccess.SafePath(session.Root,directory);if(!Directory.Exists(root))continue;foreach(var file in Directory.EnumerateFiles(root,"*",new EnumerationOptions{RecurseSubdirectories=true,AttributesToSkip=0})){var relative=Path.GetRelativePath(session.Root,file).Replace((char)92,(char)47);DeviceAccess.SafePath(session.Root,relative);if(!saved.Contains(relative)&&!Path.GetFileName(file).Contains(".itp-",StringComparison.Ordinal))changes.Add(new(relative,null));}}}
    static void Journal(string path,FileJournal journal){var pending=path+".tmp";using(var stream=new FileStream(pending,FileMode.Create,FileAccess.Write,FileShare.None,81920,FileOptions.WriteThrough)){JsonSerializer.Serialize(stream,journal);stream.Flush(true);}File.Move(pending,path,true);}
    public static Task<string> ApplyAsync(DeviceSession session,IReadOnlyList<FileChange> changes,string host,CancellationToken token=default)=>ApplyCoreAsync(session,changes,host,token,true,null);
    internal static async Task<string> ApplyCoreAsync(DeviceSession session,IReadOnlyList<FileChange> changes,string host,CancellationToken token,bool ownsLock,Func<Task>? verify)
    {
        DeviceWriteProfile.Validate(session);changes=changes.OrderBy(x=>x.Content==null&&x.SourceFile==null&&x.RelativePath.Replace((char)92,(char)47).StartsWith("iPod_Control/Music/",StringComparison.OrdinalIgnoreCase)?2:x.RelativePath.Replace((char)92,(char)47).Equals(session.DatabaseFile.Replace((char)92,(char)47),StringComparison.OrdinalIgnoreCase)?1:0).ToArray();if(changes.Select(x=>x.RelativePath.Replace((char)92,(char)47)).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=changes.Count)throw new IOException("重复变更路径。");
        foreach(var change in changes){DeviceAccess.SafePath(session.Root,change.RelativePath);var r=change.RelativePath.Replace('\\','/');if(!(r.StartsWith("iPod_Control/Music/",StringComparison.OrdinalIgnoreCase)||r.StartsWith("Notes/",StringComparison.OrdinalIgnoreCase)||r.StartsWith("Photos/",StringComparison.OrdinalIgnoreCase)||r.StartsWith("iPod_Control/Artwork/",StringComparison.OrdinalIgnoreCase)||r.StartsWith("iPod_Control/iTunes/",StringComparison.OrdinalIgnoreCase)))throw new IOException("不支持的变更目录。");if(r.Split('/').Any(x=>x.StartsWith(".itp-",StringComparison.Ordinal)))throw new IOException("保留文件名称。");}
        var db=DeviceAccess.SafePath(session.Root,session.DatabaseFile);await using var gate=ownsLock?new FileStream(DeviceAccess.SafePath(session.Root,"iPod_Control/iTunes/.itp-lock"),FileMode.CreateNew,FileAccess.ReadWrite,FileShare.None,1,FileOptions.DeleteOnClose):null;
        if(await DeviceBackup.HashAsync(db,token)!=session.Generation)throw new IOException("设备资料库已更改。");var current=await new DeviceAccess().InspectAsync(session.Root,token);DeviceWriteProfile.Validate(current);if(current.DeviceId!=session.DeviceId||!current.SignatureVerified)throw new IOException("设备标识已更改。");
        foreach(var change in changes.Where(x=>x.CheckBefore)){var target=DeviceAccess.SafePath(session.Root,change.RelativePath);var hash=File.Exists(target)?await DeviceBackup.HashAsync(target,token):null;if(hash!=change.ExpectedBeforeHash)throw new IOException("预览后的文件发生变化或目标名称已经存在："+change.RelativePath);}var backup=await DeviceBackup.CreateAsync(session,DeviceBackup.Destination(host,session.DeviceId),changes.Any(x=>x.RelativePath.Replace((char)92,(char)47).StartsWith("iPod_Control/Music/",StringComparison.OrdinalIgnoreCase)),null,token);var folder=Path.Combine(host,"file-transactions",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);var path=Path.Combine(folder,"journal.json");var receipts=new List<FileReceipt>();
        foreach(var change in changes){var target=DeviceAccess.SafePath(session.Root,change.RelativePath);receipts.Add(new(change.RelativePath,File.Exists(target)?await DeviceBackup.HashAsync(target,token):null,change.SourceFile!=null?await DeviceBackup.HashAsync(change.SourceFile,token):change.Content==null?null:Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(change.Content))));}
        var journal=new FileJournal(session.DeviceId,session.Root,backup,"Prepared",receipts);Journal(path,journal);
        try{journal=journal with{Phase="Committing"};Journal(path,journal);for(var i=0;i<changes.Count;i++){token.ThrowIfCancellationRequested();var change=changes[i];var target=DeviceAccess.SafePath(session.Root,change.RelativePath);var actual=File.Exists(target)?await DeviceBackup.HashAsync(target,token):null;if(actual!=receipts[i].BeforeHash)throw new IOException("设备文件已被其他程序更改。");if(change.Content==null&&change.SourceFile==null){if(File.Exists(target))File.Delete(target);}else{Directory.CreateDirectory(Path.GetDirectoryName(target)!);var temp=target+".itp-"+Guid.NewGuid().ToString("N");if(change.SourceFile!=null)await DeviceBackup.CopyAsync(change.SourceFile,temp,token);else using(var stream=new FileStream(temp,FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,FileOptions.WriteThrough)){stream.Write(change.Content!);stream.Flush(true);}File.Move(temp,target,true);}var after=File.Exists(target)?await DeviceBackup.HashAsync(target,token):null;if(after!=receipts[i].AfterHash)throw new IOException("提交复读失败。");}if(changes.Any(x=>x.RelativePath.Replace((char)92,(char)47).Equals(session.DatabaseFile.Replace((char)92,(char)47),StringComparison.OrdinalIgnoreCase))){var committed=await File.ReadAllBytesAsync(db,CancellationToken.None);if(!DeviceChecksum.VerifyHash58(committed,session.SigningIdentity))throw new IOException("提交数据库签名无效。");var reader=new ITunesDbReader();reader.Read(committed,session.Root);reader.ReadPlaylists(committed);}if(verify!=null)await verify();Journal(path,journal with{Phase="Complete"});return backup;}
        catch{try{await RecoverCoreAsync(path,CancellationToken.None);}catch{Journal(path,journal with{Phase="RecoveryRequired"});}throw;}
    }
    public static async Task RecoverAsync(string path,CancellationToken token=default)
    {
        var journal=JsonSerializer.Deserialize<FileJournal>(await File.ReadAllTextAsync(path,token))??throw new IOException("日志损坏。");await using var gate=new FileStream(DeviceAccess.SafePath(journal.Root,"iPod_Control/iTunes/.itp-lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None,1,FileOptions.DeleteOnClose);await RecoverCoreAsync(path,token);
    }
    internal static async Task RecoverCoreAsync(string path,CancellationToken token=default)
    {
        var journal=JsonSerializer.Deserialize<FileJournal>(await File.ReadAllTextAsync(path,token))??throw new IOException("日志损坏。");var backup=await DeviceBackup.VerifyAsync(journal.Backup,token);var session=await new DeviceAccess().InspectAsync(journal.Root,token);if(session.DeviceId!=journal.DeviceId||backup.DeviceId!=journal.DeviceId)throw new IOException("恢复设备不匹配。");
        // Validate all files before restoring any, avoiding overwrite of unrelated external edits.
        foreach(var receipt in journal.Files){var target=DeviceAccess.SafePath(journal.Root,receipt.RelativePath);var actual=File.Exists(target)?await DeviceBackup.HashAsync(target,token):null;if(actual!=receipt.BeforeHash&&actual!=receipt.AfterHash)throw new IOException("恢复被阻止：检测到外部更改。");}
        foreach(var receipt in journal.Files.OrderBy(x=>x.RelativePath.Replace((char)92,(char)47).Equals(session.DatabaseFile.Replace((char)92,(char)47),StringComparison.OrdinalIgnoreCase)?1:0)){var target=DeviceAccess.SafePath(journal.Root,receipt.RelativePath);if(receipt.BeforeHash==null){if(File.Exists(target))File.Delete(target);}else{var source=DeviceAccess.SafePath(journal.Backup,receipt.RelativePath);if(await DeviceBackup.HashAsync(source,token)!=receipt.BeforeHash)throw new IOException("恢复副本不匹配。");Directory.CreateDirectory(Path.GetDirectoryName(target)!);var temp=target+".itp-restore";if(File.Exists(temp))throw new IOException("恢复临时文件已存在。");await DeviceBackup.CopyAsync(source,temp,token);File.Move(temp,target,true);}}
        Journal(path,journal with{Phase="RolledBack"});
    }
    public static async Task<string> RestoreMetadataAsync(DeviceSession session,string backupFolder,string host,CancellationToken token=default){var manifest=await DeviceBackup.VerifyAsync(backupFolder,token);if(manifest.DeviceId!=session.DeviceId)throw new IOException("备份属于其他设备。");var changes=new List<FileChange>();foreach(var entry in manifest.Files){if(entry.RelativePath.Replace('\\','/').StartsWith("iPod_Control/Music/",StringComparison.OrdinalIgnoreCase))continue;if(entry.RelativePath.Replace('\\','/').StartsWith("iPod_Control/Device/",StringComparison.OrdinalIgnoreCase))continue;changes.Add(new(entry.RelativePath,await File.ReadAllBytesAsync(DeviceAccess.SafePath(backupFolder,entry.RelativePath),token)));}var db=changes.FirstOrDefault(x=>x.RelativePath.Replace((char)92,(char)47).Equals(session.DatabaseFile.Replace((char)92,(char)47),StringComparison.OrdinalIgnoreCase));if(db?.Content==null||!DeviceChecksum.VerifyHash58(db.Content,session.SigningIdentity))throw new IOException("备份数据库签名不匹配。");foreach(var track in new ITunesDbReader().Read(db.Content,session.Root))if(!File.Exists(track.Path)&&!session.Tracks.Any(x=>x.Path.Equals(track.Path,StringComparison.OrdinalIgnoreCase)&&!File.Exists(x.Path)))throw new IOException("旧数据库需要的媒体已丢失，请先恢复完整备份。");RemoveExtras(session,manifest,changes,false);return await ApplyAsync(session,changes.OrderBy(x=>x.RelativePath.Replace((char)92,(char)47).Equals(session.DatabaseFile.Replace((char)92,(char)47),StringComparison.OrdinalIgnoreCase)?1:0).ToArray(),host,token);}
}
