using System.Buffers.Binary;
using iTunesPod.Core;
using static iTunesPod.Infrastructure.ITunesDbWriter;
namespace iTunesPod.Infrastructure;
public sealed record ArtworkLink(int ImageId,int SourceBytes);
public static class DeviceDatabaseEdits
{
    public static IReadOnlyDictionary<uint,int> ArtworkIds(byte[] database){var map=new Dictionary<uint,int>();foreach(var section in Children(database,U(database,4)).Where(x=>U(x,12)==1)){var at=U(section,4);foreach(var track in Children(section,at+U(section,at+4)))if(U(track,4)>=356)map.Add((uint)U(track,16),track[164]!=1?0:U(track,352));}return map;}
    public static IReadOnlyDictionary<uint,ulong> PersistentIds(byte[] database){var map=new Dictionary<uint,ulong>();foreach(var section in Children(database,U(database,4)).Where(x=>U(x,12)==1)){var at=U(section,4);foreach(var track in Children(section,at+U(section,at+4)))map.Add((uint)U(track,16),BinaryPrimitives.ReadUInt64LittleEndian(track.AsSpan(112)));}return map;}
    public static byte[] Apply(byte[] original,ReadOnlySpan<byte> identity,IReadOnlyDictionary<uint,Track>? updates=null,IReadOnlyDictionary<uint,ArtworkLink>? covers=null,IReadOnlyList<Playlist>? playlists=null,IReadOnlySet<uint>? deleteTracks=null)
    {
        if(!DeviceChecksum.VerifyHash58(original,identity))throw new IOException("数据库签名不匹配。");var reader=new ITunesDbReader();var old=reader.Read(original,Path.GetTempPath());var updated=old.Where(x=>deleteTracks?.Contains(uint.Parse(x.Id[7..]))!=true).Select(x=>updates?.GetValueOrDefault(uint.Parse(x.Id[7..]))??x).ToArray();var sections=Children(original,U(original,4));
        for(var s=0;s<sections.Count;s++){var section=sections[s];var type=U(section,12);if(type is not (1 or 2 or 3))throw new IOException("数据库含尚未支持的派生索引分区。");var h=U(section,4);var lh=U(section,h+4);var records=Children(section,h+lh);if(type==1){var changed=new List<byte[]>();foreach(var raw in records){var id=(uint)U(raw,16);if(deleteTracks?.Contains(id)==true)continue;var header=raw.AsSpan(0,U(raw,4)).ToArray();var children=Children(raw,header.Length);if(updates?.TryGetValue(id,out var t)==true){var strings=new Dictionary<int,string>{{1,t.Title},{3,t.Album},{4,t.Artist},{5,t.Genre},{12,t.Composer},{22,t.AlbumArtist},{23,t.Artist},{27,t.Title},{28,t.Album},{29,t.AlbumArtist}};foreach(var pair in strings){var at=children.FindIndex(x=>Magic(x)=="mhod"&&U(x,12)==pair.Key);if(at>=0)children[at]=StringRecord(pair.Key,pair.Value);else if(pair.Key<=22)children.Add(StringRecord(pair.Key,pair.Value));}if(header.Length>=212)Put(header,208,(int)t.MediaType);header[30]=t.Compilation?(byte)1:(byte)0;header[31]=(byte)Math.Min(100,t.Rating*20);Put(header,44,(int)t.Number);Put(header,52,(int)t.Year);Put(header,92,(int)t.Disc);Put(header,12,children.Count);}if(covers?.TryGetValue(id,out var cover)==true){if(header.Length<356)throw new IOException("曲目头不支持封面引用。");Put(header,352,cover.ImageId);header[164]=cover.ImageId==0?(byte)2:(byte)1;BinaryPrimitives.WriteUInt16LittleEndian(header.AsSpan(124),cover.ImageId==0?(ushort)0:(ushort)1);Put(header,128,cover.SourceBytes);}changed.Add(Join(header,children));}records=changed;}
            else{var result=new List<byte[]>();var seen=new HashSet<string>();foreach(var raw in records){var id="device-playlist:"+BinaryPrimitives.ReadUInt64LittleEndian(raw.AsSpan(28)).ToString("X16");seen.Add(id);var requested=playlists?.FirstOrDefault(x=>x.Id==id);var system=raw[20]!=0;if(playlists!=null&&requested==null&&!system)continue;var previous=reader.ReadPlaylists(original).Single(x=>x.Id==id);if(!system&&deleteTracks==null&&(requested==null||(requested.Name==previous.Name&&requested.TrackIds.SequenceEqual(previous.TrackIds)&&SameRules(requested.SmartDefinition,previous.SmartDefinition)))){result.Add(raw);continue;}if(playlists!=null&&requested==null&&!system)continue;var header=raw.AsSpan(0,U(raw,4)).ToArray();var children=Children(raw,header.Length);var metadata=children.Where(x=>Magic(x)=="mhod").ToList();var entries=children.Where(x=>Magic(x)=="mhip").ToList();if(children.Count!=metadata.Count+entries.Count)throw new IOException("列表含未知子记录。");var smart=metadata.Any(x=>U(x,12) is 50 or 51);if(smart&&requested!=null&&requested.SmartDefinition==null){var existing=reader.ReadPlaylists(original).Single(x=>x.Id==id);if(existing.Name!=requested.Name||!existing.TrackIds.SequenceEqual(requested.TrackIds))throw new IOException("未知智能列表规则保持原样，请先复制为普通列表。");}
                if(requested!=null&&(!smart||requested.SmartDefinition!=null)){if(requested.SmartDefinition!=null){metadata.RemoveAll(x=>U(x,12) is 50 or 51);metadata.AddRange(SmartPlaylistBinary.Encode(requested.SmartDefinition));}var nameAt=metadata.FindIndex(x=>U(x,12)==1);if(nameAt>=0)metadata[nameAt]=StringRecord(1,requested.Name);else metadata.Insert(0,StringRecord(1,requested.Name));if(!requested.TrackIds.SequenceEqual(previous.TrackIds)){var byTrack=entries.GroupBy(x=>U(x,24)).ToDictionary(x=>x.Key,x=>new Queue<byte[]>(x));entries=[];for(var i=0;i<requested.TrackIds.Count;i++){var track=int.Parse(requested.TrackIds[i][7..]);if(!updated.Any(x=>x.Id=="device:"+track))throw new IOException("列表引用未知曲目。");var item=byTrack.TryGetValue(track,out var queue)&&queue.Count>0?queue.Dequeue():Item((uint)track,i);var itemChildren=Children(item,U(item,4));foreach(var position in itemChildren.Where(x=>Magic(x)=="mhod"&&U(x,12)==100))Put(position,U(position,4),i);entries.Add(Join(item.AsSpan(0,U(item,4)).ToArray(),itemChildren));}}}
                entries.RemoveAll(x=>deleteTracks?.Contains((uint)U(x,24))==true);if(system){var map=updated.ToDictionary(x=>int.Parse(x.Id[7..]));var inMasterOrder=entries.Select(x=>map[U(x,24)]).ToArray();for(var m=0;m<metadata.Count;m++)if(U(metadata[m],12) is 52 or 53)metadata[m]=BuildIndex(U(metadata[m],12),U(metadata[m],24),inMasterOrder);}
                Put(header,12,metadata.Count);Put(header,16,entries.Count);result.Add(Join(header,metadata.Concat(entries)));}
                if(playlists!=null)foreach(var list in playlists.Where(x=>!seen.Contains(x.Id)&&!x.IsSystem)){if(list.IsSmart&&list.SmartDefinition==null)throw new IOException("缺少智能列表规则。");var header=Header("mhyp",184);BinaryPrimitives.WriteUInt64LittleEndian(header.AsSpan(28),Convert.ToUInt64(list.Id.Replace("device-playlist:",""),16));var metadata=new List<byte[]>{StringRecord(1,list.Name)};if(list.SmartDefinition!=null)metadata.AddRange(SmartPlaylistBinary.Encode(list.SmartDefinition));Put(header,12,metadata.Count);Put(header,16,list.TrackIds.Count);var entries=list.TrackIds.Select((id,i)=>Item(uint.Parse(id[7..]),i)).ToArray();if(list.TrackIds.Any(id=>!updated.Any(t=>t.Id==id)))throw new IOException("列表引用未知曲目。");result.Add(Join(header,metadata.Concat(entries)));}records=result;}
            sections[s]=Join(section.AsSpan(0,h).ToArray(),[Join(section.AsSpan(h,lh).ToArray(),records,true)]);
        }
        var output=DeviceChecksum.SignHash58(Join(original.AsSpan(0,U(original,4)).ToArray(),sections),identity);if(reader.Read(output,Path.GetTempPath()).Count!=updated.Length)throw new IOException("编辑后的数据库复读失败。");reader.ReadPlaylists(output);return output;
    }
    public static byte[] RefreshSmart(byte[] database,ReadOnlySpan<byte> identity){var reader=new ITunesDbReader();var tracks=reader.Read(database,Path.GetTempPath());var lists=reader.ReadPlaylists(database);var updated=lists.Select(x=>x.IsSystem||x.SmartDefinition==null?x:x with{TrackIds=SmartPlaylists.Evaluate(x.SmartDefinition,tracks).Select(t=>t.Id).ToArray()}).ToArray();if(lists.Zip(updated).All(x=>x.First.TrackIds.SequenceEqual(x.Second.TrackIds)))return database;return Apply(database,identity,playlists:updated);}
    static bool SameRules(SmartDefinition? a,SmartDefinition? b)=>a==null||b==null?a==b:a.MatchAll==b.MatchAll&&a.Limit==b.Limit&&a.LimitUnit==b.LimitUnit&&a.Sort==b.Sort&&a.Rules.SequenceEqual(b.Rules);
    static byte[] BuildIndex(int kind,int sort,IReadOnlyList<Track> tracks)=>ITunesDbWriter.Index(kind,sort,tracks);
}
