using System.Text.Json;
using iTunesPod.Core;
namespace iTunesPod.Infrastructure;
public sealed record PreparedMedia(string SourceId,string SourcePath,string SourceHash,DeviceTrackWrite Write){public string PayloadHash{get;init;}="";}
public sealed record PreparedSync(DeviceSession Device,string DatabasePath,string DatabaseHash,IReadOnlyList<PreparedMedia> Media,string WorkDirectory,long RequiredBytes){public IReadOnlyDictionary<string,string> MetadataHashes{get;init;}=new Dictionary<string,string>();public string PlanHash{get;init;}="";public IReadOnlyDictionary<uint,string> ExistingHashes{get;init;}=new Dictionary<uint,string>();public IReadOnlyDictionary<string,uint> ExistingMatches{get;init;}=new Dictionary<string,uint>();public IReadOnlyList<PreparedAsset> Assets{get;init;}=[];public IReadOnlyList<PreparedDeletion> Deletes{get;init;}=[];public IReadOnlyList<PreparedSource> Sources{get;init;}=[];}
public sealed record PreparedAsset(string RelativePath,string SourcePath,string Hash,string? BeforeHash=null);
public sealed record PreparedDeletion(string RelativePath,string BeforeHash);
public sealed record PreparedSource(string Id,string Path,string Hash);
public sealed record SyncJournal(string DeviceId,string OriginalGeneration,string NewGeneration,string DatabaseRelativePath,string BackupDirectory,IReadOnlyList<string> NewFiles,string Phase){public IReadOnlyDictionary<string,string> NewHashes{get;init;}=new Dictionary<string,string>();}
public sealed class DeviceSync(string hostDirectory)
{
    static string Digest(PreparedSync plan)=>Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(JsonSerializer.Serialize(new{plan.Device.DeviceId,plan.Device.Root,plan.Device.MountEpoch,plan.Device.Generation,plan.DatabaseHash,plan.RequiredBytes,plan.ExistingMatches,plan.ExistingHashes,plan.MetadataHashes,plan.Sources,plan.Deletes,plan.Assets,Media=plan.Media.Select(x=>new{x.SourceId,x.SourcePath,x.SourceHash,x.PayloadHash,x.Write.Id,x.Write.RelativePath,x.Write.Track.Bytes})}))));
    public static PreparedSync Seal(PreparedSync plan){var sealedPlan=plan with{PlanHash=Digest(plan)};File.WriteAllText(Path.Combine(plan.WorkDirectory,"preview.json"),JsonSerializer.Serialize(sealedPlan,new JsonSerializerOptions{WriteIndented=true}));return sealedPlan;}
    public async Task RecoverAsync(DeviceSession device,string journalPath,CancellationToken token=default){var journal=JsonSerializer.Deserialize<SyncJournal>(await File.ReadAllTextAsync(journalPath,token))??throw new IOException("日志损坏。");if(journal.DeviceId!=device.DeviceId)throw new IOException("恢复日志属于其他设备。");await DeviceBackup.VerifyAsync(journal.BackupDirectory,token);await using var gate=new FileStream(DeviceAccess.SafePath(device.Root,"iPod_Control/iTunes/.itp-lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None,1,FileOptions.DeleteOnClose);var db=DeviceAccess.SafePath(device.Root,journal.DatabaseRelativePath);var actual=await DeviceBackup.HashAsync(db,token);if(actual!=journal.OriginalGeneration&&actual!=journal.NewGeneration)throw new IOException("数据库有外部更改，不能自动恢复。");var txRoot=Path.Combine(hostDirectory,"file-transactions");if(Directory.Exists(txRoot))foreach(var path in Directory.EnumerateFiles(txRoot,"journal.json",SearchOption.AllDirectories)){var tx=JsonSerializer.Deserialize<FileJournal>(await File.ReadAllTextAsync(path,token));if(tx?.DeviceId==device.DeviceId&&tx.Phase!="RolledBack"&&tx.Files.Any(x=>x.RelativePath.Replace((char)92,(char)47).Equals(journal.DatabaseRelativePath,StringComparison.OrdinalIgnoreCase)&&x.BeforeHash==journal.OriginalGeneration&&x.AfterHash==journal.NewGeneration)){if(!Path.GetFullPath(tx.Root).Equals(Path.GetFullPath(device.Root),StringComparison.OrdinalIgnoreCase))throw new IOException("挂载路径改变，请先重新定位恢复日志中的设备路径。");await DeviceFileTransaction.RecoverCoreAsync(path,token);break;}}if(await DeviceBackup.HashAsync(db,token)!=journal.OriginalGeneration)throw new IOException("找不到完整的提交日志，恢复被阻止。");foreach(var file in journal.NewFiles){var target=DeviceAccess.SafePath(device.Root,file);if(File.Exists(target)&&(!journal.NewHashes.TryGetValue(file,out var hash)||await DeviceBackup.HashAsync(target,token)!=hash))throw new IOException("新增文件被外部更改，不能清理。");}foreach(var file in journal.NewFiles){var target=DeviceAccess.SafePath(device.Root,file);if(File.Exists(target))File.Delete(target);}Persist(journalPath,journal with{Phase="RolledBack"});}
    static void Persist(string path,SyncJournal journal){var temp=path+".tmp";using(var f=new FileStream(temp,FileMode.Create,FileAccess.Write,FileShare.None,81920,FileOptions.WriteThrough)){JsonSerializer.Serialize(f,journal);f.Flush(true);}File.Move(temp,path,true);}
    public async Task<PreparedSync> PrepareAsync(DeviceSession device,IEnumerable<Track> selected,IProgress<string>? progress=null,CancellationToken token=default)
    {
        DeviceWriteProfile.Validate(device);
        selected=selected.ToArray();var sourceDb=DeviceAccess.SafePath(device.Root,device.DatabaseFile);if(await DeviceBackup.HashAsync(sourceDb,token)!=device.Generation)throw new IOException("设备数据库已被更改，请刷新。");
        var folder=Path.Combine(hostDirectory,"transactions",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);var media=new List<PreparedMedia>();var next=device.Tracks.Select(x=>uint.Parse(x.Id[7..])).DefaultIfEmpty().Max();var settings=new LibraryStore(hostDirectory);var tools=new MediaTools(Path.Combine(hostDirectory,"transcode"),settings.GetPreference("ffmpeg","ffmpeg"),settings.GetPreference("ffprobe","ffprobe"));var existing=await DeviceMediaIndex.BuildAsync(device,hostDirectory,progress,token);var sources=new List<PreparedSource>();var deletes=new List<PreparedDeletion>();var matches=new Dictionary<string,uint>();var sourceLinks=DeviceMediaIndex.LoadLinks(device.DeviceId,hostDirectory);
        foreach(var track in selected.DistinctBy(x=>x.Id)){token.ThrowIfCancellationRequested();progress?.Report("检查 / 转换："+track.Title);var sourceHash=await DeviceBackup.HashAsync(track.Path,token);if(track.Hash.Length==64&&!track.Hash.Equals(sourceHash,StringComparison.OrdinalIgnoreCase))throw new IOException("来源内容已更改："+track.Title);sources.Add(new(track.Id,track.Path,sourceHash));var matching=existing.Where(x=>x.Hash==sourceHash||sourceLinks.Any(link=>link.SourceHash==sourceHash&&link.DeviceTrackId==x.Id&&link.PayloadHash==x.Hash)).ToArray();if(matching.Length>1)throw new IOException("设备有多个相同内容的曲目，请先处理重复记录："+track.Title);if(matching.Length==1){matches.Add(track.Id,matching[0].Id);continue;}var prepared=await tools.PrepareAsync(track,token);if(int.TryParse(settings.GetPreference("cache-limit-gb","10"),out var limit)&&Directory.Exists(Path.Combine(hostDirectory,"transcode"))&&Directory.EnumerateFiles(Path.Combine(hostDirectory,"transcode")).Sum(x=>new FileInfo(x).Length)>limit*1024L*1024*1024)throw new IOException("转码缓存已超过设置上限，请在设置中清理缓存或增大上限。");var fileName=Guid.NewGuid().ToString("N")+Path.GetExtension(prepared.Path).ToLowerInvariant();var relative="iPod_Control/Music/F00/"+fileName;var id=checked(++next);media.Add(new(track.Id,track.Path,sourceHash,new(id,prepared,relative)){PayloadHash=await DeviceBackup.HashAsync(prepared.Path,token)});}
        var original=await File.ReadAllBytesAsync(sourceDb,token);var countsPath=DeviceAccess.SafePath(device.Root,"iPod_Control/iTunes/Play Counts");if(File.Exists(countsPath)){var counts=await File.ReadAllBytesAsync(countsPath,token);original=DeviceStatistics.Fold(original,counts,device.SigningIdentity);deletes.Add(new("iPod_Control/iTunes/Play Counts",Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(counts))));}var result=new ITunesDbWriter().Build(original,media.Select(x=>x.Write).ToArray(),device.SigningIdentity,DeviceClock.CurrentOffset(device.Root,original));
        var changes=new Dictionary<uint,Track>();foreach(var match in matches){var pc=selected.First(x=>x.Id==match.Key);var old=device.Tracks.Single(x=>x.Id=="device:"+match.Value);if(pc.Title!=old.Title||pc.Artist!=old.Artist||pc.Album!=old.Album||pc.AlbumArtist!=old.AlbumArtist||pc.Genre!=old.Genre||pc.Number!=old.Number||pc.Disc!=old.Disc||pc.Year!=old.Year||pc.Composer!=old.Composer||pc.Compilation!=old.Compilation||pc.MediaType!=old.MediaType)changes.Add(match.Value,pc with{Id=old.Id,Rating=old.Rating});}if(changes.Count>0)result=DeviceDatabaseEdits.Apply(result,device.SigningIdentity,updates:changes);
        result=DeviceDatabaseEdits.RefreshSmart(result,device.SigningIdentity);if(media.Any(x=>x.Write.Track.IsPodcast))result=PodcastDatabase.GroupEpisodes(result,device.SigningIdentity);var database=Path.Combine(folder,"iTunesDB");await File.WriteAllBytesAsync(database,result,token);var required=checked(media.Sum(x=>x.Write.Track.Bytes)+result.Length+Math.Max(64L*1024*1024,media.Sum(x=>x.Write.Track.Bytes)/20));if(required>new DriveInfo(Path.GetPathRoot(device.Root)!).AvailableFreeSpace)throw new IOException("设备剩余容量不足。");
        var plan=new PreparedSync(device,database,await DeviceBackup.HashAsync(database,token),media,folder,required){MetadataHashes=await DeviceBackup.MetadataHashesAsync(device.Root,token),ExistingMatches=matches,ExistingHashes=existing.Where(x=>matches.Values.Contains(x.Id)).ToDictionary(x=>x.Id,x=>x.Hash),Sources=sources,Deletes=deletes};await File.WriteAllTextAsync(Path.Combine(folder,"preview.json"),JsonSerializer.Serialize(new{device.DeviceId,device.Generation,required,DatabaseHash=plan.DatabaseHash,Media=media.Select(x=>new{x.SourceId,x.Write.Id,x.Write.Track.Title,x.Write.RelativePath,x.Write.Track.Bytes}),ExistingMatches=matches},new JsonSerializerOptions{WriteIndented=true}),token);if(plan.MetadataHashes.GetValueOrDefault(device.DatabaseFile)!=device.Generation)throw new IOException("准备期间设备数据库发生变化。");return Seal(plan);
    }
    public async Task<string> CommitAsync(PreparedSync plan,IProgress<string>? progress=null,CancellationToken token=default)
    {
        DeviceWriteProfile.Validate(plan.Device);if(plan.PlanHash!=Digest(plan))throw new IOException("同步计划已变化，请重新预览。");var device=plan.Device;var db=DeviceAccess.SafePath(device.Root,device.DatabaseFile);var lockPath=DeviceAccess.SafePath(device.Root,"iPod_Control/iTunes/.itp-lock");
        await using var writeLock=new FileStream(lockPath,FileMode.CreateNew,FileAccess.ReadWrite,FileShare.None,1,FileOptions.DeleteOnClose|FileOptions.WriteThrough);
        if(await DeviceBackup.HashAsync(db,token)!=device.Generation)throw new IOException("E_EXTERNAL_CHANGE：设备数据库已更改。");
        var current=await new DeviceAccess().InspectAsync(device.Root,token);DeviceWriteProfile.Validate(current);if(current.DeviceId!=device.DeviceId||current.MountEpoch!=device.MountEpoch||!current.SignatureVerified)throw new IOException("E_DEVICE_CHANGED：设备标识或校验已更改。");
        if(await DeviceBackup.HashAsync(plan.DatabasePath,token)!=plan.DatabaseHash)throw new IOException("预览数据库已更改。");
        var metadata=await DeviceBackup.MetadataHashesAsync(device.Root,token);if(metadata.Count!=plan.MetadataHashes.Count||plan.MetadataHashes.Any(x=>metadata.GetValueOrDefault(x.Key)!=x.Value))throw new IOException("设备元数据在预览后发生变化，请重新预览。");foreach(var asset in plan.Assets){var target=DeviceAccess.SafePath(device.Root,asset.RelativePath);var actual=File.Exists(target)?await DeviceBackup.HashAsync(target,token):null;if(actual!=asset.BeforeHash)throw new IOException("E_EXTERNAL_CHANGE：封面资源发生更改，请重新预览。");}
        foreach(var entry in plan.Sources)if(await DeviceBackup.HashAsync(entry.Path,token)!=entry.Hash)throw new IOException("来源文件已更改："+entry.Id);
        foreach(var match in plan.ExistingMatches){var existingTrack=current.Tracks.Single(x=>x.Id=="device:"+match.Value);if(!plan.ExistingHashes.TryGetValue(match.Value,out var expected)||await DeviceBackup.HashAsync(existingTrack.Path,token)!=expected)throw new IOException("已匹配的设备媒体发生变化，请重新生成预览。");}foreach(var deletion in plan.Deletes)if(await DeviceBackup.HashAsync(DeviceAccess.SafePath(device.Root,deletion.RelativePath),token)!=deletion.BeforeHash)throw new IOException("设备播放统计已变化，请重新预览。");if(plan.RequiredBytes>current.FreeBytes)throw new IOException("设备容量已不足。");progress?.Report("备份全部元数据与封面");var backup=await DeviceBackup.CreateAsync(device,DeviceBackup.Destination(hostDirectory,device.DeviceId),false,progress,token);
        var journalPath=Path.Combine(plan.WorkDirectory,"journal.json");var journal=new SyncJournal(device.DeviceId,device.Generation,plan.DatabaseHash,device.DatabaseFile,backup,Array.Empty<string>(),"Staging"){NewHashes=plan.Media.ToDictionary(x=>x.Write.RelativePath,x=>x.PayloadHash)};Persist(journalPath,journal);var copied=new List<string>();var pending=db+".itp-"+Guid.NewGuid().ToString("N");
        var committed=false;try{
            foreach(var entry in plan.Media){token.ThrowIfCancellationRequested();var target=DeviceAccess.SafePath(device.Root,entry.Write.RelativePath);progress?.Report("写入媒体："+entry.Write.Track.Title);Directory.CreateDirectory(Path.GetDirectoryName(target)!);await using(var input=File.OpenRead(entry.Write.Track.Path))await using(var output=new FileStream(target,FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,FileOptions.Asynchronous|FileOptions.WriteThrough)){copied.Add(target);journal=journal with{NewFiles=copied.Select(x=>Path.GetRelativePath(device.Root,x).Replace((char)92,(char)47)).ToArray()};Persist(journalPath,journal);await input.CopyToAsync(output,token);await output.FlushAsync(token);output.Flush(true);}if(await DeviceBackup.HashAsync(target,token)!=entry.PayloadHash)throw new IOException("媒体复读校验失败。");}
            await DeviceBackup.CopyAsync(plan.DatabasePath,pending,token);if(await DeviceBackup.HashAsync(pending,token)!=plan.DatabaseHash)throw new IOException("临时数据库校验失败。");
            // Revalidate every snapshotted metadata file. No parallel iTunes/device update may be overwritten.
            var manifest=await DeviceBackup.VerifyAsync(backup,token);foreach(var file in manifest.Files)if(await DeviceBackup.HashAsync(DeviceAccess.SafePath(device.Root,file.RelativePath),token)!=file.Hash)throw new IOException("E_EXTERNAL_CHANGE：设备元数据被其他程序更改。");
            journal=journal with{Phase="Committing"};Persist(journalPath,journal);
            foreach(var asset in plan.Assets)if(await DeviceBackup.HashAsync(asset.SourcePath,token)!=asset.Hash)throw new IOException("预览资源已更改。");
            var changes=plan.Assets.Select(x=>new FileChange(x.RelativePath,null,x.SourcePath)).Concat(plan.Deletes.Select(x=>new FileChange(x.RelativePath,null))).Append(new FileChange(device.DatabaseFile,null,plan.DatabasePath)).ToArray();
            await DeviceFileTransaction.ApplyCoreAsync(device,changes,hostDirectory,token,false,async()=>{if(await DeviceBackup.HashAsync(db,CancellationToken.None)!=plan.DatabaseHash)throw new IOException("提交后数据库校验失败。");var bytes=await File.ReadAllBytesAsync(db,CancellationToken.None);if(!DeviceChecksum.VerifyHash58(bytes,device.SigningIdentity))throw new IOException("提交后的 HASH58 校验失败。");foreach(var asset in plan.Assets.Where(x=>x.RelativePath.EndsWith("ArtworkDB",StringComparison.OrdinalIgnoreCase)))new NativeImageDatabase(await File.ReadAllBytesAsync(DeviceAccess.SafePath(device.Root,asset.RelativePath))).VerifyFiles(device.Root,false);var tracks=new ITunesDbReader().Read(bytes,device.Root);if(tracks.Count!=device.Tracks.Count+plan.Media.Count)throw new IOException("提交后歌曲数不一致。");foreach(var entry in plan.Media)if(!tracks.Any(x=>x.Id=="device:"+entry.Write.Id&&File.Exists(x.Path)))throw new IOException("提交后的媒体引用缺失。");});
            committed=true;
            if(File.Exists(pending))File.Delete(pending);
            var oldLinks=DeviceMediaIndex.LoadLinks(device.DeviceId,hostDirectory);DeviceMediaIndex.SaveLinks(device.DeviceId,hostDirectory,plan.Media.Select(x=>new SourceDeviceLink(x.SourceId,x.SourceHash,x.PayloadHash,x.Write.Id)).Concat(plan.ExistingMatches.Select(x=>new SourceDeviceLink(x.Key,plan.Sources.Single(s=>s.Id==x.Key).Hash,DeviceBackup.HashAsync(current.Tracks.Single(t=>t.Id=="device:"+x.Value).Path).GetAwaiter().GetResult(),x.Value))).Concat(oldLinks));journal=journal with{Phase="Complete"};Persist(journalPath,journal);progress?.Report("同步完成，备份与日志已保留");return backup;
        }catch{
            if(committed){try{Persist(journalPath,journal with{Phase="RecoveryRequired"});}catch(IOException){}throw new IOException("设备提交已完成，但电脑端收尾失败。请保留设备，在传输任务中检查恢复日志。");}
            string actual;try{actual=await DeviceBackup.HashAsync(db,CancellationToken.None);}catch(IOException){Persist(journalPath,journal with{Phase="RecoveryRequired"});throw;}
            if(actual==device.Generation){foreach(var path in copied)if(File.Exists(path)){var relative=Path.GetRelativePath(device.Root,path).Replace((char)92,(char)47);if(!journal.NewHashes.TryGetValue(relative,out var hash)||await DeviceBackup.HashAsync(path,CancellationToken.None)!=hash){Persist(journalPath,journal with{Phase="RecoveryRequired"});throw new IOException("新增媒体与预期不一致，已保留文件和恢复日志。");}File.Delete(path);}if(File.Exists(pending))File.Delete(pending);Persist(journalPath,journal with{Phase="RolledBack"});}else Persist(journalPath,journal with{Phase="RecoveryRequired"});throw;
        }
    }
}
