using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using iTunesPod.Core;
namespace iTunesPod.Infrastructure;

public sealed record DeviceTrackWrite(uint Id, Track Track, string RelativePath);
/// <summary>Edits an existing uncompressed HASH58 database, retaining opaque records and headers.</summary>
public sealed class ITunesDbWriter
{
    internal static int U(byte[] b,int p){if(p<0||p>b.Length-4)throw new InvalidDataException("二进制字段越界。");var value=BinaryPrimitives.ReadUInt32LittleEndian(b.AsSpan(p,4));if(value>int.MaxValue)throw new InvalidDataException("二进制长度或计数超限。");return (int)value;}
    internal static void Put(byte[] b,int p,int n)=>BinaryPrimitives.WriteUInt32LittleEndian(b.AsSpan(p,4),checked((uint)n));
    internal static byte[] Header(string magic,int size){var h=new byte[size];Encoding.ASCII.GetBytes(magic).CopyTo(h,0);Put(h,4,size);Put(h,8,size);return h;}
    internal static byte[] Join(byte[] header,IEnumerable<byte[]> children,bool count=false){var parts=children.ToArray();var result=new byte[checked(header.Length+parts.Sum(x=>x.Length))];header.CopyTo(result,0);var p=header.Length;foreach(var part in parts){part.CopyTo(result,p);p+=part.Length;}Put(result,8,count?parts.Length:result.Length);return result;}
    internal static List<byte[]> Children(byte[] b,int start){var result=new List<byte[]>();while(start<b.Length){if(start>b.Length-12)throw new InvalidDataException("记录被截断。");var size=U(b,start+8);var h=U(b,start+4);if(size<h||h<12||size>b.Length-start)throw new InvalidDataException("记录越界。");result.Add(b.AsSpan(start,size).ToArray());start+=size;}return result;}
    internal static string Magic(byte[] b)=>Encoding.ASCII.GetString(b,0,4);
    internal static byte[] StringRecord(int type,string value){var text=Encoding.Unicode.GetBytes(value);if(text.Length>8192)throw new InvalidDataException("设备文字字段超过 8192 字节。");var h=Header("mhod",24);Put(h,12,type);var body=new byte[16+text.Length];Put(body,0,1);Put(body,4,text.Length);text.CopyTo(body,16);return Join(h,[body]);}
    static byte[] TrackRecord(DeviceTrackWrite write,int timeOffset){var t=write.Track;var h=Header("mhit",624);Put(h,16,checked((int)write.Id));Put(h,20,1);var extension=Path.GetExtension(write.RelativePath).ToLowerInvariant();Put(h,24,extension switch{".mp3"=>0x4d503320,".wav"=>0x57415620,".mp4"=>0x4d503420,".m4v"=>0x4d345620,_=>0x4d344120});h[29]=Path.GetExtension(write.RelativePath).Equals(".mp3",StringComparison.OrdinalIgnoreCase)?(byte)1:(byte)0;h[31]=(byte)Math.Min(100,t.Rating*20);BinaryPrimitives.WriteUInt32LittleEndian(h.AsSpan(36),checked((uint)t.Bytes));Put(h,40,checked((int)(t.Seconds*1000)));Put(h,44,(int)t.Number);Put(h,52,(int)t.Year);Put(h,56,(int)t.Bitrate);BinaryPrimitives.WriteUInt32LittleEndian(h.AsSpan(60),t.SampleRate<<16);Put(h,92,(int)t.Disc);RandomNumberGenerator.Fill(h.AsSpan(112,8));h.AsSpan(112,8).CopyTo(h.AsSpan(168,8));BinaryPrimitives.WriteUInt16LittleEndian(h.AsSpan(126),t.IsVideo?(ushort)0x80:extension==".wav"?(ushort)0:(ushort)0xffff);BitConverter.GetBytes((float)t.SampleRate).CopyTo(h,136);h[164]=2;h[178]=2;h[30]=t.Compilation?(byte)1:(byte)0;BinaryPrimitives.WriteUInt16LittleEndian(h.AsSpan(144),extension==".mp3"?(ushort)12:(ushort)51);BinaryPrimitives.WriteUInt32LittleEndian(h.AsSpan(104),checked((uint)(DateTimeOffset.UtcNow.ToUnixTimeSeconds()+2082844800+timeOffset)));h[166]=t.IsPodcast?(byte)1:(byte)0;h[177]=t.IsVideo?(byte)1:(byte)0;Put(h,208,(int)t.MediaType);Put(h,80,(int)t.PlayCount);Put(h,84,(int)t.PlayCount);Put(h,108,(int)t.BookmarkMilliseconds);Put(h,156,(int)t.SkipCount);if(t.LastPlayedUtc is {} played)BinaryPrimitives.WriteUInt32LittleEndian(h.AsSpan(88),checked((uint)(played.ToUnixTimeSeconds()+2082844800+timeOffset)));if(t.PlayCount>0)h[178]=1;var parts=new List<byte[]>{StringRecord(1,t.Title),StringRecord(2,":"+write.RelativePath.Replace('\\',':').Replace('/',':')),StringRecord(3,t.Album),StringRecord(4,t.Artist),StringRecord(5,t.Genre),StringRecord(22,t.AlbumArtist),StringRecord(12,t.Composer)};if(t.IsPodcast){h[165]=1;h[167]=1;parts.Add(StringRecord(20,t.EpisodeId));parts.Add(StringRecord(14,t.Description[..Math.Min(t.Description.Length,4096)]));foreach(var pair in new[]{(15,t.EnclosureUrl),(16,t.PodcastFeed)}){if(pair.Item2.Length==0)continue;var url=Encoding.UTF8.GetBytes(pair.Item2);if(url.Length>4096)throw new IOException("Podcast 地址过长。");var urlHeader=Header("mhod",24);Put(urlHeader,12,pair.Item1);parts.Add(Join(urlHeader,[url]));}}Put(h,12,parts.Count);return Join(h,parts);}
    internal static byte[] Item(uint id,int position){var h=Header("mhip",76);Put(h,12,1);Put(h,24,(int)id);var m=Header("mhod",24);Put(m,12,100);var body=new byte[20];Put(body,0,position);return Join(h,[Join(m,[body])]);}
    internal static byte[] Index(int kind,int sort,IReadOnlyList<Track> tracks){if(sort is not (3 or 4 or 5 or 7 or 18 or 35 or 36))throw new IOException("未知主列表排序索引，已阻止改写。");string Key(Track t)=>sort switch{4=>t.Album,5 or 36=>t.Artist,7=>t.Genre,35=>t.AlbumArtist,18=>t.Composer,_=>t.Title};var ordered=tracks.Select((t,i)=>(t,i)).OrderBy(x=>Key(x.t),StringComparer.OrdinalIgnoreCase).ThenBy(x=>sort==7?x.t.Artist:sort==35?x.t.Artist:"",StringComparer.OrdinalIgnoreCase).ThenBy(x=>sort is 5 or 7 or 35 or 36?x.t.Album:"",StringComparer.OrdinalIgnoreCase).ThenBy(x=>sort is 3 or 18?0:x.t.Disc).ThenBy(x=>sort is 3 or 18?0:x.t.Number).ThenBy(x=>x.t.Title,StringComparer.OrdinalIgnoreCase).ThenBy(x=>x.i).ToArray();var h=Header("mhod",24);Put(h,12,kind);if(kind==52){var body=new byte[48+ordered.Length*4];Put(body,0,sort);Put(body,4,ordered.Length);for(var i=0;i<ordered.Length;i++)Put(body,48+i*4,ordered[i].i);return Join(h,[body]);}var groups=ordered.Select((x,i)=>(Letter:(ushort)(Key(x.t).Length==0?'0':char.ToUpperInvariant(Key(x.t)[0])),Position:i)).GroupBy(x=>x.Letter).ToArray();var jump=new byte[16+groups.Length*12];Put(jump,0,sort);Put(jump,4,groups.Length);for(var i=0;i<groups.Length;i++){var at=16+i*12;BinaryPrimitives.WriteUInt16LittleEndian(jump.AsSpan(at),groups[i].Key);Put(jump,at+4,groups[i].First().Position);Put(jump,at+8,groups[i].Count());}return Join(h,[jump]);}

    public byte[] Build(byte[] original,IReadOnlyList<DeviceTrackWrite> additions,ReadOnlySpan<byte> identity,int? timeOffset=null)
    {
        if(!DeviceChecksum.VerifyHash58(original,identity))throw new InvalidDataException("E_SIGNATURE：原始数据库校验失败。");
        var reader=new ITunesDbReader();var originalTracks=reader.Read(original,Path.GetTempPath());reader.ReadPlaylists(original);
        if(additions.Count==0)return (byte[])original.Clone();
        if(additions.Any(x=>x.Id==0||x.Id>int.MaxValue)||additions.Select(x=>x.Id).Concat(originalTracks.Select(x=>uint.Parse(x.Id[7..]))).Distinct().Count()!=originalTracks.Count+additions.Count)throw new InvalidDataException("曲目 ID 冲突。");
        var dbHeader=U(original,4);var sections=Children(original,dbHeader);var tracks=originalTracks.Concat(additions.Select(x=>x.Track with{Id="device:"+x.Id})).ToArray();var found=false;
        for(var s=0;s<sections.Count;s++){var section=sections[s];var sh=U(section,4);var type=U(section,12);if(type is not (1 or 2 or 3))throw new InvalidDataException("此数据库含额外索引分区，当前写入器不能更新它们。");var lh=U(section,sh+4);var listHeader=section.AsSpan(sh,lh).ToArray();var items=Children(section,sh+lh);
            if(type==1){items.AddRange(additions.Select(x=>TrackRecord(x,timeOffset??DeviceClock.DatabaseOffset(original))));found=true;}
            else for(var p=0;p<items.Count;p++){var playlist=items[p];if(playlist[20]==0)continue;var ph=U(playlist,4);var children=Children(playlist,ph);var metadata=children.Where(x=>Magic(x)=="mhod").ToList();var entries=children.Where(x=>Magic(x)=="mhip").ToList();if(children.Count!=metadata.Count+entries.Count)throw new InvalidDataException("主列表含未知子记录。");if(entries.Count!=originalTracks.Count)throw new InvalidDataException("主列表与曲目表不一致。");var byId=tracks.ToDictionary(x=>uint.Parse(x.Id[7..]));var playlistTracks=entries.Select(x=>byId[checked((uint)U(x,24))]).Concat(additions.Select(x=>x.Track)).ToArray();for(var m=0;m<metadata.Count;m++){var kind=U(metadata[m],12);if(kind is 52 or 53)metadata[m]=Index(kind,U(metadata[m],24),playlistTracks);}foreach(var sort in new[]{3,4,5,7,18})foreach(var kind in new[]{52,53})if(!metadata.Any(x=>U(x,12)==kind&&U(x,24)==sort))metadata.Add(Index(kind,sort,playlistTracks));entries.AddRange(additions.Select((x,i)=>Item(x.Id,originalTracks.Count+i)));var header=playlist.AsSpan(0,ph).ToArray();Put(header,12,metadata.Count);Put(header,16,entries.Count);items[p]=Join(header,metadata.Concat(entries));}
            sections[s]=Join(section.AsSpan(0,sh).ToArray(),[Join(listHeader,items,true)]);
        }
        if(!found)throw new InvalidDataException("缺少曲目分区。");var result=DeviceChecksum.SignHash58(Join(original.AsSpan(0,dbHeader).ToArray(),sections),identity);if(reader.Read(result,Path.GetTempPath()).Count!=tracks.Length)throw new InvalidDataException("写入结果复读失败。");reader.ReadPlaylists(result);return result;
    }
}
