using System.Buffers.Binary;
using System.Text;
using static iTunesPod.Infrastructure.ITunesDbWriter;
namespace iTunesPod.Infrastructure;
public sealed record ImagePayload(int Format,int Width,int Height,byte[] Pixels);
public sealed record NativeImageReference(int Format,string FileName,int Offset,int Size,int Width,int Height);
public sealed record NativeImage(int Id,ulong TrackId,IReadOnlyList<NativeImageReference> Images);
public sealed record NativePhotoAlbum(int Id,string Name,IReadOnlyList<int> Images,bool IsMaster);
/// <summary>Raw-preserving ArtworkDB and Photo Database editor. Existing image payloads stay immutable.</summary>
public sealed class NativeImageDatabase
{
    byte[] _header;readonly List<byte[]> _sections;readonly string? _beforeHash;
    public NativeImageDatabase(byte[]? original,bool photos=false){_beforeHash=original==null?null:Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(original));if(original==null){_header=Header("mhfd",132);Put(_header,16,photos?6:2);Put(_header,20,3);Put(_header,28,100);Put(_header,48,2);_sections=[];for(var i=1;i<=3;i++){var list=Header(i==1?"mhli":i==2?"mhla":"mhlf",92);Put(list,8,0);var section=Header("mhsd",96);Put(section,12,i);_sections.Add(Join(section,[list]));}if(photos)AddAlbum("Photo Library",[],true);}else{if(original.Length>64*1024*1024||original.Length<132||Magic(original)!="mhfd"||U(original,8)!=original.Length)throw new InvalidDataException("照片数据库无效或超过 64 MiB。");var length=U(original,4);if(length<132||length>original.Length)throw new InvalidDataException("照片数据库头无效。");_header=original.AsSpan(0,length).ToArray();_sections=Children(original,length);if(_sections.Count!=U(original,20))throw new InvalidDataException("照片分区计数不一致。");foreach(var section in _sections){var h=U(section,4);if(h<16||h>section.Length-12)throw new InvalidDataException("照片分区无效。");var lh=U(section,h+4);if(lh<12||lh>section.Length-h)throw new InvalidDataException("照片列表头无效。");if(Children(section,h+lh).Count!=U(section,h+8))throw new InvalidDataException("照片列表计数不一致。");}}}
    List<byte[]> Entries(int type){var section=_sections.Single(x=>U(x,12)==type);var at=U(section,4);return Children(section,at+U(section,at+4));}
    void Replace(int type,List<byte[]> entries){var index=_sections.FindIndex(x=>U(x,12)==type);var section=_sections[index];var h=U(section,4);var lh=U(section,h+4);_sections[index]=Join(section.AsSpan(0,h).ToArray(),[Join(section.AsSpan(h,lh).ToArray(),entries,true)]);}
    public IReadOnlyList<NativeImage> Images(){var result=new List<NativeImage>();foreach(var entry in Entries(1)){if(Magic(entry)!="mhii"||U(entry,4)<52)throw new InvalidDataException("图像记录无效。");var refs=new List<NativeImageReference>();foreach(var child in Children(entry,U(entry,4))){if(Magic(child)!="mhod"||U(child,12) is not (2 or 5))continue;var nodes=Children(child,U(child,4));foreach(var node in nodes){if(Magic(node)!="mhni"||U(node,4)<44)throw new InvalidDataException("图像位置记录无效。");var names=Children(node,U(node,4));var name=names.FirstOrDefault(x=>Magic(x)=="mhod"&&U(x,12)==3);if(name==null)throw new InvalidDataException("图像文件名缺失。");var text=DecodeString(name);refs.Add(new(U(node,16),text,U(node,20),U(node,24),BinaryPrimitives.ReadUInt16LittleEndian(node.AsSpan(34)),BinaryPrimitives.ReadUInt16LittleEndian(node.AsSpan(32))));}}result.Add(new(U(entry,16),BinaryPrimitives.ReadUInt64LittleEndian(entry.AsSpan(20)),refs));}return result;}
    static string DecodeString(byte[] record){var at=U(record,4);if(at>record.Length-12)throw new InvalidDataException("图像字符串头被截断。");var size=U(record,at);if(size>record.Length-at-12)throw new InvalidDataException("图像字符串越界。");return (record[at+4]==2?Encoding.Unicode:Encoding.UTF8).GetString(record,at+12,size).TrimEnd('\0');}
    static byte[] ImageString(int type,string text){var bytes=type==3?Encoding.Unicode.GetBytes(text):Encoding.UTF8.GetBytes(text);var body=new byte[12+(bytes.Length+3)/4*4];Put(body,0,bytes.Length);body[4]=type==3?(byte)2:(byte)1;bytes.CopyTo(body,12);var header=Header("mhod",24);Put(header,12,type);return Join(header,[body]);}
    static byte[] Reference(int type,int format,int width,int height,int size,string filename,int offset){var header=Header("mhni",76);Put(header,12,1);Put(header,16,format);Put(header,20,offset);Put(header,24,size);Put(header,40,size);BinaryPrimitives.WriteUInt16LittleEndian(header.AsSpan(32),(ushort)height);BinaryPrimitives.WriteUInt16LittleEndian(header.AsSpan(34),(ushort)width);var mhod=Header("mhod",24);Put(mhod,12,type);return Join(mhod,[Join(header,[ImageString(3,filename)])]);}
    public (int Id,IReadOnlyList<FileChange> Files) AddImage(ulong trackId,IReadOnlyList<ImagePayload> payloads,string folder,string? originalName=null,byte[]? original=null){var entries=Entries(1);var id=Math.Max(100,Math.Max(U(_header,28),entries.Select(x=>U(x,16)+1).DefaultIfEmpty(100).Max()));var h=Header("mhii",152);Put(h,16,id);BinaryPrimitives.WriteUInt64LittleEndian(h.AsSpan(20),trackId);Put(h,48,original?.Length??payloads.Sum(x=>x.Pixels.Length));var nodes=new List<byte[]>();var changes=new List<FileChange>();var suffix=System.Security.Cryptography.RandomNumberGenerator.GetInt32(2,1_000_000).ToString();var fileEntries=Entries(3);foreach(var payload in payloads){if(payload.Width<=0||payload.Height<=0||payload.Pixels.Length!=checked(payload.Width*payload.Height*2))throw new InvalidDataException("RGB565 图像字节数不匹配。");var basename=$"F{payload.Format}_{suffix}.ithmb";var relative=folder+"/"+basename;changes.Add(new(relative,payload.Pixels){CheckBefore=true});nodes.Add(Reference(2,payload.Format,payload.Width,payload.Height,payload.Pixels.Length,folder.StartsWith("Photos")?":Thumbs:"+basename:":"+basename,0));if(!fileEntries.Any(x=>U(x,16)==payload.Format)){var file=Header("mhif",124);Put(file,16,payload.Format);Put(file,20,payload.Pixels.Length);fileEntries.Add(file);}}
        if(original!=null){var name=$"Full Resolution/{id}-{suffix}{Path.GetExtension(originalName)}";changes.Add(new("Photos/"+name,original){CheckBefore=true});nodes.Insert(0,Reference(5,1,0,0,original.Length,":"+name.Replace('/',':'),0));}Put(h,12,nodes.Count);entries.Add(Join(h,nodes));Replace(1,entries);Replace(3,fileEntries);Put(_header,28,id+1);return(id,changes);}
    public IReadOnlyList<NativePhotoAlbum> Albums(){var result=new List<NativePhotoAlbum>();foreach(var album in Entries(2)){if(Magic(album)!="mhba"||U(album,4)<64)throw new InvalidDataException("相册记录无效。");var children=Children(album,U(album,4));var name=children.FirstOrDefault(x=>Magic(x)=="mhod"&&U(x,12)==1);result.Add(new(U(album,20),name==null?"未命名相册":DecodeString(name),children.Where(x=>Magic(x)=="mhia").Select(x=>U(x,16)).ToArray(),album[30]==1));}return result;}
    static byte[] PhotoMember(int id){var h=Header("mhia",40);Put(h,16,id);return h;}
    public int AddAlbum(string name,IReadOnlyList<int> ids,bool master=false){var entries=Entries(2);var id=entries.Select(x=>U(x,20)).DefaultIfEmpty().Max()+1;var h=Header("mhba",148);Put(h,12,1);Put(h,16,ids.Count);Put(h,20,id);h[30]=master?(byte)1:(byte)2;Put(h,36,5);Put(h,40,1);entries.Add(Join(h,new[]{ImageString(1,name)}.Concat(ids.Select(PhotoMember))));Replace(2,entries);return id;}
    public void SetAlbum(int id,string name,IReadOnlyList<int> ids){var entries=Entries(2);var at=entries.FindIndex(x=>U(x,20)==id);if(at<0)throw new IOException("相册不存在。");var original=entries[at];var children=Children(original,U(original,4));var replaced=false;for(var i=0;i<children.Count;i++)if(Magic(children[i])=="mhod"&&U(children[i],12)==1){children[i]=ImageString(1,name);replaced=true;}if(!replaced)children.Insert(0,ImageString(1,name));children.RemoveAll(x=>Magic(x)=="mhia");children.AddRange(ids.Select(PhotoMember));var h=original.AsSpan(0,U(original,4)).ToArray();Put(h,16,ids.Count);entries[at]=Join(h,children);Replace(2,entries);}
    public void RemoveAlbum(int id){var entries=Entries(2);var album=entries.Single(x=>U(x,20)==id);if(album[30]==1)throw new IOException("不能删除系统相册。");entries.Remove(album);Replace(2,entries);}
    public void RemoveImage(int id){var entries=Entries(1);entries.RemoveAll(x=>U(x,16)==id);Replace(1,entries);foreach(var album in Albums())if(album.Images.Contains(id))SetAlbum(album.Id,album.Name,album.Images.Where(x=>x!=id).ToArray());}
    public FileChange Change(string path)=>new(path,Build()){CheckBefore=true,ExpectedBeforeHash=_beforeHash};
    public byte[] Build()=>Join(_header,_sections);
    public void VerifyFiles(string root,bool photos){var images=Images();var ids=images.Select(x=>x.Id).ToHashSet();if(ids.Count!=images.Count)throw new IOException("图像 ID 重复。");if(photos)foreach(var album in Albums())if(album.Images.Any(id=>!ids.Contains(id)))throw new IOException("相册引用不存在的图像。");foreach(var image in images)foreach(var reference in image.Images){var relative=reference.FileName.TrimStart(':').Replace(':','/');var path=DeviceAccess.SafePath(root,photos?(relative.StartsWith("Photos/",StringComparison.OrdinalIgnoreCase)?relative:"Photos/"+relative):"iPod_Control/Artwork/"+relative);var file=new FileInfo(path);if(!file.Exists||reference.Offset<0||reference.Size<0||(long)reference.Offset+reference.Size>file.Length)throw new IOException("图像载荷引用越界或缺失。");if(reference.Format is 1024 or 1055 or 1066 or 1071 or 1074 or 1078 or 1079 or 1083){if(reference.Width<=0||reference.Height<=0||checked((long)reference.Width*reference.Height*2)>reference.Size)throw new IOException("RGB565 图像尺寸与载荷不符。");}}}
}
