using System.Security.Cryptography;
using System.Text;
using System.Xml;
using System.Xml.Linq;
namespace iTunesPod.Infrastructure;
public sealed record PodcastEpisode(string Id,string Feed,string Show,string Title,string Url,DateTimeOffset? Published,string Description,string? DownloadPath=null,bool Played=false);
public sealed class PodcastService
{
    readonly HttpClient _http=new(new HttpClientHandler{AllowAutoRedirect=false}){Timeout=TimeSpan.FromSeconds(40)};
    public static Uri ValidateUrl(string url){if(!Uri.TryCreate(url,UriKind.Absolute,out var uri)||uri.Scheme is not ("http" or "https")||uri.UserInfo.Length>0)throw new IOException("仅支持 HTTP / HTTPS 地址。");return uri;}
    async Task<HttpResponseMessage> Get(string url,CancellationToken token){var uri=ValidateUrl(url);for(var i=0;i<6;i++){var response=await _http.GetAsync(uri,HttpCompletionOption.ResponseHeadersRead,token);if((int)response.StatusCode is >=300 and <400&&response.Headers.Location!=null){uri=ValidateUrl(new Uri(uri,response.Headers.Location).AbsoluteUri);response.Dispose();continue;}response.EnsureSuccessStatusCode();return response;}throw new IOException("重定向次数超过限制。");}
    public static IReadOnlyList<PodcastEpisode> Parse(string xml,string feed){using var reader=XmlReader.Create(new StringReader(xml),new XmlReaderSettings{DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null,MaxCharactersInDocument=4*1024*1024});var doc=XDocument.Load(reader);var channel=doc.Descendants().FirstOrDefault(x=>x.Name.LocalName=="channel")??throw new IOException("不是 RSS Podcast 订阅。");string Value(XElement e,string key)=>e.Elements().FirstOrDefault(x=>x.Name.LocalName==key)?.Value.Trim()??"";var show=Value(channel,"title");var episodes=new List<PodcastEpisode>();foreach(var item in channel.Elements().Where(x=>x.Name.LocalName=="item").Take(5000)){var enclosure=item.Elements().FirstOrDefault(x=>x.Name.LocalName=="enclosure");var url=enclosure?.Attribute("url")?.Value;if(string.IsNullOrWhiteSpace(url))continue;ValidateUrl(url);var guid=Value(item,"guid");if(guid.Length==0)guid=url;var id=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(feed+"\n"+guid)));episodes.Add(new(id,feed,show,Value(item,"title"),url,DateTimeOffset.TryParse(Value(item,"pubDate"),out var date)?date:null,Value(item,"description")));}return episodes.DistinctBy(x=>x.Id).ToArray();}
    public async Task<IReadOnlyList<PodcastEpisode>> RefreshAsync(string feed,CancellationToken token=default){using var response=await Get(feed,token);if(response.Content.Headers.ContentLength>4*1024*1024)throw new IOException("RSS 超过 4 MiB。");await using var stream=await response.Content.ReadAsStreamAsync(token);using var output=new MemoryStream();var buffer=new byte[81920];int n;while((n=await stream.ReadAsync(buffer,token))>0){if(output.Length+n>4*1024*1024)throw new IOException("RSS 超过 4 MiB。");output.Write(buffer,0,n);}using var reader=new StreamReader(new MemoryStream(output.ToArray()),Encoding.UTF8,true);return Parse(await reader.ReadToEndAsync(token),feed);}
    public async Task<string> DownloadAsync(PodcastEpisode episode,string folder,IProgress<string>? progress=null,CancellationToken token=default){Directory.CreateDirectory(folder);using var response=await Get(episode.Url,token);const long limit=1024L*1024*1024;if(response.Content.Headers.ContentLength>limit)throw new IOException("单集超过 1 GiB。");var extension=Path.GetExtension(ValidateUrl(episode.Url).AbsolutePath).ToLowerInvariant();if(extension is not (".mp3" or ".m4a" or ".mp4" or ".aac" or ".ogg" or ".wav"))extension=".mp3";var final=Path.Combine(folder,episode.Id+extension);if(File.Exists(final)){await new MediaTools(folder).ProbeAsync(final,token);return final;}var partial=final+".partial";try{await using(var input=await response.Content.ReadAsStreamAsync(token))await using(var output=new FileStream(partial,FileMode.Create,FileAccess.Write,FileShare.None,81920,true)){var buffer=new byte[81920];int n;long total=0;while((n=await input.ReadAsync(buffer,token))>0){total+=n;if(total>limit)throw new IOException("单集超过下载限制。");await output.WriteAsync(buffer.AsMemory(0,n),token);progress?.Report(episode.Title+" · "+total/1024+" KiB");}if(response.Content.Headers.ContentLength is long expected&&total!=expected)throw new IOException("下载长度不匹配。");}var probe=await new MediaTools(folder).ProbeAsync(partial,token);if(probe.Seconds<=0||probe.AudioCodec.Length==0)throw new IOException("下载内容不是有效音频。");File.Move(partial,final);return final;}catch{if(File.Exists(partial))File.Delete(partial);throw;}}
}
