using System.Buffers.Binary;
using System.Globalization;
using System.Text;
using iTunesPod.Core;
using static iTunesPod.Infrastructure.ITunesDbWriter;
namespace iTunesPod.Infrastructure;
public static class SmartPlaylistBinary
{
    public static SmartDefinition? Decode(byte[] preferences,byte[] rules){try{var ph=U(preferences,4);var rh=U(rules,4);if(preferences.Length-ph!=72||rules.Length-rh<136)return null;var pref=preferences.AsSpan(ph);var raw=rules.AsSpan(rh);if(!raw[..4].SequenceEqual("SLst"u8)||pref[0]!=1||pref[1]!=1||pref[4] is not (3 or 4 or 5 or 16 or 20 or 21 or 23)||BinaryPrimitives.ReadUInt32BigEndian(raw[12..])>1||pref[3] is not (1 or 3 or 4)||pref[12]!=0||pref[13]!=0||pref[14..].IndexOfAnyExcept((byte)0)>=0)return null;var count=BinaryPrimitives.ReadUInt32BigEndian(raw[8..]);if(count is 0 or >64)return null;var result=new List<SmartRule>();var at=136;for(var i=0;i<count;i++){if(at>raw.Length-56)return null;var field=(int)BinaryPrimitives.ReadUInt32BigEndian(raw[at..]);var action=BinaryPrimitives.ReadUInt32BigEndian(raw[(at+4)..]);if(!SmartPlaylists.Fields.ContainsKey(field)||raw.Slice(at+8,44).IndexOfAnyExcept((byte)0)>=0)return null;var length=checked((int)BinaryPrimitives.ReadUInt32BigEndian(raw[(at+52)..]));at+=56;if(length<0||length>4096||length>raw.Length-at)return null;var value=raw.Slice(at,length);var text=SmartPlaylists.IsText(field);var comparison=action switch{1 or 0x01000001=>"等于",0x02000001 or 0x03000001=>"不等于",0x01000002=>"包含",0x03000002=>"不包含",0x01000004=>"开头是",0x01000008=>"结尾是",16=>"大于",64=>"小于",512=>"在最近天数内",0x02000200=>"不在最近天数内",1024=>"等于",0x02000400=>"不等于",_=>null};if(comparison==null)return null;string parsed;if(text){if(length%2!=0)return null;parsed=new UnicodeEncoding(true,false,true).GetString(value);}else{if(length!=68||value[48..].IndexOfAnyExcept((byte)0)>=0)return null;if(SmartPlaylists.IsDate(field)){if(action is not (512 or 0x02000200)||BinaryPrimitives.ReadUInt64BigEndian(value)!=0x2DAE2DAE2DAE2DAE||BinaryPrimitives.ReadUInt64BigEndian(value[24..])!=0x2DAE2DAE2DAE2DAE||BinaryPrimitives.ReadUInt64BigEndian(value[16..])!=86400)return null;parsed=(-BinaryPrimitives.ReadInt64BigEndian(value[8..])).ToString(CultureInfo.InvariantCulture);}else parsed=(BinaryPrimitives.ReadUInt64BigEndian(value)/(field==25?20d:field==13?1000d:1d)).ToString(CultureInfo.InvariantCulture);}result.Add(new(field,comparison,parsed));at+=length;}if(at!=raw.Length)return null;var definition=new SmartDefinition(BinaryPrimitives.ReadUInt32BigEndian(raw[12..])==0,result,pref[4] switch{5=>"艺术家",4=>"专辑",23=>"评分",20=>"播放次数",16=>"最近添加",21=>"最近播放",_=>"标题"},pref[2]==0?0:U(preferences,ph+8),pref[3] switch{1=>"分钟",4=>"小时",_=>"首"});SmartPlaylists.Evaluate(definition,[]);return definition;}catch(Exception e)when(e is ArgumentException or OverflowException or InvalidDataException){return null;}}
    public static IReadOnlyList<byte[]> Encode(SmartDefinition definition){SmartPlaylists.Evaluate(definition,[]);var prefs=new byte[72];prefs[0]=1;prefs[1]=1;prefs[2]=definition.Limit>0?(byte)1:(byte)0;prefs[3]=definition.LimitUnit switch{"分钟"=>1,"小时"=>4,_=>3};prefs[4]=definition.Sort switch{"艺术家"=>5,"专辑"=>4,"评分"=>23,"播放次数"=>20,"最近添加"=>16,"最近播放"=>21,_=>3};Put(prefs,8,definition.Limit);var h50=Header("mhod",24);Put(h50,12,50);var header=new byte[136];"SLst"u8.CopyTo(header);BinaryPrimitives.WriteUInt32BigEndian(header.AsSpan(4),0x10001);BinaryPrimitives.WriteUInt32BigEndian(header.AsSpan(8),(uint)definition.Rules.Count);BinaryPrimitives.WriteUInt32BigEndian(header.AsSpan(12),definition.MatchAll?0u:1u);using var body=new MemoryStream();body.Write(header);foreach(var rule in definition.Rules){var text=SmartPlaylists.IsText(rule.Field);uint action=rule.Comparison switch{"等于"=>text?0x01000001u:1u,"不等于"=>text?0x03000001u:0x02000001u,"包含"=>0x01000002,"不包含"=>0x03000002,"开头是"=>0x01000004,"结尾是"=>0x01000008,"大于"=>16,"小于"=>64,"在最近天数内"=>512,"不在最近天数内"=>0x02000200,_=>throw new IOException("规则比较无效。")};if(rule.Field==60)action=rule.Comparison=="等于"?1024u:0x02000400u;byte[] data;if(text)data=Encoding.BigEndianUnicode.GetBytes(rule.Value);else{data=new byte[68];var value=SmartPlaylists.IsDate(rule.Field)?0:double.Parse(rule.Value,CultureInfo.InvariantCulture)*(rule.Field==25?20:rule.Field==13?1000:1);var integer=checked((ulong)value);BinaryPrimitives.WriteUInt64BigEndian(data,integer);BinaryPrimitives.WriteUInt64BigEndian(data.AsSpan(16),1);BinaryPrimitives.WriteUInt64BigEndian(data.AsSpan(24),integer);BinaryPrimitives.WriteUInt64BigEndian(data.AsSpan(40),1);if(SmartPlaylists.IsDate(rule.Field)){BinaryPrimitives.WriteUInt64BigEndian(data,0x2DAE2DAE2DAE2DAE);BinaryPrimitives.WriteInt64BigEndian(data.AsSpan(8),-long.Parse(rule.Value,CultureInfo.InvariantCulture));BinaryPrimitives.WriteUInt64BigEndian(data.AsSpan(16),86400);BinaryPrimitives.WriteUInt64BigEndian(data.AsSpan(24),0x2DAE2DAE2DAE2DAE);}}if(data.Length>4096)throw new IOException("规则文本过长。");var rh=new byte[56];BinaryPrimitives.WriteUInt32BigEndian(rh,(uint)rule.Field);BinaryPrimitives.WriteUInt32BigEndian(rh.AsSpan(4),action);BinaryPrimitives.WriteUInt32BigEndian(rh.AsSpan(52),(uint)data.Length);body.Write(rh);body.Write(data);}var h51=Header("mhod",24);Put(h51,12,51);return [Join(h50,[prefs]),Join(h51,[body.ToArray()])];}
}
