using System.Diagnostics;
using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using iTunesPod.Core;
using iTunesPod.Infrastructure;
using Microsoft.Win32;
namespace iTunesPod.App;
public sealed partial class MainWindow
{
    async Task Discover(bool force){if(_discovering)return;_discovering=true;try{var changed=false;var roots=await Task.Run(_devices.Discover);foreach(var root in _sessions.Keys.Where(x=>string.Equals(Path.GetFullPath(x).TrimEnd(Path.DirectorySeparatorChar),Path.GetPathRoot(x)?.TrimEnd(Path.DirectorySeparatorChar),StringComparison.OrdinalIgnoreCase)&&!roots.Contains(x,StringComparer.OrdinalIgnoreCase)).ToArray()){changed=true;DeviceAccess.InvalidateMount(root);_sessions.Remove(root);_stamps.Remove(root);if(_device?.Root==root){_device=null;_draft.Clear();if(_route=="设备")Navigate("新发现");}}
        foreach(var root in roots){var db=Path.Combine(root,"iPod_Control/iTunes/iTunesDB");if(!File.Exists(db))db=Path.Combine(root,"iPod_Control/iTunes/iTunesCDB");var stamp=File.Exists(db)?new FileInfo(db).Length+":"+File.GetLastWriteTimeUtc(db).Ticks:"missing";if(!force&&_stamps.GetValueOrDefault(root)==stamp)continue;changed=true;var session=await Task.Run(()=>_devices.InspectAsync(root,_lifetime.Token));_sessions[root]=session;_stamps[root]=stamp;if(_device==null||_device.Root==root)SelectDevice(session);await ReadArtwork(session);}if(changed){RebuildDevices();if(_route=="新发现"||_route=="主页"||_route=="设备")Navigate(_route);}
    }finally{_discovering=false;}}
    void SelectDevice(DeviceSession session){ImportStatistics(session);_device=session;_draft.Clear();_draft.UnionWith(_store.LoadDraft(session.DeviceId));_undo.Clear();}
    void RebuildDevices(){_deviceNav.Children.Clear();if(_sessions.Count==0){var label=T("连接 iPod 后自动显示",11,true);label.Margin=new(10,7,0,5);_deviceNav.Children.Add(label);}foreach(var session in _sessions.Values){var b=Action(session.Name,()=>{SelectDevice(session);_deviceTab="概览";Navigate("设备");return Task.CompletedTask;},"usb");b.Style=(Style)Resources["Nav"];_deviceNav.Children.Add(b);}}
    async Task OpenDevice(){var dialog=new OpenFolderDialog{Title="选择包含 iPod_Control 的设备目录"};if(dialog.ShowDialog(this)!=true)return;var session=await Task.Run(()=>_devices.InspectAsync(dialog.FolderName));_sessions[session.Root]=session;SelectDevice(session);RebuildDevices();Navigate("设备");await ReadArtwork(session);Navigate("设备");}
    async Task ReadArtwork(DeviceSession session){_status.Text="正在读取设备封面…";var tracks=await Task.Run(()=>MediaArtwork.ReadCoversAsync(session.Tracks,Path.Combine(_store.DataDirectory,"device-covers",session.DeviceId.Replace(':','_')),_lifetime.Token));try{tracks=await Task.Run(()=>ReadNativeCovers(session,tracks));}catch(InvalidDataException){/* Keep embedded covers when an opaque artwork database cannot be decoded. */}var result=session with{Tracks=tracks};_sessions[session.Root]=result;if(_device?.DeviceId==session.DeviceId)_device=result;_status.Text="设备资料库读取完成";}
    void Device(){if(_device==null){_page.Content=Empty("连接你的 iPod","通过 USB 连接设备并启用磁盘模式。",Action("重新扫描",()=>Discover(true),"refresh",true));return;}_title.Text=_device.Name;_subtitle.Text=_device.Model+" · "+_device.Tracks.Count+" 首歌曲";
        foreach(var label in new[]{"概览","歌曲","专辑","艺术家","播放列表","照片","备忘录","快照"}){var b=Action(label,()=>{_deviceTab=label;Navigate("设备");return Task.CompletedTask;});b.Margin=new(0,0,6,0);if(label==_deviceTab){b.Background=B("Selection");((TextBlock)b.Content).Foreground=B("Accent");}_tabs.Children.Add(b);}switch(_deviceTab){case "歌曲":Music(_device.Tracks,true);break;case "专辑":Albums(_device.Tracks);break;case "艺术家":Artists(_device.Tracks);break;case "播放列表":Playlists(true);break;case "照片":DevicePhotos();break;case "备忘录":Notes();break;case "快照":Snapshots();break;default:DeviceOverview();break;}}
    void DeviceOverview(){var d=_device!;var panel=Stack();var hero=Grid("210,*","*");hero.Margin=new(0,12,0,8);hero.Children.Add(DeviceProductImage(d,180,300));var name=T(d.Model,30);name.FontWeight=FontWeights.Bold;var details=Stack(T("已连接 · "+d.Identity.FileSystem+" · "+d.Identity.Confidence,12,true),name,T(d.Identity.ModelNumber+" "+d.Identity.Color,12,true),T($"{d.Tracks.Count} 首歌曲    {d.Tracks.GroupBy(x=>x.AlbumKey).Count()} 张专辑    {d.Playlists.Count} 个播放列表",17),T($"{Bytes(d.FreeBytes)} 可用 / {Bytes(d.TotalBytes)} 总容量",13,true),new ProgressBar{Maximum=Math.Max(1,d.TotalBytes),Value=d.TotalBytes-d.FreeBytes,Height=6,Foreground=B("Accent"),Background=B("Panel"),BorderThickness=new(0)},T("音乐 "+Bytes(d.Tracks.Where(x=>File.Exists(x.Path)).Sum(x=>x.Bytes))+" · 其他 "+Bytes(Math.Max(0,d.TotalBytes-d.FreeBytes-d.Tracks.Where(x=>File.Exists(x.Path)).Sum(x=>x.Bytes))),12,true),Row(Action("浏览歌曲",()=>{_deviceTab="歌曲";Navigate("设备");return Task.CompletedTask;},"music",true),Action("识别详情",Identity,"info")),Row(Action("重命名",RenameDevice),Action("回写播放统计",CommitStatistics),Action("刷新设备",()=>Discover(true),"refresh"),Action("安全弹出",async()=>{var target=TargetDevice!;SavePlaybackPosition();_player.Stop();await DeviceEject.EjectAsync(target,_lifetime.Token);DeviceAccess.InvalidateMount(target.Root);_sessions.Remove(target.Root);if(_device?.DeviceId==target.DeviceId){_device=null;_draft.Clear();}RebuildDevices();Navigate("新发现");Notify("设备已安全弹出。");},"usb")));
        foreach(var child in details.Children.OfType<FrameworkElement>())child.Margin=new(0,0,0,16);details.VerticalAlignment=VerticalAlignment.Center;Col(details,1);hero.Children.Add(details);panel.Children.Add(hero);var missing=d.Tracks.Count(x=>!File.Exists(x.Path));var status=T((missing>0?$"{missing} 条歌曲记录缺少对应媒体文件。 ":"")+(d.ReadError??d.ReadOnlyReason),12,true);status.Margin=new(0,16,0,0);panel.Children.Add(status);panel.Children.Add(SectionHeading("设备中的专辑",()=>{_deviceTab="专辑";Navigate("设备");return Task.CompletedTask;}));panel.Children.Add(AlbumRail(d.Tracks,12));_page.Content=new ScrollViewer{Content=panel};}
    Task Identity(){var d=_device!;var fields=Stack(T(d.Model,24),T("型号 "+d.Identity.ModelNumber),T("序列号 "+d.Identity.SerialMasked),T("USB "+d.Identity.HardwareId),T("数据库版本 "+d.DatabaseVersion),T("挂载目录 "+d.Root));foreach(var e in d.Identity.Evidence){var text=T(e.Field+"："+e.Value+"\n来源："+e.Source,12,true);text.Margin=new(0,12,0,0);fields.Children.Add(text);}ShowDialog("设备识别详情",new ScrollViewer{Content=fields});return Task.CompletedTask;}
    void Notes(){var folder=DeviceAccess.SafePath(_device!.Root,"Notes");var panel=Stack(T("设备备忘录",22),Row(Action("新建",()=>EditNote(null),"add",true),Action("导入文本",async()=>{var picker=new OpenFileDialog{Filter="文本|*.txt;*.md|所有文件|*.*",Multiselect=true};if(picker.ShowDialog(this)==true){var changes=new List<FileChange>();foreach(var file in picker.FileNames)changes.Add(DeviceNotes.Save(Path.GetFileName(file),await File.ReadAllTextAsync(file)));await CommitFiles(changes,"导入备忘录");Notes();}},"folder")));
        if(Directory.Exists(folder))foreach(var path in Directory.EnumerateFiles(folder).Where(x=>!Path.GetFileName(x).Contains(".itp-")).Take(1000)){var relative=Path.GetRelativePath(_device.Root,path);panel.Children.Add(Row(Action(Path.GetFileName(path),()=>EditNote(path),"info"),Action("导出",async()=>{var save=new SaveFileDialog{FileName=Path.GetFileName(path),Filter="文本|*.txt"};if(save.ShowDialog(this)==true){if(Path.GetFullPath(save.FileName).StartsWith(Path.GetFullPath(_device.Root),StringComparison.OrdinalIgnoreCase))throw new IOException("请选择设备之外的保存目录。");await File.WriteAllBytesAsync(save.FileName,await File.ReadAllBytesAsync(path));}},"export"),Action("删除",async()=>{if(MessageBox.Show(this,"删除这篇设备备忘录？提交前会保留恢复备份。","备忘录",MessageBoxButton.OKCancel)==MessageBoxResult.OK){await CommitFiles([new(relative,null)],"删除备忘录");Notes();}})));}else panel.Children.Add(T("还没有备忘录。",13,true));_page.Content=new ScrollViewer{Content=panel};}
    async Task EditNote(string? path){var originalHash=path==null?null:await DeviceBackup.HashAsync(path);var name=new TextBox{Text=path==null?"新备忘录.txt":Path.GetFileName(path)};var content=new TextBox{Text=path==null?"":DeviceNotes.Read(path),AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=250,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};var panel=Stack(T("文件名",12),name,T("正文 · 最多 4096 UTF-8 字节",12,true),content);if(ShowDialog("编辑备忘录",panel,true)){var change=DeviceNotes.Save(name.Text,content.Text) with{CheckBefore=true,ExpectedBeforeHash=path!=null&&Path.GetFileName(path).Equals(name.Text,StringComparison.OrdinalIgnoreCase)?originalHash:null};var changes=new List<FileChange>{change};if(path!=null&&!Path.GetRelativePath(TargetDevice!.Root,path).Replace('\\','/').Equals(change.RelativePath,StringComparison.OrdinalIgnoreCase))changes.Insert(0,new(Path.GetRelativePath(TargetDevice.Root,path),null){CheckBefore=true,ExpectedBeforeHash=originalHash});await CommitFiles(changes,"保存备忘录");Notes();}}
    async Task CommitFiles(IReadOnlyList<FileChange> changes,string title){var session=TargetDevice??throw new IOException("请先选择设备。");var activity=StartActivity(title,changes.Count+" 个文件更改");try{activity.Detail=await Task.Run(()=>DeviceFileTransaction.ApplyCoreAsync(session,changes,_store.DataDirectory,_lifetime.Token,true,()=>{foreach(var change in changes){var relative=change.RelativePath.Replace((char)92,(char)47);if(relative=="Photos/Photo Database"||relative=="iPod_Control/Artwork/ArtworkDB"){var native=new NativeImageDatabase(File.ReadAllBytes(DeviceAccess.SafePath(session.Root,relative)),relative.StartsWith("Photos/"));native.VerifyFiles(session.Root,relative.StartsWith("Photos/"));}}return Task.CompletedTask;}));activity.State="已完成";Notify(title+"完成，恢复备份已保留。");}catch{activity.State="失败";throw;}finally{SaveActivities();}}
    void Snapshots(){var destination=DeviceBackup.Destination(_store.DataDirectory,TargetDevice!.DeviceId);async Task Backup(bool full){var activity=StartActivity(full?"完整设备备份":"元数据快照",TargetDevice!.Name);var progress=new Progress<string>(s=>_status.Text="备份："+s);try{activity.Detail=await Task.Run(()=>DeviceBackup.CreateAsync(TargetDevice,destination,full,progress,_lifetime.Token));activity.State="已完成";Snapshots();}catch{activity.State="失败";throw;}finally{SaveActivities();}}var panel=Stack(T("设备备份与恢复",22),T("元数据快照包含数据库、全部封面、照片与备忘录。完整备份同时保存音乐文件。恢复前会校验备份并保存当前状态。",13,true),Row(Action("创建快照",()=>Backup(false),"export",true),Action("完整备份",()=>Backup(true),"folder")));
        if(Directory.Exists(destination))foreach(var path in Directory.EnumerateDirectories(destination).OrderDescending()){var incomplete=File.Exists(Path.Combine(path,"INCOMPLETE"));panel.Children.Add(Row(T(Path.GetFileName(path)+(incomplete?" · 未完成":""),12),Action("继续未完成备份",async()=>{if(!incomplete){Notify("备份已完成。");return;}await Task.Run(()=>DeviceBackup.ResumeAsync(TargetDevice!,path,new Progress<string>(x=>_status.Text=x),_lifetime.Token));Snapshots();}),Action("校验",async()=>{var manifest=await Task.Run(()=>DeviceBackup.VerifyAsync(path,_lifetime.Token));Notify("备份校验通过："+manifest.Files.Count+" 个文件");}),Action("恢复此备份",async()=>{if(incomplete)throw new IOException("不能恢复未完成的备份。");if(MessageBox.Show(this,"恢复此备份中的数据库、封面、照片与备忘录，并移除备份中不存在的附属文件？完整备份还会恢复音乐集合；当前状态会另行备份。","恢复设备",MessageBoxButton.OKCancel)==MessageBoxResult.OK){var manifest=await Task.Run(()=>DeviceBackup.VerifyAsync(path,_lifetime.Token));if(manifest.Full)await Task.Run(()=>DeviceFileTransaction.RestoreFullAsync(TargetDevice!,path,_store.DataDirectory,_lifetime.Token));else await Task.Run(()=>DeviceFileTransaction.RestoreMetadataAsync(TargetDevice!,path,_store.DataDirectory,_lifetime.Token));await Discover(true);Notify("元数据恢复完成。");}})));}_page.Content=new ScrollViewer{Content=panel};}
    void AddDraft(IEnumerable<Track> tracks){if(_device==null){Notify("先连接或选择 iPod。");return;}_undo.Push(_draft.ToArray());_draft.UnionWith(tracks.Select(x=>x.Id));_store.SaveDraft(_device.DeviceId,_draft);UpdateDraft();}
    void UndoDraft(){if(_device==null)return;if(_undo.TryPop(out var before)){_draft.Clear();_draft.UnionWith(before);}else _draft.Clear();_store.SaveDraft(_device.DeviceId,_draft);UpdateDraft();}
    async Task ShowPlan(){if(_device==null)return;var panel=Stack(T("检查同步草稿",22),T("可以排除失效来源，再生成格式、封面和数据库预览。",12,true));var map=_tracks.ToDictionary(x=>x.Id);foreach(var id in _draft.ToArray()){var label=map.TryGetValue(id,out var track)?track.Artist+" — "+track.Title+(File.Exists(track.Path)?"":" · 来源失效"):"来源已从索引移除";var row=Row(T(label,13));row.Children.Add(Action("排除",()=>{_undo.Push(_draft.ToArray());_draft.Remove(id);_store.SaveDraft(_device.DeviceId,_draft);UpdateDraft();row.Visibility=Visibility.Collapsed;return Task.CompletedTask;}));panel.Children.Add(row);}if(ShowDialog("同步草稿",new ScrollViewer{Content=panel},true,"准备预览"))await PrepareSyncPreview();}
    void UpdateDraft(){_draftBar.Visibility=_draft.Count>0?Visibility.Visible:Visibility.Collapsed;var row=Grid("*,Auto,Auto","*");row.Children.Add(T($"{_draft.Count} 首歌曲待加入 · 草稿保存在电脑",12));var review=Action("查看更改",ShowPlan);Col(review,1);row.Children.Add(review);var undo=Action("撤销草稿",()=>{UndoDraft();return Task.CompletedTask;});Col(undo,2);row.Children.Add(undo);_draftBar.Child=row;_draftBar.Padding=new(40,9,30,9);_draftBar.Background=B("Panel");}
    async Task PrepareSyncPreview(){if(TargetDevice==null)return;var selected=_tracks.Where(x=>_draft.Contains(x.Id)).ToArray();if(selected.Length==0){Notify("草稿为空。");return;}var activity=StartActivity("准备同步","检查格式与生成数据库");try{var progress=new Progress<string>(s=>{_status.Text=s;activity.Detail=s;});var sync=new DeviceSync(_store.DataDirectory);var plan=await Task.Run(()=>sync.PrepareAsync(TargetDevice,selected,progress,_lifetime.Token));plan=await AttachCovers(plan);var panel=Stack(T(plan.Media.Count+" 首新增 · "+plan.ExistingMatches.Count+" 首已存在 · 写入峰值 "+Bytes(plan.RequiredBytes),22),T("音乐将写入设备目录，并更新已验证签名的数据库。提交前自动备份全部元数据与封面；原有歌曲和播放列表保留。",13,true));foreach(var entry in plan.Media)panel.Children.Add(T(entry.Write.Track.Artist+" — "+entry.Write.Track.Title+" · "+entry.Write.Track.Format+" · "+Bytes(entry.Write.Track.Bytes),13));var execute=Action("执行同步",async()=>{var backup=await Task.Run(()=>sync.CommitAsync(plan,progress,_lifetime.Token));_store.SaveDraft(plan.Device.DeviceId,[]);if(_device?.DeviceId==plan.Device.DeviceId){_draft.Clear();UpdateDraft();}activity.State="已完成";activity.Detail="同步完成，恢复备份："+backup;SaveActivities();Notify("同步完成。请安全弹出后在 iPod 上检查新歌曲。");await Discover(true);},"usb",true);panel.Children.Add(execute);activity.State="等待提交";ShowDialog("同步更改预览",new ScrollViewer{Content=panel});}catch{activity.State="失败";throw;}finally{SaveActivities();}}
    void Playlists(bool device=false){var lists=device?_device!.Playlists:_store.LoadPlaylists().Select(x=>x.SmartDefinition==null?x:x with{TrackIds=SmartPlaylists.Evaluate(x.SmartDefinition,_tracks).Select(t=>t.Id).ToArray()}).ToArray();var panel=Stack(Row(Action("新建播放列表",()=>CreatePlaylist(device),"add",true),Action("智能播放列表",()=>CreateSmartPlaylist(device),"list"),Action("导入 M3U",ImportPlaylist,"folder")));foreach(var list in lists){var row=Stack(Row(Action(list.Name+" · "+list.TrackIds.Count+" 首",()=>{var source=device?_device!.Tracks:_tracks;var map=source.ToDictionary(x=>x.Id);_title.Text=list.Name;Music(list.TrackIds.Where(map.ContainsKey).Select(id=>map[id]),device);return Task.CompletedTask;},"list"),Action("编辑 / 排序",()=>EditPlaylist(list,device)),Action("复制",()=>SavePlaylist(list with{Id=device?"device-playlist:"+Convert.ToHexString(System.Security.Cryptography.RandomNumberGenerator.GetBytes(8)):Guid.NewGuid().ToString("N"),Name=list.Name+" 副本",IsSmart=false,IsSystem=false,SmartDefinition=null},device)),Action("导出",()=>ExportPlaylist(list,device),"export"),Action("删除",()=>DeletePlaylist(list,device))));if(!device)row.Children.Add(Action("同步列表到 iPod",()=>SyncPlaylist(list),"usb"));row.Margin=new(0,12,0,12);panel.Children.Add(row);}_page.Content=new ScrollViewer{Content=panel};}
    Task AddToPlaylist(Track[] tracks){if(tracks.Length==0){Notify("先选择歌曲。");return Task.CompletedTask;}var lists=_store.LoadPlaylists();var choose=new ComboBox{ItemsSource=lists.Select(x=>x.Name).ToArray(),SelectedIndex=lists.Count>0?0:-1,MinWidth=300};var create=new TextBox{ToolTip="新建列表名称"};var panel=Stack(T("选择已有播放列表",13),choose,T("或新建列表",13),create);if(ShowDialog("加入播放列表",panel,true)){var name=create.Text.Trim();if(name.Length>0)_store.SavePlaylist(new(Guid.NewGuid().ToString("N"),name,tracks.Select(x=>x.Id).ToArray()));else if(choose.SelectedIndex>=0){var list=lists[choose.SelectedIndex];_store.SavePlaylist(list with{TrackIds=list.TrackIds.Concat(tracks.Select(x=>x.Id)).ToArray()});}Notify("播放列表已保存。");}return Task.CompletedTask;}
    bool ShowDialog(string title,UIElement content,bool confirm=false,string? confirmText=null){var dialog=StyledWindow(title);var cancel=Action(confirm?"取消":"关闭",()=>{dialog.DialogResult=!confirm;return Task.CompletedTask;});if(confirm){var accept=Action(confirmText??"保存",()=>{dialog.DialogResult=true;return Task.CompletedTask;},null,true);dialog.Content=DialogFrame(dialog,title,content,cancel,accept);}else dialog.Content=DialogFrame(dialog,title,content,cancel);return dialog.ShowDialog()==true;}
    string? Prompt(string title,string value=""){var text=new TextBox{Text=value,MaxLength=200};return ShowDialog(title,text,true)?text.Text.Trim():null;}
    Activity StartActivity(string title,string detail){var activity=new Activity{Title=title,Detail=detail};_activities.Insert(0,activity);SaveActivities();return activity;}
    void SaveActivities()=>_store.SetPreference("activities",JsonSerializer.Serialize(_activities.Take(40)));
    void Transfers(){var panel=Stack(T("导入、同步与恢复记录",20));if(_downloads.Count>0)panel.Children.Add(Action("取消播客下载",()=>{foreach(var operation in _downloads.Values)operation.Cancel();return Task.CompletedTask;}));if(_scan!=null)panel.Children.Add(Action("取消导入",()=>{_scan.Cancel();return Task.CompletedTask;}));foreach(var directory in new[]{"transactions","file-transactions"}){var root=Path.Combine(_store.DataDirectory,directory);if(!Directory.Exists(root))continue;foreach(var path in Directory.EnumerateFiles(root,"journal.json",SearchOption.AllDirectories)){using var json=JsonDocument.Parse(File.ReadAllText(path));var phase=json.RootElement.GetProperty("Phase").GetString();var id=json.RootElement.GetProperty("DeviceId").GetString();if(phase is "Complete" or "RolledBack")continue;panel.Children.Add(Row(T("未完成任务 · "+phase,14),Action("校验并回滚",async()=>{if(_device==null||_device.DeviceId!=id)throw new IOException("请先连接并选择日志对应的 iPod。");if(MessageBox.Show(this,"检查外部更改后回滚此任务？如果发现无法确认的变化，将保留日志并停止。","恢复未完成任务",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return;if(directory=="transactions")await Task.Run(()=>new DeviceSync(_store.DataDirectory).RecoverAsync(_device,path,_lifetime.Token));else await Task.Run(()=>DeviceFileTransaction.RecoverAsync(path,_lifetime.Token));await Discover(true);Transfers();})));}}
        foreach(var activity in _activities){var entry=Stack(T(activity.Title+" · "+activity.State,17),T(activity.Detail,12,true),T(activity.Time.ToString("yyyy-MM-dd HH:mm"),11,true));entry.Margin=new(0,16,0,20);panel.Children.Add(entry);}if(_activities.Count==0)panel.Children.Add(T("还没有任务。导入、同步或备份后会显示记录。",13,true));_page.Content=new ScrollViewer{Content=panel};}
    string _settingsTab="常规";
    void Settings()
    {
        foreach(var label in new[]{"常规","资料库","设备","转换","备份与缓存","网络与日志","关于"}){var button=Action(label,()=>{_settingsTab=label;Navigate("设置");return Task.CompletedTask;});button.Margin=new(0,0,6,0);if(label==_settingsTab)button.Background=B("Selection");_tabs.Children.Add(button);}
        var panel=Stack();panel.MaxWidth=920;panel.HorizontalAlignment=HorizontalAlignment.Left;
        switch(_settingsTab){
            case "常规":panel.Children.Add(T("外观",22));panel.Children.Add(Action(_dark?"切换为浅色":"切换为深色",()=>{_dark=!_dark;_store.SetPreference("theme",_dark?"dark":"light");ApplyTheme();Navigate("设置");return Task.CompletedTask;}));LanguageSettings(panel);break;
            case "资料库":panel.Children.Add(T("资料库",22));panel.Children.Add(T(_store.DataDirectory,12,true));panel.Children.Add(Action("打开数据目录",()=>{Process.Start(new ProcessStartInfo(_store.DataDirectory){UseShellExecute=true});return Task.CompletedTask;},"folder"));SourceSettings(panel);break;
            case "设备":panel.Children.Add(T("设备支持",22));panel.Children.Add(T("Nano 4 · HASH58 · 数据库版本 115",17));panel.Children.Add(T("音乐、封面、播放列表、Podcast、视频、照片与备忘录使用真实设备格式写入。提交前备份并复读校验；固件播放和显示仍待实机验收。",13,true));if(_device!=null){panel.Children.Add(T(_device.Name+" · "+_device.Model,15));panel.Children.Add(Action("打开设备",()=>Go("设备"),"usb",true));var key="statistics-enabled:"+_device.DeviceId;var enabled=new CheckBox{Content="回传此设备播放统计至电脑索引",IsChecked=_store.GetPreference(key,"true")=="true"};enabled.Click+=(_,_)=>_store.SetPreference(key,enabled.IsChecked==true?"true":"false");panel.Children.Add(enabled);}break;
            case "转换":panel.Children.Add(T("Nano 4 转码预设",22));panel.Children.Add(T("音频 AAC-LC · 160 kbps · 44.1 kHz · 立体声\n视频 H.264 Baseline Level 3.0 · 最多 640×480 / 30 fps · AAC-LC 128 kbps\n兼容内容直接复制；可无损重封装的内容优先 remux。",13,true));ConversionSettings(panel);break;
            case "备份与缓存":BackupSettings(panel);break;
            case "网络与日志":panel.Children.Add(T("网络与隐私",22));panel.Children.Add(T("音乐与设备索引保存在电脑。无遥测；只有 RSS 和你手动指定的封面下载会联网。",13,true));NetworkSettings(panel);break;
            default:About();return;
        }
        foreach(var element in panel.Children.OfType<FrameworkElement>()){element.Margin=new(0,0,0,16);if(element is Button)element.HorizontalAlignment=HorizontalAlignment.Left;}
        _page.Content=new ScrollViewer{Content=panel};
    }
    void Photos(){var panel=Stack(T("电脑图片",22),T("浏览电脑图片，或打开 iPod 照片资料库。",13,true),Action("选择图片文件夹",()=>{var picker=new OpenFolderDialog{Title="选择图片文件夹"};if(picker.ShowDialog(this)==true){_store.SetPreference("photos-folder",picker.FolderName);Photos();}return Task.CompletedTask;},"folder",true));panel.Children.Add(Action("iPod 照片与相册",()=>{DevicePhotos();return Task.CompletedTask;},"usb",true));var folder=_store.GetPreference("photos-folder");if(Directory.Exists(folder)){var wrap=new WrapPanel();foreach(var file in Directory.EnumerateFiles(folder).Where(x=>new[]{".jpg",".jpeg",".png",".webp"}.Contains(Path.GetExtension(x).ToLowerInvariant())).Take(200)){var b=Action(Path.GetFileName(file),()=>{Process.Start(new ProcessStartInfo(file){UseShellExecute=true});return Task.CompletedTask;});b.Content=Stack(ImageCover(file,150),T(Path.GetFileName(file),11,true));b.Margin=new(0,16,20,0);wrap.Children.Add(b);}panel.Children.Add(wrap);}_page.Content=new ScrollViewer{Content=panel};}
}
public sealed class NanoDrawing : FrameworkElement
{
    protected override void OnRender(DrawingContext c){var left=(ActualWidth-130)/2;var alloy=new LinearGradientBrush(Color.FromRgb(232,234,238),Color.FromRgb(173,181,192),0);var body=new Rect(left,5,130,285);c.DrawRoundedRectangle(alloy,new Pen(Brushes.Silver,1),body,15,15);c.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(27,32,41)),null,new Rect(left+9,18,112,125),5,5);var text=new FormattedText("♫",System.Globalization.CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface(new FontFamily("MiSans"),FontStyles.Normal,FontWeights.SemiBold,FontStretches.Normal),55,new SolidColorBrush(Color.FromRgb(245,91,107)),1);c.DrawText(text,new Point(left+42,52));c.DrawEllipse(Brushes.WhiteSmoke,null,new Point(left+65,217),48,48);c.DrawEllipse(alloy,new Pen(Brushes.Silver,.5),new Point(left+65,217),18,18);var menu=new FormattedText("MENU",System.Globalization.CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface(new FontFamily("MiSans"),FontStyles.Normal,FontWeights.SemiBold,FontStretches.Normal),7,Brushes.Gray,1);c.DrawText(menu,new Point(left+55,180));}
}

