using System.IO;
using System.Security.Cryptography;
using System.Windows;
using iTunesPod.Core;
using iTunesPod.Infrastructure;
using Microsoft.Win32;
namespace iTunesPod.App;
public sealed partial class MainWindow
{
    async Task DeleteSourceFiles(){var tracks=Selected();if(tracks.Length==0)return;if(MessageBox.Show(this,$"删除 {tracks.Length} 个电脑源文件？将先保存完整文件备份；设备内容与索引记录保留，索引会标记来源失效。","删除电脑源文件",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return;var folder=Path.Combine(_store.DataDirectory,"source-deletions",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);foreach(var track in tracks){if(track.Id.StartsWith("device:")||Directory.Exists(Path.Combine(Path.GetPathRoot(track.Path)!,"iPod_Control")))throw new IOException("此操作不能删除设备文件。");if(!File.Exists(track.Path))continue;_player.Stop();var target=Path.Combine(folder,track.Id+Path.GetExtension(track.Path));await DeviceBackupCopy(track.Path,target);await using var copied=File.OpenRead(target);var hash=Convert.ToHexString(await SHA256.HashDataAsync(copied));await using(var original=File.OpenRead(track.Path))if(Convert.ToHexString(await SHA256.HashDataAsync(original))!=hash)throw new IOException("来源发生改变，已停止删除。");File.Delete(track.Path);}Notify("源文件删除完成，备份："+folder);Navigate(_route);}
    async Task CommitStatistics(){if(TargetDevice==null)return;var progress=new Progress<string>(s=>_status.Text=s);var sync=new DeviceSync(_store.DataDirectory);var plan=await Task.Run(()=>sync.PrepareAsync(TargetDevice,[],progress,_lifetime.Token));if(plan.Deletes.Count==0){Notify("没有待回写的设备播放统计。");return;}if(MessageBox.Show(this,"将设备播放次数、跳过次数、评分和播放位置合并到数据库，并在验证后清理已处理统计文件？","统计回写",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return;await Task.Run(()=>sync.CommitAsync(plan,progress,_lifetime.Token));await Discover(true);Notify("统计回写完成。");}
    void ImportStatistics(DeviceSession session){if(_store.GetPreference("statistics-enabled:"+session.DeviceId,"true")!="true")return;var links=DeviceMediaIndex.LoadLinks(session.DeviceId,_store.DataDirectory);if(links.Count==0)return;IReadOnlyList<Track> statistics;try{statistics=DeviceStatistics.Peek(session);}catch(InvalidDataException){return;}catch(IOException){return;}var byId=statistics.ToDictionary(x=>uint.Parse(x.Id[7..]));var pc=_store.LoadTracks().ToDictionary(x=>x.Id);var changed=new List<Track>();var baselines=new Dictionary<string,string>();foreach(var link in links){if(!byId.TryGetValue(link.DeviceTrackId,out var device)||!pc.TryGetValue(link.SourceId,out var source))continue;var key="statistics:"+session.DeviceId+":"+link.DeviceTrackId;var baselineText=_store.GetPreference(key);var total=device.PlayCount;var baseline=uint.TryParse(baselineText,out var value)?value:total;var count=baselineText.Length==0?Math.Max(source.PlayCount,total):checked(source.PlayCount+(total>baseline?total-baseline:0));changed.Add(source with{PlayCount=count,SkipCount=device.SkipCount,BookmarkMilliseconds=device.BookmarkMilliseconds,Rating=device.Rating,LastPlayedUtc=device.LastPlayedUtc});baselines[key]=total.ToString();}_store.SaveTracksAndPreferences(changed,baselines);_tracks=_store.LoadTracks();var played=changed.Where(x=>x.IsPodcast&&x.PlayCount>0).Select(x=>x.EpisodeId).ToHashSet();if(played.Count>0)SaveEpisodes(Episodes().Select(x=>played.Contains(x.Id)?x with{Played=true}:x));}
    async Task<PreparedSync> AttachCovers(PreparedSync plan)
    {
        var existing=plan.ExistingMatches.Select(pair=>new DeviceTrackWrite(pair.Value,_tracks.First(x=>x.Id==pair.Key),""));
        var groups=plan.Media.Select(x=>x.Write).Concat(existing).Where(x=>File.Exists(x.Track.CoverPath)).GroupBy(x=>x.Track.AlbumKey).ToArray();if(groups.Length==0)return plan;
        var path=DeviceAccess.SafePath(plan.Device.Root,"iPod_Control/Artwork/ArtworkDB");var original=File.Exists(path)?await File.ReadAllBytesAsync(path):null;var art=new NativeImageDatabase(original);
        var database=await File.ReadAllBytesAsync(plan.DatabasePath);var persistent=DeviceDatabaseEdits.PersistentIds(database);var oldLinks=DeviceDatabaseEdits.ArtworkIds(database);var oldImages=art.Images().ToDictionary(x=>x.Id);
        var links=new Dictionary<uint,ArtworkLink>();var assets=new List<PreparedAsset>(plan.Assets);
        bool Matches(DeviceTrackWrite entry,IReadOnlyList<ImagePayload> payloads){if(!oldLinks.TryGetValue(entry.Id,out var id)||!oldImages.TryGetValue(id,out var image))return false;foreach(var payload in payloads){var reference=image.Images.FirstOrDefault(x=>x.Format==payload.Format);if(reference==null||reference.Size<payload.Pixels.Length)return false;var file=DeviceAccess.SafePath(plan.Device.Root,"iPod_Control/Artwork/"+reference.FileName.TrimStart(':').Replace(':','/'));if(!File.Exists(file))return false;using var stream=File.OpenRead(file);if(reference.Offset+payload.Pixels.Length>stream.Length)return false;stream.Position=reference.Offset;var bytes=new byte[payload.Pixels.Length];stream.ReadExactly(bytes);if(!bytes.AsSpan().SequenceEqual(payload.Pixels))return false;}return true;}
        foreach(var group in groups){var first=group.First();var cover=first.Track.CoverPath!;var payloads=NativeImages.Encode(cover,false);if(group.All(x=>Matches(x,payloads)))continue;_status.Text="生成设备封面："+first.Track.Album;
            var result=art.AddImage(persistent[first.Id],payloads,"iPod_Control/Artwork");foreach(var change in result.Files){var file=DeviceAccess.SafePath(plan.WorkDirectory,change.RelativePath);Directory.CreateDirectory(Path.GetDirectoryName(file)!);await File.WriteAllBytesAsync(file,change.Content!);assets.Add(new(change.RelativePath,file,Convert.ToHexString(SHA256.HashData(change.Content!))));}foreach(var entry in group)links[entry.Id]=new(result.Id,checked((int)new FileInfo(cover).Length));
        }
        if(links.Count==0)return plan;var artwork=art.Build();var artworkHost=Path.Combine(plan.WorkDirectory,"ArtworkDB");await File.WriteAllBytesAsync(artworkHost,artwork);assets.Add(new("iPod_Control/Artwork/ArtworkDB",artworkHost,Convert.ToHexString(SHA256.HashData(artwork)),original==null?null:Convert.ToHexString(SHA256.HashData(original))));database=DeviceDatabaseEdits.Apply(database,plan.Device.SigningIdentity,covers:links);await File.WriteAllBytesAsync(plan.DatabasePath,database);
        return DeviceSync.Seal(plan with{DatabaseHash=Convert.ToHexString(SHA256.HashData(database)),Assets=assets,RequiredBytes=plan.RequiredBytes+assets.Sum(x=>new FileInfo(x.SourcePath).Length)});
    }
    IReadOnlyList<Track> ReadNativeCovers(DeviceSession session,IReadOnlyList<Track> tracks){var artPath=DeviceAccess.SafePath(session.Root,"iPod_Control/Artwork/ArtworkDB");if(!File.Exists(artPath))return tracks;var art=new NativeImageDatabase(File.ReadAllBytes(artPath));var images=art.Images().ToDictionary(x=>x.Id);var links=DeviceDatabaseEdits.ArtworkIds(File.ReadAllBytes(DeviceAccess.SafePath(session.Root,session.DatabaseFile)));var folder=Path.Combine(_store.DataDirectory,"native-covers",session.Generation);Directory.CreateDirectory(folder);var output=new List<Track>();foreach(var track in tracks){if(!links.TryGetValue(uint.Parse(track.Id[7..]),out var id)){output.Add(track);continue;}if(id==0){output.Add(track with{CoverPath=null});continue;}if(!images.TryGetValue(id,out var image)){output.Add(track);continue;}var reference=image.Images.FirstOrDefault(x=>x.Format==1071)??image.Images.FirstOrDefault();if(reference==null){output.Add(track);continue;}var cover=Path.Combine(folder,id+".png");try{if(!File.Exists(cover))NativeImages.SavePng(NativeImages.Decode(session.Root,reference,false),cover);output.Add(track with{CoverPath=cover});}catch(IOException){output.Add(track);}}return output;}
    async Task SaveDeviceTrack(Track track){var bytes=await File.ReadAllBytesAsync(DeviceAccess.SafePath(TargetDevice!.Root,TargetDevice.DatabaseFile));var result=DeviceDatabaseEdits.Apply(bytes,TargetDevice.SigningIdentity,updates:new Dictionary<uint,Track>{{uint.Parse(track.Id[7..]),track}});await CommitFiles([new(TargetDevice.DatabaseFile,result)],"编辑设备歌曲信息");await Discover(true);}
    async Task ChangeCover(Track track,bool device,bool remove=false,string? suppliedSource=null){string? source=suppliedSource;if(!remove&&source==null){var picker=new OpenFileDialog{Title="选择专辑封面",Filter="封面|*.jpg;*.jpeg;*.png"};if(picker.ShowDialog(this)!=true)return;source=picker.FileName;}if(!device){var folder=Path.Combine(_store.DataDirectory,"user-covers");Directory.CreateDirectory(folder);string? target=null;if(source!=null){await using var f=File.OpenRead(source);var hash=Convert.ToHexString(await SHA256.HashDataAsync(f));target=Path.Combine(folder,hash+Path.GetExtension(source));if(!File.Exists(target))File.Copy(source,target);}var albums=_tracks.Where(x=>x.AlbumKey==track.AlbumKey).Select(x=>x with{CoverPath=target}).ToArray();_store.SaveTracks(albums);foreach(var albumTrack in albums)_store.SetPreference("cover-override:"+albumTrack.Id,target??"none");_tracks=_store.LoadTracks();Inspect(_tracks.First(x=>x.Id==track.Id),false);return;}
        var databasePath=DeviceAccess.SafePath(TargetDevice!.Root,TargetDevice.DatabaseFile);var database=await File.ReadAllBytesAsync(databasePath);var album=TargetDevice.Tracks.Where(x=>x.AlbumKey==track.AlbumKey).ToArray();var links=new Dictionary<uint,ArtworkLink>();var changes=new List<FileChange>();if(source==null){foreach(var song in album)links.Add(uint.Parse(song.Id[7..]),new(0,0));}else{var path=DeviceAccess.SafePath(TargetDevice.Root,"iPod_Control/Artwork/ArtworkDB");var art=new NativeImageDatabase(File.Exists(path)?await File.ReadAllBytesAsync(path):null);var persistent=DeviceDatabaseEdits.PersistentIds(database);var image=art.AddImage(persistent[uint.Parse(track.Id[7..])],NativeImages.Encode(source,false),"iPod_Control/Artwork");changes.AddRange(image.Files);changes.Add(art.Change("iPod_Control/Artwork/ArtworkDB"));foreach(var song in album)links.Add(uint.Parse(song.Id[7..]),new(image.Id,checked((int)new FileInfo(source).Length)));}
        changes.Add(new(TargetDevice.DatabaseFile,DeviceDatabaseEdits.Apply(database,TargetDevice.SigningIdentity,covers:links)));await CommitFiles(changes,remove?"移除设备专辑封面":"替换设备专辑封面");await Discover(true);
    }
    async Task DeleteDeviceTracks(){var selected=Selected();if(selected.Length==0)return;if(MessageBox.Show(this,$"从 iPod 删除 {selected.Length} 首歌曲及对应媒体文件？电脑来源文件保留。提交前会创建完整设备备份。","删除设备歌曲",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return;SavePlaybackPosition();_player.Stop();var data=await File.ReadAllBytesAsync(DeviceAccess.SafePath(TargetDevice!.Root,TargetDevice.DatabaseFile));var countPath=DeviceAccess.SafePath(TargetDevice.Root,"iPod_Control/iTunes/Play Counts");if(File.Exists(countPath))data=DeviceStatistics.Fold(data,await File.ReadAllBytesAsync(countPath),TargetDevice.SigningIdentity);var ids=selected.Select(x=>uint.Parse(x.Id[7..])).ToHashSet();var changed=DeviceDatabaseEdits.Apply(data,TargetDevice.SigningIdentity,deleteTracks:ids);var changes=new List<FileChange>();if(File.Exists(countPath))changes.Add(new("iPod_Control/iTunes/Play Counts",null));changes.Add(new(TargetDevice.DatabaseFile,changed));foreach(var track in selected.Where(x=>File.Exists(x.Path)))changes.Add(new(Path.GetRelativePath(TargetDevice.Root,track.Path),null));await CommitFiles(changes,"删除设备歌曲");await Discover(true);}
    async Task WriteSourceTags(Track track){if(track.Path.Split(new[]{(char)92,(char)47}).Any(x=>x.Equals("iPod_Control",StringComparison.OrdinalIgnoreCase)))throw new IOException("设备文件标签需要通过设备同步事务修改。");if(MessageBox.Show(this,"将电脑索引信息写入原音频文件？写入前会保留原文件备份。","更新源文件标签",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return;SavePlaybackPosition();_player.Stop();var folder=Path.Combine(_store.DataDirectory,"source-backups",DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N")[..8]);Directory.CreateDirectory(folder);var backup=Path.Combine(folder,Path.GetFileName(track.Path));await DeviceBackupCopy(track.Path,backup);try{using(var file=TagLib.File.Create(track.Path)){file.Tag.Title=track.Title;file.Tag.Performers=[track.Artist];file.Tag.Album=track.Album;file.Tag.AlbumArtists=[track.AlbumArtist];file.Tag.Track=track.Number;file.Tag.Disc=track.Disc;file.Tag.Year=track.Year;file.Tag.Genres=[track.Genre];file.Tag.Composers=[track.Composer];if(file.GetTag(TagLib.TagTypes.Id3v2) is TagLib.Id3v2.Tag id3)id3.IsCompilation=track.Compilation;if(file.GetTag(TagLib.TagTypes.Apple) is TagLib.Mpeg4.AppleTag apple)apple.IsCompilation=track.Compilation;file.Save();}await using var updated=File.OpenRead(track.Path);var hash=Convert.ToHexString(await SHA256.HashDataAsync(updated));_store.SaveTracks([track with{Hash=hash,Bytes=updated.Length}]);_tracks=_store.LoadTracks();Notify("标签已更新，原文件备份："+backup);}catch{File.Copy(backup,track.Path,true);throw;}}
    static async Task DeviceBackupCopy(string source,string target){await using var input=File.OpenRead(source);await using var output=new FileStream(target,FileMode.CreateNew,FileAccess.Write);await input.CopyToAsync(output);output.Flush(true);}
}
