using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using iTunesPod.Core;
using iTunesPod.Infrastructure;
using Microsoft.Win32;
namespace iTunesPod.App;
public sealed partial class MainWindow
{
    IEnumerable<Track> DiscoveryTracks()=>_tracks.Count>0?_tracks.Where(x=>!x.IsVideo):_device?.Tracks??[];
    void Home(){
        _title.Text=UiLanguage.Label(_route=="主页"?"主页":"新发现");_subtitle.Text=_tracks.Count>0?"从你的收藏中，发现下一首喜欢的音乐。":_device!=null?"来自 "+_device.Name+" 的音乐收藏":"导入本地音乐，发现你的专辑与播放列表。";
        var source=DiscoveryTracks().ToArray();var fromDevice=_tracks.Count==0&&_device!=null;Task BrowseAll(string tab){if(fromDevice){_deviceTab=tab;Navigate("设备");return Task.CompletedTask;}return Go(tab=="歌曲"?"歌曲":"专辑");}var panel=Stack();
        if(source.Length==0){_page.Content=Empty("让音乐成为你的日常","导入音乐文件或文件夹。连接 iPod 后，歌曲、专辑与播放列表会出现在这里。",Action("导入音乐",PickFiles,"add",true),Action("选择文件夹",PickFolder,"folder"));return;}
        var featured=source.Where(x=>x.CoverPath!=null).GroupBy(x=>x.AlbumKey).Take(2).ToArray();if(featured.Length==0)featured=source.GroupBy(x=>x.AlbumKey).Take(2).ToArray();
        var heroes=Grid("*,*","*");for(var i=0;i<featured.Length;i++){var album=featured[i].ToArray();var first=album[0];var eyebrow=T(i==0?"重温你的收藏":"精选专辑",11,true);eyebrow.FontWeight=FontWeights.SemiBold;var heading=T(first.Album,21);heading.FontWeight=FontWeights.SemiBold;heading.MaxHeight=55;heading.TextTrimming=TextTrimming.CharacterEllipsis;
            var card=new Button{HorizontalContentAlignment=HorizontalAlignment.Stretch,Padding=new(0),Margin=new(i==0?0:12,0,i==0?12:0,0)};var coverGrid=Grid("*","*");coverGrid.Height=250;coverGrid.Background=B("Panel");
            if(first.CoverPath!=null){var image=ImageCover(first.CoverPath,400);image.HorizontalAlignment=HorizontalAlignment.Stretch;image.Width=double.NaN;image.Height=250;coverGrid.Children.Add(image);}else coverGrid.Children.Add(Glyph("album",60,B("Accent")));
            var body=Stack(eyebrow,heading,T(first.AlbumArtist,13,true),coverGrid);eyebrow.Margin=new(0,0,0,5);heading.Margin=new(0,0,0,4);((FrameworkElement)body.Children[2]).Margin=new(0,0,0,12);card.Content=body;card.Click+=(_,_)=>AlbumDetail(album);Col(card,i);heroes.Children.Add(card);}
        panel.Children.Add(heroes);panel.Children.Add(SectionHeading("值得再听一次",()=>BrowseAll("专辑")));panel.Children.Add(AlbumRail(source,12));panel.Children.Add(SectionHeading("你的音乐精选",()=>BrowseAll("歌曲")));var songs=Grid("*,*,*","*");for(var i=0;i<3;i++){var column=Stack();foreach(var track in source.Skip(i*4).Take(4)){var row=Grid("52,*,32","*");row.Margin=new(0,0,14,12);row.Children.Add(Cover(track,42));var names=Stack(T(track.Title,13),T(track.Artist,11,true));Col(names,1);row.Children.Add(names);var play=IconButton("play","播放 "+track.Title,()=>Play(track,source));Col(play,2);row.Children.Add(play);column.Children.Add(row);}Col(column,i);songs.Children.Add(column);}panel.Children.Add(songs);_page.Content=new ScrollViewer{Content=panel};
    }
    FrameworkElement SectionHeading(string label,Func<Task> more){var row=Grid("*,Auto","*");row.Margin=new(0,32,0,16);var title=T(label,22);title.FontWeight=FontWeights.Bold;row.Children.Add(title);var all=Action("查看全部 ›",more);((TextBlock)all.Content).Foreground=B("Accent");Col(all,1);row.Children.Add(all);return row;}
    FrameworkElement AlbumTile(Track[] album,double size=170){var first=album[0];var name=T(first.Album,13);name.TextTrimming=TextTrimming.CharacterEllipsis;name.TextWrapping=TextWrapping.NoWrap;name.Margin=new(0,8,0,3);var artist=T(first.AlbumArtist,12,true);artist.TextWrapping=TextWrapping.NoWrap;artist.TextTrimming=TextTrimming.CharacterEllipsis;var tile=Stack(Cover(first,size),name,artist);var b=new Button{Content=tile,Width=size,Padding=new(0),Margin=new(0,0,20,20),HorizontalContentAlignment=HorizontalAlignment.Stretch};b.Click+=(_,_)=>AlbumDetail(album);return b;}
    FrameworkElement AlbumRail(IEnumerable<Track> source,int limit){var row=new StackPanel{Orientation=Orientation.Horizontal};foreach(var album in source.GroupBy(x=>x.AlbumKey).Take(limit))row.Children.Add(AlbumTile(album.ToArray(),170));return new ScrollViewer{Content=row,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto,VerticalScrollBarVisibility=ScrollBarVisibility.Disabled};}
    void Albums(IEnumerable<Track> source){var tracks=source.ToArray();_subtitle.Text=$"{tracks.GroupBy(x=>x.AlbumKey).Count()} 张专辑";var container=new ContentControl();void Show(string search){var wrap=new WrapPanel();var albums=tracks.Where(x=>(x.Album+" "+x.AlbumArtist).Contains(search,StringComparison.OrdinalIgnoreCase)).GroupBy(x=>x.AlbumKey);if(_route!="最近添加")albums=albums.OrderBy(x=>x.First().Album);else albums=albums.OrderByDescending(x=>x.Max(t=>t.AddedUtc));foreach(var album in albums)wrap.Children.Add(AlbumTile(album.ToArray(),174));container.Content=new ScrollViewer{Content=wrap};}_filter=Show;Show("");_page.Content=tracks.Length==0?Empty("你的专辑资料库","导入收藏后，封面与曲目会自动整理。",Action("导入音乐",PickFiles,"add",true)):container;}
    void Music(IEnumerable<Track> source,bool device=false){var tracks=source.ToArray();_queue=tracks.Where(x=>!x.IsVideo).ToArray();var g=Grid("*","Auto,*,Auto");var actions=Row(Action("播放",async()=>{var track=_table?.SelectedItem as Track??tracks.FirstOrDefault(x=>File.Exists(x.Path));if(track!=null)await Play(track,tracks);},"play",true),Action("随机播放",Shuffle,"shuffle"),Action("歌曲信息",()=>{if(_table?.SelectedItem is Track track)Inspect(track,device);return Task.CompletedTask;},"info"));actions.Margin=new(0,0,0,16);
        if(device){actions.Children.Add(Action("导出选中",()=>Export(Selected()),"export"));actions.Children.Add(Action("删除设备歌曲",DeleteDeviceTracks));}else{actions.Children.Add(Action("加入播放列表",()=>AddToPlaylist(Selected()),"list"));actions.Children.Add(Action("加入 iPod",()=>{AddDraft(Selected());return Task.CompletedTask;},"usb"));actions.Children.Add(Action("删除电脑源文件",DeleteSourceFiles));}g.Children.Add(actions);
        var table=new DataGrid{ItemsSource=tracks,SelectionMode=DataGridSelectionMode.Extended,SelectionUnit=DataGridSelectionUnit.FullRow};_table=table;foreach(var (title,property,width) in new[]{("标题","Title",3d),("艺术家","Artist",1.8),("专辑","Album",2d),("时长","Duration",.65),("来源","Status",1d)})table.Columns.Add(new DataGridTextColumn{Header=title,Binding=new Binding(property),Width=new(width,DataGridLengthUnitType.Star)});
        table.MouseDoubleClick+=(_,_)=>{if(table.SelectedItem is Track track)Inspect(track,device);};table.SelectionChanged+=(_,_)=>{if(_details.Visibility==Visibility.Visible&&table.SelectedItem is Track track)Inspect(track,device);};table.PreviewKeyDown+=async(_,e)=>{if(e.Key==Key.Enter&&table.SelectedItem is Track track){await Guard(()=>Play(track,tracks));e.Handled=true;}};
        var context=new ContextMenu();void Menu(string name,Func<Task> action){var item=new MenuItem{Header=name};item.Click+=async(_,_)=>await Guard(action);context.Items.Add(item);}Menu("播放",async()=>{if(table.SelectedItem is Track track)await Play(track,tracks);});Menu("歌曲信息",()=>{if(table.SelectedItem is Track track)Inspect(track,device);return Task.CompletedTask;});Menu("导出到电脑",()=>Export(Selected()));if(!device)Menu("从电脑索引移除（保留文件）",RemoveIndex);table.ContextMenu=context;At(table,1);g.Children.Add(table);
        var summary=T($"{tracks.Length} 首歌曲 · {Bytes(tracks.Where(x=>File.Exists(x.Path)).Sum(x=>x.Bytes))} · {tracks.Count(x=>!File.Exists(x.Path))} 条来源失效",11,true);summary.Margin=new(0,12,0,0);At(summary,2);g.Children.Add(summary);_filter=q=>{var result=tracks.Where(x=>(x.Title+" "+x.Artist+" "+x.Album).Contains(q,StringComparison.OrdinalIgnoreCase)).ToArray();table.ItemsSource=result;summary.Text=$"显示 {result.Length} / {tracks.Length} 首 · Enter 播放 · 双击查看详情";};
        _page.Content=tracks.Length==0?Empty("资料库中还没有内容","导入本地媒体，或者打开已连接的 iPod。",Action("导入音乐",PickFiles,"add",true),Action("导入视频",()=>PickFiles(true),"video")):g;
    }
    Track[] Selected()=>_table?.SelectedItems.Cast<Track>().ToArray()??[];
    void AlbumDetail(Track[] album){HideDetails();if(album.Length==0)return;var first=album[0];_title.Text=first.Album;_subtitle.Text=first.AlbumArtist;Music(album.OrderBy(x=>x.Disc).ThenBy(x=>x.Number),first.Id.StartsWith("device:"));var table=(UIElement)_page.Content;_page.Content=null;var layout=Grid("*","Auto,*");var header=Grid("220,*","*");header.Margin=new(0,0,0,28);header.Children.Add(Cover(first,196));var info=Stack(T(first.AlbumArtist,17),T($"{album.Length} 首 · {album.Sum(x=>x.Seconds)/60:0} 分钟 · {first.Format}",13,true),Row(Action("播放专辑",()=>Play(album.First(x=>File.Exists(x.Path)),album),"play",true),Action("导出专辑",()=>Export(album),"export")));info.VerticalAlignment=VerticalAlignment.Center;foreach(var e in info.Children.OfType<FrameworkElement>())e.Margin=new(0,0,0,14);Col(info,1);header.Children.Add(info);layout.Children.Add(header);At(table,1);layout.Children.Add(table);_page.Content=layout;}
    void Artists(IEnumerable<Track> source){var tracks=source.Where(x=>!x.IsVideo).ToArray();var wrap=new WrapPanel();foreach(var group in tracks.GroupBy(x=>x.Artist).OrderBy(x=>x.Key)){var avatar=new Border{Width=150,Height=150,CornerRadius=new(75),Background=B("Panel"),Child=Glyph("person",48,B("Muted"))};var text=T(group.Key,15);text.TextAlignment=TextAlignment.Center;var info=T(group.Count()+" 首歌曲",12,true);info.TextAlignment=TextAlignment.Center;var b=new Button{Width=174,Padding=new(0),Margin=new(0,0,24,24),Content=Stack(avatar,text,info)};b.Click+=(_,_)=>{_title.Text=group.Key;Albums(group);};wrap.Children.Add(b);}_page.Content=tracks.Length==0?Empty("艺术家资料库","导入音乐后，艺术家会自动整理。",Action("导入音乐",PickFiles,"add",true)):new ScrollViewer{Content=wrap};}
    void Inspect(Track track,bool device)
    {
        _content.ColumnDefinitions[1].Width=new(280);_details.Visibility=Visibility.Visible;
        var fields=Stack(Row(T("歌曲信息",17),IconButton("close","关闭详情",()=>{HideDetails();return Task.CompletedTask;})),Cover(track,230),T(track.Title,21),T(track.Artist,13,true));
        var edits=new Dictionary<string,TextBox>();
        foreach(var (label,value) in new[]{("标题",track.Title),("艺术家",track.Artist),("专辑",track.Album),("专辑艺术家",track.AlbumArtist),("流派",track.Genre),("作曲家",track.Composer),("年份",track.Year.ToString()),("碟号",track.Disc.ToString()),("曲目号",track.Number.ToString()),("评分（0—5）",track.Rating.ToString())}){fields.Children.Add(T(label,11,true));var input=new TextBox{Text=value};edits[label]=input;fields.Children.Add(input);}
        var mediaKind=new ComboBox{ItemsSource=new[]{"音乐","电影","音乐视频","电视节目","Podcast"},SelectedIndex=track.IsPodcast?4:(track.MediaType&64)!=0?3:(track.MediaType&32)!=0?2:track.IsVideo?1:0};if(track.IsVideo){fields.Children.Add(T("视频分类",11,true));fields.Children.Add(mediaKind);}var compilation=new CheckBox{Content="合辑（Various Artists）",IsChecked=track.Compilation};fields.Children.Add(compilation);
        Track Edited(){uint Number(string label,uint max){if(!uint.TryParse(edits[label].Text,out var n)||n>max)throw new IOException(label+"超出有效范围。");return n;}if(string.IsNullOrWhiteSpace(edits["标题"].Text))throw new IOException("标题不能为空。");return track with{Title=edits["标题"].Text.Trim(),Artist=edits["艺术家"].Text.Trim(),Album=edits["专辑"].Text.Trim(),AlbumArtist=edits["专辑艺术家"].Text.Trim(),Genre=edits["流派"].Text.Trim(),Composer=edits["作曲家"].Text.Trim(),Year=Number("年份",9999),Disc=Number("碟号",65535),Number=Number("曲目号",65535),Rating=Number("评分（0—5）",5),Compilation=compilation.IsChecked==true,MediaType=track.IsVideo?mediaKind.SelectedIndex switch{2=>32u,3=>64u,4=>6u,_=>2u}:track.MediaType};}
        fields.Children.Add(T($"{track.Format} · {track.Duration} · {Bytes(track.Bytes)}\n{track.Bitrate} kbps · {track.SampleRate} Hz\n播放 {track.PlayCount} 次 · 跳过 {track.SkipCount} 次",12,true));fields.Children.Add(T(track.Path,11,true));
        fields.Children.Add(Action("播放",()=>Play(track),"play",true));fields.Children.Add(Row(Action("替换封面",()=>ChangeCover(track,device)),Action("移除封面",()=>ChangeCover(track,device,true))));
        fields.Children.Add(Action("从网络地址添加封面",()=>OnlineCover(track,device)));if(device)fields.Children.Add(Action("保存到设备",()=>SaveDeviceTrack(Edited()),"info",true));
        else{fields.Children.Add(Action("保存信息",async()=>{_store.SaveTracks([Edited()]);_tracks=await Task.Run(_store.LoadTracks);Notify("电脑索引信息已保存。");}));fields.Children.Add(Action("写入源文件标签",()=>WriteSourceTags(Edited())));}
        foreach(var e in fields.Children.OfType<FrameworkElement>())e.Margin=new(0,0,0,10);
        _details.Content=new Border{Margin=new(24,0,0,0),BorderBrush=B("Line"),BorderThickness=new(1,0,0,0),Padding=new(18,0,0,0),Child=new ScrollViewer{Content=fields}};
    }
    async Task PickFiles()=>await PickFiles(false);
    async Task PickFiles(bool video){var dialog=new OpenFileDialog{Title=video?"导入视频":"导入音乐",Multiselect=true,Filter=video?"视频|*.mp4;*.m4v;*.mov|所有文件|*.*":"音频|*.mp3;*.m4a;*.aac;*.flac;*.wav;*.ogg;*.aiff;*.wma|所有文件|*.*"};if(dialog.ShowDialog(this)==true)await Import(dialog.FileNames);}
    async Task PickFolder(){var dialog=new OpenFolderDialog{Title="选择音乐文件夹",Multiselect=true};if(dialog.ShowDialog(this)==true)await Import(dialog.FolderNames);}
    async Task Import(IEnumerable<string> sources){if(_scan!=null){Notify("已有导入任务正在执行。");return;}_scan=CancellationTokenSource.CreateLinkedTokenSource(_lifetime.Token);var activity=StartActivity("导入音乐","读取标签与封面");try{var progress=new Progress<string>(s=>_status.Text="正在导入："+s);var result=await Task.Run(()=>new LibraryScanner(_store).ImportAsync(sources,progress,_scan.Token));_tracks=await Task.Run(_store.LoadTracks);activity.State=result.Errors.Count==0?"已完成":"部分完成";activity.Detail=$"导入 {result.Tracks.Count} 首，重复 {result.Duplicates} 个\n"+string.Join("\n",result.Errors);Navigate(_route);Notify(activity.Detail);}catch(OperationCanceledException){activity.State="已取消";}catch(Exception ex){activity.State="失败";activity.Detail=ex.Message;throw;}finally{_scan.Dispose();_scan=null;SaveActivities();}}
    async Task Play(Track track,IEnumerable<Track>? queue=null){if(track.IsVideo){Process.Start(new ProcessStartInfo(track.Path){UseShellExecute=true});return;}if(queue!=null)_queue=queue.Where(x=>!x.IsVideo).ToArray();SavePlaybackPosition();await _player.PlayAsync(track);if(track.IsPodcast&&track.BookmarkMilliseconds>0)_player.Seek(track.BookmarkMilliseconds/1000d);UpdatePlayer();}
    async Task TogglePlayback(){if(_player.Current==null){var track=_table?.SelectedItem as Track??_queue.FirstOrDefault(x=>File.Exists(x.Path))??DiscoveryTracks().FirstOrDefault(x=>File.Exists(x.Path));if(track!=null)await Play(track);else Notify("请选择可播放的歌曲。");}else _player.Toggle();UpdatePlayer();}
    async Task Step(int offset){if(_queue.Count==0)return;var index=_queue.ToList().FindIndex(x=>x.Id==_player.Current?.Id);var next=(index+offset+_queue.Count)%_queue.Count;await Play(_queue[next]);}
    async Task Shuffle(){var available=(_queue.Count>0?_queue:DiscoveryTracks()).Where(x=>File.Exists(x.Path)&&!x.IsVideo).OrderBy(_=>Random.Shared.Next()).ToArray();if(available.Length>0)await Play(available[0],available);}
    void UpdatePlayer(){if(_closed)return;_nowTitle.Text=_player.Current?.Title??"iTunesPod";_nowArtist.Text=_player.Current?.Artist??"选择音乐开始播放";_nowArt.Content=Cover(_player.Current,46);_play.Content=Glyph(_player.IsPlaying?"pause":"play",25,B("Muted"));UpdateProgress();}
    void UpdateProgress(){_seek.Maximum=Math.Max(1,_player.TotalSeconds);if(!_seeking)_seek.Value=_player.PositionSeconds;_elapsed.Text=Time(_player.PositionSeconds);_duration.Text=Time(_player.TotalSeconds);}
    Task ShowQueue(){var list=new ListBox{ItemsSource=_queue.Select(x=>x.Artist+" — "+x.Title).ToArray()};list.MouseDoubleClick+=async(_,_)=>{if(list.SelectedIndex>=0)await Guard(()=>Play(_queue[list.SelectedIndex]));};ShowDialog("播放队列",list);return Task.CompletedTask;}
    async Task Export(IEnumerable<Track> source){var tracks=source.ToArray();if(tracks.Length==0){Notify("先选择歌曲。");return;}var picker=new OpenFolderDialog{Title="导出到电脑文件夹"};if(picker.ShowDialog(this)!=true)return;var target=Path.GetFullPath(picker.FolderName).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;if(_sessions.Values.Any(x=>target.StartsWith(Path.GetFullPath(x.Root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)))throw new IOException("请选择设备之外的电脑目录。");var activity=StartActivity("导出歌曲",target);var copied=0;try{foreach(var track in tracks){if(!File.Exists(track.Path))continue;var name=string.Concat((track.Artist+" - "+track.Title).Select(c=>Path.GetInvalidFileNameChars().Contains(c)?'_':c));name=name[..Math.Min(name.Length,140)].TrimEnd('.',' ');var extension=Path.GetExtension(track.Path);var path=Path.Combine(target,name+extension);for(var n=2;File.Exists(path);n++)path=Path.Combine(target,name+" ("+n+")"+extension);await using var input=File.OpenRead(track.Path);await using var output=new FileStream(path,FileMode.CreateNew,FileAccess.Write);await input.CopyToAsync(output,_lifetime.Token);copied++;}activity.State="已完成";activity.Detail=$"导出 {copied} 首，跳过失效来源 {tracks.Length-copied} 首";Notify(activity.Detail);}catch{activity.State="失败";throw;}finally{SaveActivities();}}
    Task RemoveIndex(){var ids=Selected().Select(x=>x.Id).ToArray();if(ids.Length>0&&MessageBox.Show(this,"从电脑索引移除选中歌曲？源文件保留。","移除歌曲",MessageBoxButton.OKCancel)==MessageBoxResult.OK){_store.RemoveFromIndex(ids);_tracks=_store.LoadTracks();Navigate(_route);}return Task.CompletedTask;}
}

