using System.IO;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using iTunesPod.Infrastructure;
namespace iTunesPod.App;
public static class NativeImages
{
    public static readonly (int Id,int Width,int Height)[] PhotoFormats=[(1024,320,240),(1066,64,64),(1079,80,80),(1083,240,320)];
    public static readonly (int Id,int Width,int Height)[] CoverFormats=[(1055,128,128),(1071,240,240),(1074,50,50),(1078,80,80)];
    public static IReadOnlyList<ImagePayload> Encode(string path,bool photo){using var stream=File.OpenRead(path);var decoder=BitmapDecoder.Create(stream,BitmapCreateOptions.PreservePixelFormat,BitmapCacheOption.OnLoad);BitmapSource image=decoder.Frames[0];if((long)image.PixelWidth*image.PixelHeight>50_000_000)throw new IOException("图片超过 5000 万像素。");var orientation=1;try{if(decoder.Frames[0].Metadata is BitmapMetadata m&&m.ContainsQuery("/app1/ifd/{ushort=274}"))orientation=Convert.ToInt32(m.GetQuery("/app1/ifd/{ushort=274}"));}catch(NotSupportedException){}var transform=new TransformGroup();if(orientation is 2 or 4 or 5 or 7)transform.Children.Add(new ScaleTransform(-1,1));if(orientation is 3 or 4)transform.Children.Add(new RotateTransform(180));else if(orientation is 6 or 7)transform.Children.Add(new RotateTransform(90));else if(orientation is 5 or 8)transform.Children.Add(new RotateTransform(270));if(transform.Children.Count>0)image=new TransformedBitmap(image,transform);var result=new List<ImagePayload>();foreach(var (id,width,height) in photo?PhotoFormats:CoverFormats){var scale=photo?Math.Min((double)width/image.PixelWidth,(double)height/image.PixelHeight):Math.Max((double)width/image.PixelWidth,(double)height/image.PixelHeight);var draw=new DrawingVisual();using(var context=draw.RenderOpen()){context.DrawRectangle(Brushes.Black,null,new Rect(0,0,width,height));context.DrawImage(image,new Rect((width-image.PixelWidth*scale)/2,(height-image.PixelHeight*scale)/2,image.PixelWidth*scale,image.PixelHeight*scale));}var bitmap=new RenderTargetBitmap(width,height,96,96,PixelFormats.Pbgra32);bitmap.Render(draw);var raw=new byte[width*height*4];bitmap.CopyPixels(raw,width*4,0);var pixels=new byte[width*height*2];for(var i=0;i<width*height;i++){var word=(ushort)(((raw[i*4+2]>>3)<<11)|((raw[i*4+1]>>2)<<5)|(raw[i*4]>>3));pixels[i*2]=(byte)word;pixels[i*2+1]=(byte)(word>>8);}result.Add(new(id,width,height,pixels));}return result;}
    public static BitmapSource Decode(string root,NativeImageReference image,bool photo){var relative=image.FileName.TrimStart(':').Replace(':','/');var path=DeviceAccess.SafePath(root,(photo?"Photos/":"iPod_Control/Artwork/")+relative);if(image.Width<=0||image.Height<=0||image.Size<checked(image.Width*image.Height*2)||image.Size>16*1024*1024)throw new IOException("图片尺寸无效。");using var stream=File.OpenRead(path);if(image.Offset<0||stream.Length-image.Offset<image.Size)throw new IOException("图片引用越界。");stream.Position=image.Offset;var raw=new byte[image.Width*image.Height*2];stream.ReadExactly(raw);var bitmap=BitmapSource.Create(image.Width,image.Height,96,96,PixelFormats.Bgr565,null,raw,image.Width*2);bitmap.Freeze();return bitmap;}
    public static void SavePng(BitmapSource source,string file){var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(source));using var stream=File.Create(file);encoder.Save(stream);}
}
