using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using iTunesPod.Infrastructure;
using Microsoft.Win32;
namespace iTunesPod.App;
public sealed partial class MainWindow
{
    NativeImageDatabase PhotoDatabase(iTunesPod.Core.DeviceSession? session=null){var path=DeviceAccess.SafePath((session??_device)!.Root,"Photos/Photo Database");return new(File.Exists(path)?File.ReadAllBytes(path):null,true);}
    async Task AddDevicePhotos(){if(TargetDevice==null){Notify("先连接 iPod。");return;}var picker=new OpenFileDialog{Title="选择同步到 iPod 的照片",Filter="照片|*.jpg;*.jpeg;*.png",Multiselect=true};if(picker.ShowDialog(this)!=true)return;var keepOriginal=new CheckBox{Content="保留原图（用于完整质量导出）",IsChecked=_store.GetPreference("photo-originals","true")=="true"};if(!ShowDialog("照片导入选项",keepOriginal,true))return;_store.SetPreference("photo-originals",keepOriginal.IsChecked==true?"true":"false");var database=PhotoDatabase(TargetDevice);var changes=new List<FileChange>();var ids=new List<int>();foreach(var path in picker.FileNames){_status.Text="处理照片："+Path.GetFileName(path);var payloads=NativeImages.Encode(path,true);var addition=database.AddImage(0,payloads,"Photos/Thumbs",keepOriginal.IsChecked==true?Path.GetFileName(path):null,keepOriginal.IsChecked==true?await File.ReadAllBytesAsync(path):null);changes.AddRange(addition.Files);ids.Add(addition.Id);}var master=database.Albums().First(x=>x.IsMaster);database.SetAlbum(master.Id,master.Name,master.Images.Concat(ids).ToArray());var albumName=Prompt("新增照片相册名称","新照片");if(albumName==null)return;database.AddAlbum(albumName,ids);changes.Add(database.Change("Photos/Photo Database"));var bytes=changes.Sum(x=>x.Content?.LongLength??0);if(bytes+64L*1024*1024>TargetDevice.FreeBytes)throw new IOException("设备空间不足。");if(MessageBox.Show(this,$"添加 {ids.Count} 张照片，共 {Bytes(bytes)}，创建相册“{albumName}”？提交前自动备份。","照片同步预览",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return;await CommitFiles(changes,"同步照片");DevicePhotos();}
    void DevicePhotos(){if(_device==null){Notify("先连接 iPod。");return;}var database=PhotoDatabase();var panel=Stack(Row(T("iPod 照片",22),Action("添加照片",AddDevicePhotos,"add",true),Action("新建相册",async()=>{var name=Prompt("新建相册");if(!string.IsNullOrWhiteSpace(name)){database.AddAlbum(name,[]);await CommitFiles([database.Change("Photos/Photo Database")],"新建相册");DevicePhotos();}})));
        foreach(var album in database.Albums()){panel.Children.Add(Row(T(album.Name+" · "+album.Images.Count+" 张",20),Action("选择相册照片",()=>EditPhotoAlbum(database,album)),Action("重命名",async()=>{if(album.IsMaster){Notify("系统相册不能重命名。");return;}var name=Prompt("重命名相册",album.Name);if(name!=null){database.SetAlbum(album.Id,name,album.Images);await CommitFiles([database.Change("Photos/Photo Database")],"重命名相册");DevicePhotos();}}),Action("删除相册",async()=>{if(MessageBox.Show(this,"删除相册并保留照片？","照片",MessageBoxButton.OKCancel)==MessageBoxResult.OK){database.RemoveAlbum(album.Id);await CommitFiles([database.Change("Photos/Photo Database")],"删除相册");DevicePhotos();}})));var wrap=new WrapPanel();foreach(var image in database.Images().Where(x=>album.Images.Contains(x.Id))){var reference=image.Images.FirstOrDefault(x=>x.Format==1024)??image.Images.FirstOrDefault(x=>x.Width>0);if(reference==null)continue;var card=Stack();try{card.Children.Add(new Image{Source=NativeImages.Decode(_device.Root,reference,true),Width=150,Height=115,Stretch=Stretch.Uniform});}catch(IOException){card.Children.Add(T("图像数据缺失",12,true));}card.Children.Add(T("照片 "+image.Id,11,true));card.Children.Add(Action("导出原图",()=>ExportOriginalPhoto(image)));card.Children.Add(Row(Action("导出",()=>{var save=new SaveFileDialog{FileName="照片-"+image.Id+".png",Filter="PNG|*.png"};if(save.ShowDialog(this)==true){if(Path.GetFullPath(save.FileName).StartsWith(Path.GetFullPath(_device.Root),StringComparison.OrdinalIgnoreCase))throw new IOException("导出请选择电脑目录。");NativeImages.SavePng(NativeImages.Decode(_device.Root,reference,true),save.FileName);}return Task.CompletedTask;}),Action("删除",async()=>{if(MessageBox.Show(this,"从设备照片资料库删除此照片？缩略图与原图会在恢复备份中保留。","照片",MessageBoxButton.OKCancel)==MessageBoxResult.OK){database.RemoveImage(image.Id);await CommitFiles([database.Change("Photos/Photo Database")],"删除照片");DevicePhotos();}})));card.Margin=new(0,16,20,10);wrap.Children.Add(card);}panel.Children.Add(wrap);}_page.Content=new ScrollViewer{Content=panel};}
}
