using System.IO;
using System.Security.Cryptography;
using System.Windows;
using System.Windows.Controls;
using iTunesPod.Core;
using iTunesPod.Infrastructure;
using Microsoft.Win32;
namespace iTunesPod.App;
public sealed partial class MainWindow
{
    async Task SyncPlaylist(Playlist list){if(TargetDevice==null){Notify("先连接 iPod。");return;}var map=_tracks.ToDictionary(x=>x.Id);var sources=list.TrackIds.Where(map.ContainsKey).Select(id=>map[id]).ToArray();var progress=new Progress<string>(s=>_status.Text=s);var sync=new DeviceSync(_store.DataDirectory);var plan=await Task.Run(()=>sync.PrepareAsync(TargetDevice,sources,progress,_lifetime.Token));plan=await AttachCovers(plan);var ids=plan.ExistingMatches.Concat(plan.Media.Select(x=>new KeyValuePair<string,uint>(x.SourceId,x.Write.Id))).ToDictionary(x=>x.Key,x=>"device:"+x.Value);var converted=list.TrackIds.Select(id=>ids.TryGetValue(id,out var match)?match:throw new IOException("列表来源失效，不能静默丢弃引用。")).ToArray();var target=new Playlist("device-playlist:"+Convert.ToHexString(RandomNumberGenerator.GetBytes(8)),list.Name,converted,list.IsSmart){SmartDefinition=list.SmartDefinition};var data=await File.ReadAllBytesAsync(plan.DatabasePath);data=DeviceDatabaseEdits.Apply(data,TargetDevice.SigningIdentity,playlists:new ITunesDbReader().ReadPlaylists(data).Append(target).ToArray());await File.WriteAllBytesAsync(plan.DatabasePath,data);await using var db=File.OpenRead(plan.DatabasePath);plan=DeviceSync.Seal(plan with{DatabaseHash=Convert.ToHexString(await SHA256.HashDataAsync(db))});if(MessageBox.Show(this,$"同步列表“{list.Name}”（{converted.Length} 项），新增 {plan.Media.Count} 个媒体文件、复用 {plan.ExistingMatches.Count} 个已有曲目？","列表同步预览",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return;await Task.Run(()=>sync.CommitAsync(plan,progress,_lifetime.Token));await Discover(true);Notify("列表同步完成。");}
    async Task CreateSmartPlaylist(bool device,Playlist? existing=null){var name=new TextBox{Text=existing?.Name??"智能播放列表"};var conjunction=new ComboBox{ItemsSource=new[]{"满足全部条件（AND）","满足任一条件（OR）"},SelectedIndex=existing?.SmartDefinition?.MatchAll==false?1:0};var sorts=new ComboBox{ItemsSource=new[]{"标题","艺术家","专辑","评分","播放次数","最近添加","最近播放"},SelectedItem=existing?.SmartDefinition?.Sort??"标题"};var unit=new ComboBox{ItemsSource=new[]{"首","分钟","小时"},SelectedItem=existing?.SmartDefinition?.LimitUnit??"首"};var limit=new TextBox{Text=(existing?.SmartDefinition?.Limit??25).ToString()};var rows=Stack();var editors=new List<(ComboBox Field,ComboBox Comparison,TextBox Value)>();void AddRule(SmartRule? rule=null){var field=new ComboBox{ItemsSource=SmartPlaylists.Fields.Values.ToArray(),SelectedItem=rule==null?"艺术家":SmartPlaylists.Fields[rule.Field],MinWidth=115};var comparison=new ComboBox{ItemsSource=new[]{"包含","不包含","等于","不等于","开头是","结尾是","大于","小于","在最近天数内","不在最近天数内"},SelectedItem=rule?.Comparison??"包含",MinWidth=90};var value=new TextBox{Text=rule?.Value??"",MinWidth=180};editors.Add((field,comparison,value));rows.Children.Add(Row(field,comparison,value));}foreach(var rule in existing?.SmartDefinition?.Rules??[new(4,"包含","")])AddRule(rule);var panel=Stack(name,conjunction,rows,Action("添加条件",()=>{AddRule();return Task.CompletedTask;}),T("排序",12),sorts,T("最大数量或时长（0 表示不限）",12),Row(limit,unit));if(!ShowDialog("智能播放列表",new ScrollViewer{Content=panel},true))return;var rules=editors.Select(x=>new SmartRule(SmartPlaylists.Fields.Single(p=>p.Value==x.Field.SelectedItem?.ToString()).Key,x.Comparison.SelectedItem?.ToString()??"等于",x.Value.Text)).ToArray();if(!int.TryParse(limit.Text,out var maximum))throw new IOException("数量需要整数。");var definition=new SmartDefinition(conjunction.SelectedIndex==0,rules,sorts.SelectedItem?.ToString()??"标题",maximum,unit.SelectedItem?.ToString()??"首");var selected=SmartPlaylists.Evaluate(definition,device?TargetDevice!.Tracks:_tracks);var id=existing?.Id??(device?"device-playlist:"+Convert.ToHexString(RandomNumberGenerator.GetBytes(8)):Guid.NewGuid().ToString("N"));await SavePlaylist(new(id,name.Text.Trim(),selected.Select(x=>x.Id).ToArray(),true){SmartDefinition=definition},device);}
    async Task SavePlaylist(Playlist list,bool device){if(!device){_store.SavePlaylist(list);Playlists();return;}var data=await File.ReadAllBytesAsync(DeviceAccess.SafePath(TargetDevice!.Root,TargetDevice.DatabaseFile));var lists=TargetDevice.Playlists.Where(x=>x.Id!=list.Id).Append(list).ToArray();await CommitFiles([new(TargetDevice.DatabaseFile,DeviceDatabaseEdits.Apply(data,TargetDevice.SigningIdentity,playlists:lists))],"保存设备播放列表");await Discover(true);Playlists(true);}
    async Task DeletePlaylist(Playlist list,bool device){if(list.IsSystem)throw new IOException("系统列表不能删除。");if(MessageBox.Show(this,"删除列表并保留歌曲？","播放列表",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return;if(!device){_store.DeletePlaylist(list.Id);Playlists();return;}var data=await File.ReadAllBytesAsync(DeviceAccess.SafePath(TargetDevice!.Root,TargetDevice.DatabaseFile));await CommitFiles([new(TargetDevice.DatabaseFile,DeviceDatabaseEdits.Apply(data,TargetDevice.SigningIdentity,playlists:TargetDevice.Playlists.Where(x=>x.Id!=list.Id).ToArray()))],"删除设备播放列表");await Discover(true);Playlists(true);}
    async Task EditPlaylist(Playlist list,bool device){if(list.IsSmart){if(list.SmartDefinition!=null)await CreateSmartPlaylist(device,list);else Notify("未知智能列表规则保持原样，可复制为普通列表后编辑。");return;}if(list.IsSystem){Notify("系统列表由设备资料库维护。");return;}var source=device?TargetDevice!.Tracks:_tracks;var map=source.ToDictionary(x=>x.Id);var ids=list.TrackIds.ToList();var name=new TextBox{Text=list.Name};var entries=new ListBox{MinHeight=190,MaxHeight=230};void Render(){entries.ItemsSource=ids.Select(id=>map.TryGetValue(id,out var track)?track.Artist+" — "+track.Title:"失效引用："+id).ToArray();}Render();Task Move(int offset){var at=entries.SelectedIndex;if(at<0||at+offset<0||at+offset>=ids.Count)return Task.CompletedTask;(ids[at],ids[at+offset])=(ids[at+offset],ids[at]);Render();entries.SelectedIndex=at+offset;return Task.CompletedTask;}var panel=Stack(name,entries,Row(Action("上移",()=>Move(-1)),Action("下移",()=>Move(1)),Action("移除",()=>{var at=entries.SelectedIndex;if(at>=0){ids.RemoveAt(at);Render();}return Task.CompletedTask;}),Action("添加歌曲",()=>{var chooser=new ListBox{ItemsSource=source,DisplayMemberPath="Title",SelectionMode=SelectionMode.Extended};if(ShowDialog("选择加入列表的歌曲",chooser,true)){ids.AddRange(chooser.SelectedItems.Cast<Track>().Select(x=>x.Id));Render();}return Task.CompletedTask;})));if(ShowDialog("编辑播放列表",panel,true))await SavePlaylist(list with{Name=name.Text.Trim(),TrackIds=ids},device);}
    async Task CreatePlaylist(bool device){var name=Prompt("新建播放列表");if(string.IsNullOrWhiteSpace(name))return;var id=device?"device-playlist:"+Convert.ToHexString(RandomNumberGenerator.GetBytes(8)):Guid.NewGuid().ToString("N");await SavePlaylist(new(id,name,[]),device);}
    Task ExportPlaylist(Playlist list,bool device){var picker=new SaveFileDialog{FileName=list.Name+".m3u8",Filter="M3U8|*.m3u8|M3U|*.m3u"};if(picker.ShowDialog(this)==true){if(_sessions.Values.Any(x=>Path.GetFullPath(picker.FileName).StartsWith(Path.GetFullPath(x.Root),StringComparison.OrdinalIgnoreCase)))throw new IOException("请选择电脑导出目录。");var map=(device?TargetDevice!.Tracks:_tracks).ToDictionary(x=>x.Id);PlaylistFiles.Write(picker.FileName,list.TrackIds.Where(map.ContainsKey).Select(x=>map[x]));}return Task.CompletedTask;}
    async Task ImportPlaylist(){var picker=new OpenFileDialog{Filter="播放列表|*.m3u;*.m3u8"};if(picker.ShowDialog(this)!=true)return;var files=PlaylistFiles.Read(picker.FileName);await Import(files);var tracks=_tracks;var ids=new List<string>();foreach(var path in files){var track=tracks.FirstOrDefault(x=>x.Path.Equals(path,StringComparison.OrdinalIgnoreCase));if(track==null&&File.Exists(path)){await using var file=File.OpenRead(path);var hash=Convert.ToHexString(await SHA256.HashDataAsync(file));track=tracks.FirstOrDefault(x=>x.Hash==hash);}if(track!=null)ids.Add(track.Id);}await SavePlaylist(new(Guid.NewGuid().ToString("N"),Path.GetFileNameWithoutExtension(picker.FileName),ids),false);if(ids.Count!=files.Count)Notify($"列表导入 {ids.Count} 首，{files.Count-ids.Count} 个来源无法导入，请检查任务错误。");}
}
