using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using iTunesPod.Infrastructure;
namespace iTunesPod.App;
public sealed partial class MainWindow
{
    List<PodcastEpisode> Episodes()=>JsonSerializer.Deserialize<List<PodcastEpisode>>(_store.GetPreference("podcast-episodes","[]"))??[];
    List<string> Feeds()=>JsonSerializer.Deserialize<List<string>>(_store.GetPreference("podcast-feeds","[]"))??[];
    void SaveEpisodes(IEnumerable<PodcastEpisode> episodes)=>_store.SetPreference("podcast-episodes",JsonSerializer.Serialize(episodes));
    void Podcasts(){var feeds=Feeds();var episodes=Episodes();var panel=Stack(Row(Action("添加 RSS 订阅",async()=>{var url=Prompt("Podcast RSS 地址");if(string.IsNullOrWhiteSpace(url))return;PodcastService.ValidateUrl(url);var discovered=await new PodcastService().RefreshAsync(url,_lifetime.Token);if(!feeds.Contains(url))feeds.Add(url);_store.SetPreference("podcast-feeds",JsonSerializer.Serialize(feeds));SaveEpisodes(episodes.Concat(discovered).DistinctBy(x=>x.Id));Podcasts();},"add",true),Action("刷新全部",async()=>{var result=Episodes();foreach(var feed in Feeds()){_status.Text="刷新："+feed;var fetched=await new PodcastService().RefreshAsync(feed,_lifetime.Token);var old=result.ToDictionary(x=>x.Id);foreach(var entry in fetched){if(!old.ContainsKey(entry.Id))result.Add(entry);}}SaveEpisodes(result);Podcasts();},"refresh")));
        PodcastOptions(panel);if(feeds.Count==0)panel.Children.Add(T("粘贴 Podcast 的 RSS 地址，订阅后选择单集下载。下载完成的单集可加入 iPod 同步草稿。",13,true));
        foreach(var feed in feeds){var list=episodes.Where(x=>x.Feed==feed).OrderByDescending(x=>x.Published).ToArray();var show=list.FirstOrDefault()?.Show??feed;panel.Children.Add(Row(T(show,22),Action("取消订阅",()=>{var current=Feeds();current.Remove(feed);_store.SetPreference("podcast-feeds",JsonSerializer.Serialize(current));SaveEpisodes(Episodes().Where(x=>x.Feed!=feed));Podcasts();return Task.CompletedTask;}),Action("下载未下载单集",async()=>{foreach(var entry in list.Where(x=>x.DownloadPath==null))await DownloadEpisode(entry);Podcasts();})));foreach(var episode in list){var label=T(episode.Title+"\n"+(episode.Published?.ToString("yyyy-MM-dd")??"")+" · "+(episode.Played?"已播放":"未播放")+" · "+(File.Exists(episode.DownloadPath)?"已下载":"未下载"),13);var row=Row(label,Action(File.Exists(episode.DownloadPath)?"播放":"下载",async()=>{if(File.Exists(episode.DownloadPath)){var track=_tracks.FirstOrDefault(x=>x.Path.Equals(episode.DownloadPath,StringComparison.OrdinalIgnoreCase));if(track!=null)await Play(track);}else await DownloadEpisode(episode);Podcasts();},"play"),Action("加入 iPod",()=>{var track=_tracks.FirstOrDefault(x=>x.Path.Equals(episode.DownloadPath,StringComparison.OrdinalIgnoreCase));if(track==null)Notify("先下载此单集。");else AddDraft([track]);return Task.CompletedTask;}),Action(episode.Played?"标为未播放":"标为已播放",()=>{MarkEpisodePlayed(episode.Id,!episode.Played);Podcasts();return Task.CompletedTask;}));row.Margin=new(0,12,0,12);panel.Children.Add(row);}}
        _subtitle.Text=feeds.Count+" 个订阅 · "+episodes.Count+" 集";_page.Content=new ScrollViewer{Content=panel};
    }
    async Task DownloadEpisode(PodcastEpisode episode){if(_downloads.ContainsKey(episode.Id)){Notify("此单集正在下载。");return;}using var cancellation=CancellationTokenSource.CreateLinkedTokenSource(_lifetime.Token);_downloads[episode.Id]=cancellation;var activity=StartActivity("下载 Podcast",episode.Title);if(_route=="Podcast")Podcasts();try{var progress=new Progress<string>(s=>_status.Text=s);var file=await new PodcastService().DownloadAsync(episode,Path.Combine(_store.DataDirectory,"podcasts"),progress,cancellation.Token);await Import([file]);var track=_tracks.First(x=>x.Path.Equals(file,StringComparison.OrdinalIgnoreCase));_store.SaveTracks([track with{Title=episode.Title,Artist=episode.Show,Album=episode.Show,AlbumArtist=episode.Show,MediaType=4,PodcastFeed=episode.Feed,EpisodeId=episode.Id,EnclosureUrl=episode.Url,Description=episode.Description}]);_tracks=_store.LoadTracks();SaveEpisodes(Episodes().Select(x=>x.Id==episode.Id?x with{DownloadPath=file}:x));activity.State="已完成";}catch(OperationCanceledException){activity.State="已取消";}catch{activity.State="失败";throw;}finally{_downloads.Remove(episode.Id);SaveActivities();}}
}
