using System.IO;
using System.Text.Json;
using System.Windows.Controls;
using iTunesPod.Infrastructure;
using Microsoft.Win32;
namespace iTunesPod.App;
public sealed partial class MainWindow
{
    void BackupSettings(StackPanel panel){panel.Children.Add(T("备份与缓存",22));var limit=new TextBox{Text=_store.GetPreference("cache-limit-gb","10"),Width=75};panel.Children.Add(Row(T("转码缓存上限（GiB）",12),limit,Action("保存上限",()=>{if(!int.TryParse(limit.Text,out var value)||value<1||value>1024)throw new IOException("缓存上限需要 1—1024 GiB。");_store.SetPreference("cache-limit-gb",value.ToString());return Task.CompletedTask;})));if(_device!=null){var key="statistics-enabled:"+_device.DeviceId;var enabled=new CheckBox{Content="将此设备播放统计回传至电脑索引",IsChecked=_store.GetPreference(key,"true")=="true"};enabled.Click+=(_,_)=>_store.SetPreference(key,enabled.IsChecked==true?"true":"false");panel.Children.Add(enabled);}panel.Children.Add(T("备份目录："+_store.GetPreference("backup-directory",Path.Combine(_store.DataDirectory,"backups")),12,true));panel.Children.Add(Action("选择备份目录",()=>{var picker=new OpenFolderDialog{Title="选择电脑上的备份目录"};if(picker.ShowDialog(this)==true){if(_sessions.Values.Any(x=>(Path.GetFullPath(picker.FolderName)+Path.DirectorySeparatorChar).StartsWith(Path.GetFullPath(x.Root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)))throw new IOException("备份目录必须在 iPod 之外。");_store.SetPreference("backup-directory",picker.FolderName);Settings();}return Task.CompletedTask;},"folder"));panel.Children.Add(Action("清理旧备份（保留最新 10 份）",()=>{if(_device==null){Notify("先选择设备。");return Task.CompletedTask;}var count=DeviceBackup.Prune(DeviceBackup.Destination(_store.DataDirectory,_device.DeviceId),_store.DataDirectory,10);Notify("清理 "+count+" 份旧备份，未完成任务依赖的备份会保留。");return Task.CompletedTask;}));panel.Children.Add(Action("清理转码缓存",()=>{if(_activities.Any(x=>x.State is "进行中" or "等待提交")||_scan!=null)throw new IOException("还有未结束任务，暂不能清理缓存。");var folder=DeviceAccess.SafePath(_store.DataDirectory,"transcode");if(Directory.Exists(folder)){foreach(var file in Directory.EnumerateFiles(folder)){var safe=DeviceAccess.SafePath(folder,Path.GetFileName(file));File.Delete(safe);}}Notify("转码缓存已清理。");return Task.CompletedTask;}));}
    readonly List<FileSystemWatcher> _watches=[];readonly HashSet<string> _watchQueue=new(StringComparer.OrdinalIgnoreCase);readonly System.Windows.Threading.DispatcherTimer _watchTimer=new(){Interval=TimeSpan.FromSeconds(5)};
    void SetupWatches(){foreach(var watcher in _watches)watcher.Dispose();_watches.Clear();_watchTimer.Stop();_watchTimer.Tick-=WatchTick;_watchTimer.Tick+=WatchTick;var folders=JsonSerializer.Deserialize<List<string>>(_store.GetPreference("watched-folders","[]"))??[];foreach(var folder in folders.Where(Directory.Exists)){var watcher=new FileSystemWatcher(folder){IncludeSubdirectories=true,NotifyFilter=NotifyFilters.FileName|NotifyFilters.LastWrite|NotifyFilters.Size};void Queue(string path)=>Dispatcher.BeginInvoke(()=>{_watchQueue.Add(new[]{".jpg",".jpeg",".png"}.Contains(Path.GetExtension(path).ToLowerInvariant())?Path.GetDirectoryName(path)!:path);});watcher.Created+=(_,e)=>Queue(e.FullPath);watcher.Changed+=(_,e)=>Queue(e.FullPath);watcher.Deleted+=(_,e)=>Queue(e.FullPath);watcher.Renamed+=(_,e)=>{Queue(e.OldFullPath);Queue(e.FullPath);};watcher.Error+=(_,_)=>Queue(folder);watcher.EnableRaisingEvents=true;_watches.Add(watcher);}_watchTimer.Start();}
    async void WatchTick(object? sender,EventArgs e){if(_scan!=null||_watchQueue.Count==0)return;var files=_watchQueue.ToArray();_watchQueue.Clear();await Guard(async()=>{await Import(files.Where(x=>File.Exists(x)||Directory.Exists(x)));_images.Clear();Navigate(_route);});}
    void LanguageSettings(StackPanel panel){var language=new ComboBox{ItemsSource=new[]{"简体中文","繁體中文"},SelectedIndex=UiLanguage.Traditional?1:0};panel.Children.Add(Row(T("界面语言",12),language,Action("保存语言",()=>{UiLanguage.Traditional=language.SelectedIndex==1;_store.SetPreference("language",UiLanguage.Traditional?"traditional":"simplified");Notify("语言已保存，重新打开应用后全部界面生效。");Navigate("设置");return Task.CompletedTask;})));}
    void ConversionSettings(StackPanel panel){var ffmpeg=new TextBox{Text=_store.GetPreference("ffmpeg","ffmpeg"),MinWidth=350};var ffprobe=new TextBox{Text=_store.GetPreference("ffprobe","ffprobe"),MinWidth=350};panel.Children.Add(T("转换工具",22));panel.Children.Add(T("自动使用随包工具或系统 PATH；也可填写可执行文件路径。",12,true));panel.Children.Add(T("FFmpeg",12));panel.Children.Add(ffmpeg);panel.Children.Add(T("FFprobe",12));panel.Children.Add(ffprobe);panel.Children.Add(Row(Action("保存工具设置",()=>{_store.SetPreference("ffmpeg",ffmpeg.Text.Trim());_store.SetPreference("ffprobe",ffprobe.Text.Trim());Notify("工具路径已保存。");return Task.CompletedTask;}),Action("检查工具",async()=>{var first=await MediaTools.RunAsync(ffmpeg.Text.Trim(),["-version"],_lifetime.Token);var second=await MediaTools.RunAsync(ffprobe.Text.Trim(),["-version"],_lifetime.Token);Notify(first.Split('\n')[0]+"\n"+second.Split('\n')[0]);})));}
    void SourceSettings(StackPanel panel){panel.Children.Add(T("自动扫描来源文件夹",22));panel.Children.Add(Action("添加监视文件夹",async()=>{var picker=new OpenFolderDialog{Title="选择音乐来源文件夹"};if(picker.ShowDialog(this)==true){if(Directory.Exists(Path.Combine(picker.FolderName,"iPod_Control")))throw new IOException("设备目录不能作为电脑来源监视目录。");var folders=JsonSerializer.Deserialize<List<string>>(_store.GetPreference("watched-folders","[]"))??[];if(!folders.Contains(picker.FolderName,StringComparer.OrdinalIgnoreCase))folders.Add(picker.FolderName);_store.SetPreference("watched-folders",JsonSerializer.Serialize(folders));await Import([picker.FolderName]);SetupWatches();Settings();}},"folder"));foreach(var folder in JsonSerializer.Deserialize<List<string>>(_store.GetPreference("watched-folders","[]"))??[]){panel.Children.Add(Row(T(folder,12,true),Action("停止监视",()=>{var current=JsonSerializer.Deserialize<List<string>>(_store.GetPreference("watched-folders","[]"))??[];current.Remove(folder);_store.SetPreference("watched-folders",JsonSerializer.Serialize(current));SetupWatches();Settings();return Task.CompletedTask;})));}}
    void NetworkSettings(StackPanel panel){var online=new CheckBox{Content="允许手动下载网络封面",IsChecked=_store.GetPreference("online-covers","false")=="true"};online.Click+=(_,_)=>_store.SetPreference("online-covers",online.IsChecked==true?"true":"false");panel.Children.Add(online);panel.Children.Add(T("日志",22));panel.Children.Add(Action("导出任务日志",async()=>{var picker=new SaveFileDialog{FileName="iTunesPod-tasks.json",Filter="JSON|*.json"};if(picker.ShowDialog(this)==true){var entries=_activities.Select(x=>new{Title=LogRedactor.Redact(x.Title),x.State,x.Time,Detail=LogRedactor.Redact(x.Detail)});await File.WriteAllTextAsync(picker.FileName,JsonSerializer.Serialize(entries,new JsonSerializerOptions{WriteIndented=true}));}}));}

}
