using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using iTunesPod.Core;
namespace iTunesPod.App;
public sealed partial class MainWindow
{
    async Task Validate(string output,string? root){Directory.CreateDirectory(output);_dark=false;ApplyTheme();var checks=new List<string>();if(root!=null){var session=await Task.Run(()=>_devices.InspectAsync(root));if(session.ReadError!=null)throw new InvalidDataException(session.ReadError);_sessions[session.Root]=session;SelectDevice(session);await ReadArtwork(session);RebuildDevices();checks.Add("设备识别与数据库读取");_deviceTab="歌曲";Navigate("设备");if(_table!.Items.Count!=_device!.Tracks.Count)throw new InvalidDataException("曲目数不一致");var first=_device.Tracks.First(x=>File.Exists(x.Path));_filter!(first.Title);if(!_table.Items.Cast<Track>().Any(x=>x.Id==first.Id))throw new InvalidDataException("搜索失败");if(await Task.Run(()=>PlaybackController.DecodeProbe(first.Path))<=0)throw new InvalidDataException("解码为空");checks.Add("曲目表、搜索与真实解码，无声音输出");_volume.Value=.25;if(Math.Abs(_player.Volume-.25)>0.001)throw new InvalidDataException("音量未接入播放引擎");_volume.Value=.5;checks.Add("音量控件与播放引擎连接");Navigate("新发现");_search.Text=first.Title;if(_table==null||!_table.Items.Cast<Track>().Any(x=>x.Id==first.Id))throw new InvalidDataException("侧栏搜索失败");checks.Add("侧栏搜索自动进入资料库并显示匹配歌曲");Navigate("新发现");var home=(System.Windows.Controls.StackPanel)((System.Windows.Controls.ScrollViewer)_page.Content).Content;var cards=(System.Windows.Controls.Grid)home.Children[0];((System.Windows.Controls.Button)cards.Children[0]).RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Button.ClickEvent));if(_table==null||_table.Items.Count==0)throw new InvalidDataException("专辑卡片未打开曲目");checks.Add("专辑卡片点击打开曲目页");}
        foreach(var route in new[]{"新发现","主页","歌曲","专辑","最近添加","艺术家","播放列表","设备","传输任务","设置","图片","视频","Podcast","关于"}){Navigate(route);await Shot(output,route);}
        if(_device!=null){foreach(var tab in new[]{"概览","歌曲","专辑","播放列表","照片","备忘录","快照"}){_deviceTab=tab;Navigate("设备");await Shot(output,"device-"+tab);}_deviceTab="歌曲";Navigate("设备");Inspect(_device.Tracks.First(x=>File.Exists(x.Path)),true);await Shot(output,"device-detail");_dark=true;ApplyTheme();Navigate("新发现");await Shot(output,"discovery-dark");_deviceTab="概览";Navigate("设备");await Shot(output,"device-dark");Width=1060;Height=760;Navigate("新发现");await Shot(output,"discovery-compact");}
        foreach(var section in new[]{"常规","资料库","设备","转换","备份与缓存","网络与日志","关于"}){_settingsTab=section;Navigate("设置");await Shot(output,"settings-"+section);} _settingsTab="常规";UiLanguage.Traditional=true;if(T("设置").Text!="設置")throw new IOException("繁体中文转换失败。");Navigate("设置");await Shot(output,"settings-traditional");UiLanguage.Traditional=false;checks.Add("简体与繁体中文界面设置");await File.WriteAllTextAsync(Path.Combine(output,"result.json"),JsonSerializer.Serialize(new{Framework="WPF",Checks=checks,Device=_device?.Model,Tracks=_device?.Tracks.Count,Missing=_device?.Tracks.Count(x=>!File.Exists(x.Path)),Playlists=_device?.Playlists.Count,Covers=_device?.Tracks.Count(x=>x.CoverPath!=null)},new JsonSerializerOptions{WriteIndented=true}));}
    async Task Shot(string output,string name){await Task.Delay(220);UpdateLayout();var visual=(FrameworkElement)Content;var image=new RenderTargetBitmap(Math.Max(1,(int)visual.ActualWidth),Math.Max(1,(int)visual.ActualHeight),96,96,PixelFormats.Pbgra32);image.Render(visual);var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(image));using var file=File.Create(Path.Combine(output,name+".png"));png.Save(file);}
}


